### ISSUE TITLE
Bug: Some media controls doesnt work, their buttons are greyed out to be more specific. the buttons that are greyed out are the previous, pause, next and stop buttons

### ISSUE THREAD

**Issue by chuchigod** [ModernFlyouts-Community/ModernFlyouts#773] opened 2021-08-24 18:09 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-08-25 10:04
Which media app? What is the windows version? What is the app version? You need to provide us these details or else we cant help you.

**Comment by chuchigod** [comment] 2021-08-25 14:30
sorry for not providing the details, It happens when I'm playing music on spotify. It doesn't happen every time but sometimes the buttons are just greyed out.
That was the case yesterday but today for some reason, the buttons are working just fine.
my windows 21H1 build version is 19043.1165
and my ModernFlyouts version is 0.9.30
I don't have the screenshots for the greyed out buttons now because now they are fixed... but ill post again if this happens again.
Thank you.

**Comment by cuadril** [comment] 2021-08-31 00:14
I have the same issue. Did you manage to fix it?

**Comment by CrisApple** [comment] 2021-08-31 01:20
> I have the same issue. Did you manage to fix it?

Nope it just comes and goes. :/

**Comment by Cyberdroid1** [comment] 2021-09-05 03:21
Closing as duplicate of #765

**Closed by Cyberdroid1** 2021-09-05 03:21 UTC
Labels: Bug
