### ISSUE TITLE
App crashes when disabling Audio Flyout

### ISSUE THREAD

**Issue by iqfareez** [ModernFlyouts-Community/ModernFlyouts#1103] opened 2022-09-22 00:57 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 22H2

### OS build

22621.521

### Platform

x64

### Area(s) with issue?

General, Audio Flyout

### Steps to reproduce

1. Open ModernFlyout settings
2. Go to Flyouts module > Audio
3. Disable the currently enabled **Enable Audio Flyout** switch.
4. App lags and crashed

### ✔️ Expected Behavior

The option can be disabled successfully

### ❌ Actual Behavior

App lags for a few seconds and crashes

![Screenshot 2022-09-22 082646](https://user-images.githubusercontent.com/60868965/191635180-7f25232d-53fc-423a-ae93-3b041a7c7f12.jpg)

### Additional Context

Resetting the app wouldn't work because the default settings is on.

**Comment by Samuel12321** [comment] 2022-10-02 02:25
Hi,
Thanks for reporting this. We are aware of the problem and plan to fix this in the next update 0.11.

Closing as duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/888

**Closed by Samuel12321** 2022-10-02 02:25 UTC
Labels: Bug
