### ISSUE TITLE
Feature Request:Add blur effects 

### ISSUE THREAD

**Issue by aunight** [ModernFlyouts-Community/ModernFlyouts#727] opened 2021-08-03 02:08 UTC
I think the blur effect it will made this app better.

**Comment by ShankarBUS** [comment] 2021-08-03 06:30
We are exploring the possiblities. We might make some progress in v0.11.

**Comment by Samuel12321** [comment] 2021-08-03 08:33
Duplicate of #66

**Closed by Samuel12321** 2021-08-03 08:33 UTC
Labels: Enhancement
