### ISSUE TITLE
Don't work music and volume widget when you use touchpad to adjust the volume.

### ISSUE THREAD

**Issue by BoGodAkim** [ModernFlyouts-Community/ModernFlyouts#525] opened 2021-03-24 16:47 UTC
Don't work music and volume widget when you use touchpad to adjust the volume.

**Comment by BoGodAkim** [comment] 2021-03-24 16:47
![image](https://user-images.githubusercontent.com/56846337/112349476-d092b700-8cd9-11eb-9aab-e66332da54d7.png)

**Comment by Samuel12321** [comment] 2021-03-24 22:05
duplicate of #4

**Closed by Samuel12321** 2021-03-24 22:05 UTC
