### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by caryleo** [ModernFlyouts-Community/ModernFlyouts#557] opened 2021-04-10 12:32 UTC
**Describe the bug:**

(Found a similar issue #522 , maybe you can close this one after you solve it :) ) I use [Auto Dark Mode](https://github.com/Armin2208/Windows-Auto-Night-Mode) for auto-switching my theme. Every time the theme change happens, the app just crashes. Soon after the switch, I can invoke the flyout while I can't open the setting panel. A hour (maybe sooner) after the switch, the app will be totally down.

**To Reproduce:**

1. Install and launch [Auto Dark Mode](https://github.com/Armin2208/Windows-Auto-Night-Mode)
2. Wait or invoke a theme change (taskbar color and app theme included)
3. The setting panel starts to crash
4. The whole app is down.

**Screenshots:**

(It will crash, so no screenshots 😥)

**OS Version:**
 - Windows 10 Version:  21H1 (19043.906)

**ModernFlyouts Version:**
 - Version: 0.9.0.1 (Latest for now)

**Additional context:**

**Comment by Samuel12321** [comment] 2021-04-10 20:55
This is a duplicate of #522 , please see #522 for further updates on this issue.

**Closed by Samuel12321** 2021-04-10 20:55 UTC
Labels: Bug
