### ISSUE TITLE
Bug: Tooltip in  is under menu when hovering item

### ISSUE THREAD

**Issue by HvadFanSkalJegHedde** [ModernFlyouts-Community/ModernFlyouts#540] opened 2021-04-04 22:16 UTC
**Describe the bug:**
When hovering an item in the sound control will show the tooltip under the menu.

**To Reproduce:**
1. Summon the menu by changing volume or song.
2. Hover over any item that has a tooltip, e.g. the three dots for more controls.
3. You'll see the "More Controls" tooltip is under the main menu.

**Screenshots:**
![Hover issue](https://user-images.githubusercontent.com/47789511/113522785-c60ed200-95a3-11eb-9807-d054773115a0.png)

**OS Version:**
 - Version: Microsoft Windows 10 Home

**ModernFlyouts Version:**
 - Version: v0.9.1.0

**Additional context:**
No additional context needed

**Comment by Samuel12321** [comment] 2021-04-04 23:04
duplicate of #377

**Closed by Samuel12321** 2021-04-04 23:04 UTC
Labels: Bug
