### ISSUE TITLE
Display new song playing

### ISSUE THREAD

**Issue by Crissomar** [ModernFlyouts-Community/ModernFlyouts#925] opened 2022-01-16 20:28 UTC
### Description of the new feature / enhancement

could be displayed every time the song changes 

### Scenario when this would be used?

So you can see if you want to skip it or be ready for the drop ♪.ıılıll|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|llılıı.♫

### Additional context

I don't know why I liked this feature in aimp xD

**Comment by Samuel12321** [comment] 2022-01-18 23:24
Duplicate of #78

**Closed** 2022-01-18 23:24 UTC
Labels: Enhancement
