### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by kepagu** [ModernFlyouts-Community/ModernFlyouts#351] opened 2021-01-10 18:37 UTC
Using trackpad gestures on laptop to change the volume does not bring up the modernflyout volume slider.

**To Reproduce:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/70054758/104132039-0e3e9f80-537b-11eb-9e88-9bbb1b1b2e58.png)
using gestures on trackpad to change volume brings up the standard windows volime slider.

![image](https://user-images.githubusercontent.com/70054758/104131949-50b3ac80-537a-11eb-8f7c-7ef22b644088.png)
"Enheter" (English translation: devices)

![image](https://user-images.githubusercontent.com/70054758/104131968-8062b480-537a-11eb-840f-32e001252ada.png)
"styreplate" (English translation: trackpad)

![image](https://user-images.githubusercontent.com/70054758/104132014-dcc5d400-537a-11eb-9f30-b06a44d91fc7.png)
swipe up and down with three fingers is configured to change the volume.

**OS Version:**
 - Windows 10 Version:  Windows 10 Home 20H2

**ModernFlyouts Version:**
 - Version:  0.8.5.0

**Additional context:**

**Comment by ShankarBUS** [comment] 2021-01-10 18:42
This is a duplicate of #4.
Please stay tuned with #4.
I'll close this now.

**Closed** 2021-01-10 18:43 UTC
Labels: Bug, Duplicate
