### ISSUE TITLE
Bug: Settings Window breaks after PC Restart (Run at start-up)

### ISSUE THREAD

**Issue by Davoleo** [ModernFlyouts-Community/ModernFlyouts#520] opened 2021-03-23 09:35 UTC
**Describe the bug:**
Settings window breaks after PC reboot, the background service is started correctly I guess, but the settings windows shows as completely black the first time you open and then completely transparent the second time you try opening it

As a workaround to fix this I've noticed that you can kill the process and start it manually again

**To Reproduce:**
1. Restart your computer with auto-start enabled
2. Try opening the settings window
3. Try opening it a second time
4. Kill any process related to Modern Flyouts from the task manager
5. Start the process again manually and successfully open the settings window

**Screenshots:**
_NYA: I'll add screenshots to this post the next time I experience this issue_

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: v0.9.1

**Additional context:**
As an additional note the first time I experienced this all my settings were untouched, the second time I had this issue the monitor placement of the flyout automatically changed to the main display instead of the one I set manually.

One more thing, the first time I experienced this bug the process was present in the `Processes` tab of the Task Manager and I was able to kill it from there the second time I couldn't find the process related to Modern Flyouts in that tab and I had to kill a related process in the `Details` tab

**Comment by Samuel12321** [comment] 2021-08-05 08:44
@Davoleo Is this still occurring on 0.9.3?

**Comment by Samuel12321** [comment] 2021-08-05 09:09
Duplicate of #437

**Closed by Samuel12321** 2021-08-05 09:09 UTC
Labels: Bug
