### ISSUE TITLE
Mica blur effect

### ISSUE THREAD

**Issue by AINER** [ModernFlyouts-Community/ModernFlyouts#1218] opened 2023-08-16 18:24 UTC
### Description of the new feature / enhancement

Add Mica blur effect for more consistency with Windows 11 design.

### Scenario when this would be used?

 Most relevant for Windows 11 so it's better to do it as an optional setting.

**Comment by manstheram** [comment] 2023-08-29 16:52
I'm going to start working on this using two Win32 api's - CreateRoundRectRgn & CombineRgn.

**Comment by Samuel12321** [comment] 2023-10-26 22:20
Closing as duplicate of #890
Planned for 0.11 as this will be much easier on winui 3, aiming to have the options of either adjustable transparency (as we currently have), Mica or acrylic.

**Closed by Samuel12321** 2023-10-26 22:20 UTC
Labels: Enhancement
