### ISSUE TITLE
interesting bug

### ISSUE THREAD

**Issue by mahdibhaiya** [ModernFlyouts-Community/ModernFlyouts#952] opened 2022-02-13 19:50 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro 21H2

### OS build

19044.1526

### Platform

x64

### Area(s) with issue?

Lock keys Flyout

### Steps to reproduce

When I drag the Lock Key flyout all the way to the top, part of it starts to disappear. When I do this again, more of it disappears. I can keep doing it until it no longer exists. Not a _serious_ bug, but a bug nevertheless.

### ✔️ Expected Behavior

I expected it to just snap to the top without fault.

### ❌ Actual Behavior

The bottom portion would disappear slightly every time I drag to the top until there was no more to disappear.

**Comment by Cyberdroid1** [comment] 2022-02-14 04:09
Duplicate of #894

**Closed by Cyberdroid1** 2022-02-14 04:09 UTC
Labels: Bug
