### ISSUE TITLE
New Windows 11 Flyouts appearing along with modernFlyouts

### ISSUE THREAD

**Issue by imjusthere2getsmethin** [ModernFlyouts-Community/ModernFlyouts#1102] opened 2022-09-21 10:52 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 22H2

### Steps to reproduce

Just simple changing volume or brightness make flyouts from both new windows11 new updated flyout along with modernFlyout.

### ✔️ Expected Behavior

ModernFlyouts should only be the one working not with the windows default.

### ❌ Actual Behavior

Both appearing at the same time.

**Comment by TheBrokenG0d** [comment] 2022-09-21 18:05
Duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/920 

Its been a bug since the insider builds.

**Comment by Samuel12321** [comment] 2022-10-02 02:22
Hi,
Thanks for reporting this. We are aware of the problem and plan to fix this in the next update 0.11.

Closing as duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/920

**Closed by Samuel12321** 2022-10-02 02:22 UTC
Labels: Bug
