### ISSUE TITLE
Error with Volume Sider.

### ISSUE THREAD

**Issue by stellar-4242** [ModernFlyouts-Community/ModernFlyouts#755] opened 2021-08-17 09:15 UTC
Not really a bug, just more of confused as how do I fix this.? 

Example : https://streamable.com/231q8l

Note : I use VoiceMeteer

Suggestion : Make an option where I'm able to select my own audio device?

**Comment by Cyberdroid1** [comment] 2021-08-17 18:18
Does the speaker tray icon in the taskbar show the volume changing when you change volume in the flyout?

**Comment by Samuel12321** [comment] 2022-01-08 09:09
duplicate of another issue, will be fixed in 0.11

**Closed by Samuel12321** 2022-01-08 09:09 UTC
