### ISSUE TITLE
Bug: Brightness slider maxes out at 99

### ISSUE THREAD

**Issue by kepagu** [ModernFlyouts-Community/ModernFlyouts#350] opened 2021-01-10 18:25 UTC
**Describe the bug:**
 The brightness slider maxes out at 99, will not reach 100.

**To Reproduce:**
 1. When increasing to full brightness, the slider does not reach the end, and it only goes up to 99. It does however go all the way down to 00. A suggestion is changing the lowest value to 1, or 0 instead of 00

**Screenshots:**

![image](https://user-images.githubusercontent.com/70054758/104131807-29101480-5379-11eb-9b7e-82cd50fd5b2b.png)

**OS Version:**
 - Windows 10 Version: Windows 10 Home 20H2

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Comment by Cyberdroid1** [comment] 2021-01-25 18:15
I would consider this a dupe of #301. 

@kepagu Please check out that issue and share your opinion there.

**Closed** 2021-02-17 05:51 UTC
Labels: Bug, Duplicate
