### ISSUE TITLE
Bug  top bar not hide automatically:

### ISSUE THREAD

**Issue by 123sachithra123** [ModernFlyouts-Community/ModernFlyouts#607] opened 2021-05-05 10:57 UTC
I used modern flyouts months but from yesterday after the windows update. when I volume/brightness increase/decrease it not hide it stay visible. I also reset it but not fix it. top bar visibility is set to auto-hide mode.

**Comment by Cyberdroid1** [comment] 2021-05-05 17:15
Duplicate of #563

**Closed by Cyberdroid1** 2021-05-05 17:15 UTC
Labels: Bug
