### ISSUE TITLE
Bug: ModernFlyouts appears when changing the language

### ISSUE THREAD

**Issue by Velrous** [ModernFlyouts-Community/ModernFlyouts#693] opened 2021-07-09 15:41 UTC
**Describe the bug:**
Changing the language with shift + ctrl brings up the ModernFlyouts panel. Tested on three computers and appears on all. I also noticed that if you hold down Shift and press ctrl, the language will change, and the panel will not appear. But if you do everything quickly or first press ctrl and then shift, the language will change and a panel will appear. Sometimes restarting the program / windows solves this problem.

**To Reproduce:**
Quickly change the language with a combination of shift + ctrl or hold ctrl and press shift.

**Screenshots:**
No.

**OS Version:**
Windows 10 Pro 21H1

**ModernFlyouts Version:**
0.9.3.0

**Comment by Cyberdroid1** [comment] 2021-07-09 17:31
Duplicate of #584. Please check pinned issues and also search for issues before opening a new one to prevent duplicates.

**Closed by Cyberdroid1** 2021-07-09 17:31 UTC
Labels: Bug
