### ISSUE TITLE
Bug: Layout Display Keeps Automatically Switching

### ISSUE THREAD

**Issue by TheCoderJT** [ModernFlyouts-Community/ModernFlyouts#929] opened 2022-01-23 21:20 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

General, Media Flyout

### Steps to reproduce

I don't know how to recreate it I pic my main display inside the layout and eventually it automatically switches to my second monitor it doesn't save.  

### ✔️ Expected Behavior

I am expecting when I select display 1 it should always stay on that display and not switch.

### ❌ Actual Behavior

I select my main display and after some random time it auto switches to my second display which i don't want.

**Comment by Samuel12321** [comment] 2022-03-27 01:36
Duplicate of #736

**Closed by Samuel12321** 2022-03-27 01:36 UTC
Labels: Bug
