### ISSUE TITLE
Bug: Flyout not appearing in front of fullscreen applications

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#339] opened 2021-01-03 19:49 UTC
**Describe the bug:**
When I am running a fullscreen application, the flyout does not appear. I am assuming it is stuck behind the fullscreen window, because the regular windows flyout still works fine when this one is disabled.

**To Reproduce:**
<!--
1. Open a fullscreen game (make sure it is not borderless, but _true_ fullscreen)
2. Try to adjust the volume. The volume adjusts but the flyout is not present.

**Screenshots:**
N/A

**OS Version:**
 - Windows 10 Version: 20H2 (OS Build 19042.685)

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Additional context:**
Specifically, I was using Rocket League on the Steam store when I had this issue.

**Comment by ShankarBUS** [comment] 2021-01-03 19:52
The title is misleading.

This issue is a duplicate and is under work.

We'll release the fix with v0.9.

**Comment by Tech-How** [comment] 2021-01-03 20:01
Whoops, meant to write *not

**Comment by Samuel12321** [comment] 2021-01-04 01:38
Closing as duplicate of #32 
Thanks for reporting this, see #32 for more on this issue.

**Closed by Samuel12321** 2021-01-04 01:38 UTC
