### ISSUE TITLE
0.9.3 New Chinese Translations and Improvements

### ISSUE THREAD

**Issue by Nevodev** [ModernFlyouts-Community/ModernFlyouts#747] opened 2021-08-14 14:04 UTC
I'm using 0.9.3.0.
I found some strings not translated to Chinese (zh-Hans), they are still English.

Layout -> 布局
Display -> 显示
Flyout placement -> 浮出控件位置
Placement mode -> 位置模式
Auto -> 自动
Manual -> 手动
Flyout alignment -> 浮出控件对齐
Horizontal alignment -> 水平对齐
Vertical alignment -> 垂直对齐
Flyout expand direction -> 浮出控件展开方向
Flyout content stacking direction -> 内容堆叠方向
Ascending -> 升序
Descending -> 降序

Fade animation -> 淡入/淡出动画

Use media's thumbnail as media control's background -> 使用媒体缩略图作为媒体控件背景

**Comment by Cyberdroid1** [comment] 2021-08-15 05:53
Thank you for your contribution, but it has been already fixed and will be released with next update.

Duplicate of #605

**Closed by Cyberdroid1** 2021-08-15 05:53 UTC
