### ISSUE TITLE
Blutooth devices

### ISSUE THREAD

**Issue by Hulmee** [ModernFlyouts-Community/ModernFlyouts#1121] opened 2022-10-13 23:40 UTC
### Description of the new feature / enhancement

A flyout to show what blutooth devices are conected and the device battery level, 
optionally a way to action a device to connect/disconect

### Scenario when this would be used?

when a device is connected/disconected

**Comment by Samuel12321** [comment] 2022-10-15 22:26
Duplicate of #903 
great minds think alike. It is planned for an upcoming release.

**Closed by Samuel12321** 2022-10-15 22:26 UTC
Labels: Enhancement
