### ISSUE TITLE
ModernFlyouts audio flyout issue

### ISSUE THREAD

**Issue by fedoraeli** [ModernFlyouts-Community/ModernFlyouts#1156] opened 2023-01-06 21:32 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Home

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Whenever I try to disable the audio flyout, the entire app freezes, then crashes. Even after restarting the application & the computer, the issue persists.

### ✔️ Expected Behavior

For the audio flyout to be disabled.

### ❌ Actual Behavior

The app crashing.

**Comment by prakharb5** [comment] 2023-01-14 10:02
Duplicate of #888

**Closed by prakharb5** 2023-01-14 10:02 UTC
Labels: Bug
