### ISSUE TITLE
Feature Request: Acrylic Blur

### ISSUE THREAD

**Issue by JosephM101** [ModernFlyouts-Community/ModernFlyouts#389] opened 2021-01-25 13:39 UTC
I know it's not really a must-have, but it is a nice-to-have. Just pure transparency doesn't look... great. I'd want everything behind the flyout to have a blur applied it; just thinking it might look better.

**Comment by Cyberdroid1** [comment] 2021-01-25 15:57
Dupe of #66. Please check out that issue and put your opinion there 😄

**Closed** 2021-01-25 15:58 UTC
Labels: Duplicate, Enhancement, UI/UX
