### ISSUE TITLE
Feature Request: Pinning to the desktop

### ISSUE THREAD

**Issue by OCakeO** [ModernFlyouts-Community/ModernFlyouts#731] opened 2021-08-04 00:48 UTC
Solution:
I want to suggest that you add the ability to attach a music player to the desktop, and already during the volume change on top of all windows.

Well, it is also possible to add scaling of the application.

I think this will be useful for those who want to decorate their 2,3,4 ... temporarily unused monitors.

Thank you for developing the project, I really liked it like many others.

Alternatives:
I didn't find any stable working alternatives

Additional context:
![i1](https://user-images.githubusercontent.com/48018220/128103860-6610ecf0-603a-4bcb-ae0f-5f9a3f16ff13.png)

P.S. Надеюсь я все правильно перевел :)

**Comment by Cyberdroid1** [comment] 2021-08-04 05:08
Duplicate of #368

**Closed by Cyberdroid1** 2021-08-04 05:08 UTC
Labels: Enhancement
