### ISSUE TITLE
alt+space (shortcut for changing language) displays ModernFlyouts

### ISSUE THREAD

**Issue by NicolasHing** [ModernFlyouts-Community/ModernFlyouts#1157] opened 2023-01-11 11:44 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

W10 22H2

### OS build

19045.2364

### Steps to reproduce

alt+space

### ✔️ Expected Behavior

no display

### ❌ Actual Behavior

display

**Comment by ElitePheonix2009** [comment] 2023-01-14 05:36
First of all, the shortcut id win + space and not alt + space. Second, I had also opened this same issue earlier. So it's a duplicate. See #1126

**Comment by prakharb5** [comment] 2023-01-14 10:00
Duplicate of #584

**Closed by prakharb5** 2023-01-14 10:00 UTC
Labels: Bug
