### ISSUE TITLE
Default media flyout appears underneath this one

### ISSUE THREAD

**Issue by T43DiamondGamer** [ModernFlyouts-Community/ModernFlyouts#1093] opened 2022-09-18 23:01 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22622.598

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Turn Volume up, down or off.

![image](https://user-images.githubusercontent.com/102071849/190931906-ea7d0027-a1aa-49c0-a75a-ebbf6bf23aa8.png)

### ✔️ Expected Behavior

Expecting default flyout to not be visible.

### ❌ Actual Behavior

Default flyout was visible.

**Comment by jaykillr** [comment] 2022-09-19 01:48
I really hope they fix this, it's very annoying

**Comment by PeterNjeim** [comment] 2022-09-20 18:22
This app hasn't been updated in over a year lol. There's only 1 active branch and it's making very slow progress. I doubt this will be updated for 22H2

**Comment by PeterNjeim** [comment] 2022-09-20 18:30
Also this is a duplicate of one of the pinned issues lol: https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/920. Please look through issues before opening duplicates. Close this

**Closed** 2022-10-02 02:36 UTC
Labels: Bug
