### ISSUE TITLE
Both Windowsflyouts and new Win 11 22H2 UI showing

### ISSUE THREAD

**Issue by Sanaan01** [ModernFlyouts-Community/ModernFlyouts#1113] opened 2022-10-03 15:30 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Just by trying to set the default to Modernflyouts

### ✔️ Expected Behavior

Only Modernflyouts to show up

### ❌ Actual Behavior

The new volume UI showing up and windowsflyout's both show even with the default selected on Win 11 22H2
![Screenshot 2022-10-03 182836](https://user-images.githubusercontent.com/81903566/193616703-883c1cf2-251c-4038-a91a-e429d571f414.png)

**Comment by Samuel12321** [comment] 2022-10-03 22:38
Duplicate of #920

**Closed** 2022-10-05 08:54 UTC
Labels: Bug
