### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by debido666** [ModernFlyouts-Community/ModernFlyouts#615] opened 2021-05-09 22:40 UTC
**Is your feature request related to a problem? Please describe:**
Before the 0.9.3.0 update, I could disable all modules except the Lock keys module. Just use that module for Caps Lock, Num lock, Insert, etc alone. Leaving the windows default for everything else (Volume). Now, with 0.9.3.0 installed, Brightness and Airplane mode modules can still be disabled, but when I disable Audio module, ModernFlyouts shuts down completely. In other words, I only need this for Lock keys module, nothing else. Can I disable the Audio module too? 
Thank you.

**Comment by Samuel12321** [comment] 2021-05-09 23:31
Duplicate of #592 
This is a bug which will be fixed in the next update

**Closed by Samuel12321** 2021-05-09 23:31 UTC
Labels: Enhancement
