### ISSUE TITLE
Display When I Switch My Input software

### ISSUE THREAD

**Issue by EvilZabanya** [ModernFlyouts-Community/ModernFlyouts#1112] opened 2022-10-03 06:56 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H1

### OS build

19043.2075

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Press Win+Space To Switch My Input software
and then the ModernFlyouts shows it's window.

### ❌ Actual Behavior

the ModernFlyouts shows it's window

**Comment by Cyberdroid1** [comment] 2022-10-06 02:24
duplicate of another issue, this is a known bug and will be fixed in the 0.11 release

**Closed by Cyberdroid1** 2022-10-06 02:24 UTC
Labels: Bug
