### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by johannes-langer** [ModernFlyouts-Community/ModernFlyouts#420] opened 2021-02-01 10:17 UTC
**Is your feature request related to a problem? Please describe:**
When I use a Surface Dial for Volume-/Media-Control, it will show the default flyouts instead of the new ones.
**Describe the solution you'd like:**
Show the Modern Flyouts when using a Surface Dial for Volume-/Media-Control

**Comment by Cyberdroid1** [comment] 2021-02-01 11:00
I think this issue is related to #4.

@johannes-langer Can you check that issue and tell if that issue suffices your needs?

**Comment by Samuel12321** [comment] 2021-02-12 21:39
closing as a duplicate of #4

**Closed by Samuel12321** 2021-02-12 21:39 UTC
