### ISSUE TITLE
frezzing

### ISSUE THREAD

**Issue by AdamGaming545** [ModernFlyouts-Community/ModernFlyouts#1106] opened 2022-09-25 22:11 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### OS build

22000.856

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

don't have screenshot doe just believe it  

### ✔️ Expected Behavior

It is suppose to just run normal and not freeze 

### ❌ Actual Behavior

instead it just freezes and don't see volume bar and when I see volume bar it just stays there and does nothing 

### Other Software

nothing

### Additional Context

no

**Comment by Cyberdroid1** [comment] 2022-10-06 02:26
Can you share a recording?

**Comment by austinjklim** [comment] 2022-10-22 08:26
> Can you share a recording?

A separate user here. It freezes completely, showing the pop-up window, and not disappearing, blocking part of my desktop and other apps. (I was on chrome and it was blocking it, not sure about other programs). 

It happens quite frequently since I just reformatted to Win 11 22H2 Build 22621.675. The only way to fix this is by terminating the process and restarting it manually. There's no specific trigger to this other than increase/decrease volume normally as I go about my usual browsing. 

It could also potentially be one of the tweaks from ThisIsWin11. 
![Screenshot 2022-10-22 162606](https://user-images.githubusercontent.com/16682922/197329099-e3394818-52e3-44a6-b3b5-2b81458df163.png)

**Comment by Cyberdroid1** [comment] 2022-10-27 17:49
Duplicate of #464

**Comment by AdamGaming545** [comment] 2023-01-07 22:07
its fine now

**Closed** 2023-01-16 17:44 UTC
Labels: Bug, Needs More Info
