### ISSUE TITLE
Bug: tooltip is behind

### ISSUE THREAD

**Issue by Nomyfan** [ModernFlyouts-Community/ModernFlyouts#404] opened 2021-01-27 13:53 UTC
**Describe the bug:**
The button tooltips is behind, which makes them invisible partially. See my screenshot below.

**To Reproduce:**
Always in my machine.

**Screenshots:**
<img width="344" alt="snipaste_20210127_214106" src="https://user-images.githubusercontent.com/19922814/106000258-96e26d00-60e9-11eb-9aac-bf209cfb537a.png">

**OS Version:**
 Windows 10 2004
OS build 19035.1

**ModernFlyouts Version:**
0.9.0.0

**Additional context:**
None

**Comment by Cyberdroid1** [comment] 2021-01-27 14:10
Error 404. Unique issue not found. 

Dupe of #377. Please check out that issue.

**Closed** 2021-01-27 14:11 UTC
Labels: Duplicate, Known issue, UI/UX
