### ISSUE TITLE
Bug: Hi guys, your application don't see Spotify aplication, at all, when i press stop/play button at my keyboard it's don't notify me, please fix it 

### ISSUE THREAD

**Issue by mellotrixmusuic** [ModernFlyouts-Community/ModernFlyouts#883] opened 2021-11-28 11:21 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-11-28 12:15
Hi, edit your issue and fill in the issue template properly. Thanks.

**Comment by eProject** [comment] 2021-11-30 10:39
Is this feature even present on the Win default flyout? 
not 100% sure
default flyout only pops when I change volume/mute (not with media keys - play/pause, next/previous) same with ModernFlyouts.

This is a feature request duplicate (# insert number) flyout pop-up when music/video changes or when user uses media keys.

**Comment by Cyberdroid1** [comment] 2021-11-30 11:18
@eProject it is a windows default behaviour, that the media flyout appears on press play/pause, next, previous buttons

**Comment by eProject** [comment] 2021-11-30 11:26
hmm strange... can't reproduce

**Comment by Samuel12321** [comment] 2022-03-27 00:52
Duplicate of #532

**Closed by Samuel12321** 2022-03-27 00:52 UTC
Labels: Bug, Needs More Info
