### ISSUE TITLE
Microphone button flyout

### ISSUE THREAD

**Issue by adazlord** [ModernFlyouts-Community/ModernFlyouts#948] opened 2022-02-11 08:06 UTC
### Description of the new feature / enhancement

Hi,
Is it possible to include a microphone button flyout as well?
I have an ASUS ROG, so I don't know if the microphone button is special or standard, but I hope it is possible to effectuate this.
Thank you!
Adam

### Scenario when this would be used?

When I'm on a video meeting, I don't always know if the microphone is on or off.

**Comment by Samuel12321** [comment] 2022-02-13 02:14
Duplicate of #841

**Closed by Samuel12321** 2022-02-13 02:14 UTC
Labels: Enhancement
