### ISSUE TITLE
Bug: ModernFlyouts does not remember your chosen display

### ISSUE THREAD

**Issue by robertfwallis** [ModernFlyouts-Community/ModernFlyouts#621] opened 2021-05-16 13:43 UTC
**Describe the bug:**
Sometimes the flyouts do not default to the correct monitor set by the user. Many times I've had to manually switch back to my chosen monitor as it has randomly moved itself to my secondary monitor.

**To Reproduce:**
1. Restart your PC
2. Power on your monitors in a random order - this may not be important, not sure
3. Watch as ModernFlyouts defaults to a different monitor.

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: v0.9.3

**Comment by ErenAKGUN2007** [comment] 2021-05-16 13:47
Duplicate of #604

**Comment by Cyberdroid1** [comment] 2021-05-17 04:35
Thanks @ErenAKGUN2007 !

**Closed** 2021-05-17 04:35 UTC
Labels: Bug, Duplicate
