### ISSUE TITLE
Bug: "win+space" triggers the ModernFlyouts

### ISSUE THREAD

**Issue by ranhengzhangr** [ModernFlyouts-Community/ModernFlyouts#914] opened 2022-01-04 09:18 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10 20H2

### OS build

19044.1415

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout

### Steps to reproduce

Click "win+space"

### ✔️ Expected Behavior

Nothing happend

### ❌ Actual Behavior

The ModernFlyouts appear

**Comment by Samuel12321** [comment] 2022-01-04 09:21
duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/584 This will be fixed in the next update due later this month.

**Closed by Samuel12321** 2022-01-04 09:21 UTC
Labels: Bug
