### ISSUE TITLE
Bug: Music interface not available until restarted

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#338] opened 2021-01-03 15:21 UTC
**Describe the bug:**
The Music UI in the flyout isn't available until Modern Flyouts is restarted when music is already playing.

**To Reproduce:**
1. Have Modern Flyouts running in the background.
2. Open a music app and play music.
3. Adjust the volume. You will see the issue: The Music UI isn't there; just the volume.
4. Now, keep the music playing, and restart Modern Flyouts. _Now_ it works.

**OS Version:**
 - Windows 10 Version: 20H2 (OS Build 19042.685)

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Additional context:**
This issue has been occurring for quite a while, please have a look.

**Comment by ShankarBUS** [comment] 2021-01-03 15:22
This is a duplicate of #29.

We are working on this.

We hope to implement and bundle the fix with the next release.

**Closed** 2021-01-03 17:24 UTC
Labels: Bug, Duplicate
