### ISSUE TITLE
Bug: Can't Pause/Skip music on Spotify.

### ISSUE THREAD

**Issue by a7ce** [ModernFlyouts-Community/ModernFlyouts#892] opened 2021-12-14 07:40 UTC
I was trying to pause a song playing on Spotify, but It didn't seem to be pausing, or not doing anything at all.

Open the Popup,
Try to pause the song.
And you'll find that the song isn't pausing/skipping at all. (at least to me)

**Comment by Cyberdroid1** [comment] 2021-12-14 11:04
Can you share a recording for the same? Also, state your windows version and app version.

**Comment by szric98** [comment] 2021-12-15 09:54
I'm having the same issue. Skip, pause and stop buttons are disabled, only shuffle and repeat work.
If I open the app ***when Spotify is already open***, it works though.

Steps to reproduce:
1) Make sure Spotify is not, but the app is open in the background
2) Open Spotify
3) Open the Popup

**OS Information**: Windows 10 Home 21H2 build: 19044.1348
**App version**: 0.9.3.0
**Spotify version**: Spotify for Windows 1.1.74.631.g0b24d9ad

**Comment by Cyberdroid1** [comment] 2021-12-15 10:40
Ok thanks for clarifying.

Duplicate of #446

**Closed** 2021-12-15 10:40 UTC
Labels: Bug
