### ISSUE TITLE
After Windows update, both Windows and ModernFlyouts appear when adjusting volume, caps/num/scroll lock, or insert

### ISSUE THREAD

**Issue by Paetrig** [ModernFlyouts-Community/ModernFlyouts#1125] opened 2022-10-20 00:56 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.675

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout, Lock keys Flyout

### Steps to reproduce

1. Windows 11 22H2.
2. OS Build 22621.675.
3. Adjust volume, or toggle Caps/Num/Scroll locks, or Insert.
4. Both the Windows 11 and ModernFlyouts flyouts appear

### ✔️ Expected Behavior

With the Default Flyout set to ModernFlyouts, only the ModerFlyouts flyout should appear when adjusting volume, or toggling Caps/Num/Scroll locks, or Insert.

### ❌ Actual Behavior

Both the Windows 11 and ModernFlyouts flyouts appear when adjusting volume, or toggling Caps/Num/Scroll locks, or Insert.

### Other Software

Cider music player
Chrome (YouTube)
Edge (YouTube)
Edge (music.apple.com)

**Comment by Samuel12321** [comment] 2022-10-20 09:25
Duplicate of #920

**Closed by Samuel12321** 2022-10-20 09:25 UTC
Labels: Bug
