### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FlyingDandeagle** [ModernFlyouts-Community/ModernFlyouts#1015] opened 2022-05-16 11:11 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.1 Windows Feature Experience Pack 1000.22632.1000.0

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

当我想禁用ModernFlyouts的音频控制弹窗时，ModernFlyouts会闪退。只有禁用音频控制弹窗时会闪退，其他正常。

**English:**

When I want to disable ModernFlyouts' audio flyout, ModernFlyouts crashes.Only when the audio control pop-up window is disabled, it will crash, otherwise it will be normal.

### ✔️ Expected Behavior

disable ModernFlyouts' audio flyout

### ❌ Actual Behavior

ModernFlyouts crashes.

### Additional Context

nothing

**Comment by Cyberdroid1** [comment] 2022-05-16 15:36
Duplicate of #888

**Closed by Cyberdroid1** 2022-05-16 15:36 UTC
Labels: Bug
