### ISSUE TITLE
pin to screen

### ISSUE THREAD

**Issue by brulaap21** [ModernFlyouts-Community/ModernFlyouts#1144] opened 2022-12-03 14:08 UTC
I just had a question, i want to have the flyout pinned to my screen at all times. Is there already a way to do this, if so where can i find it.

**Comment by prakharb5** [comment] 2023-01-17 02:03
This feature will be added in a future update, but for now, you can set the timeout time to 999999999 seconds

Duplicate of #368

**Closed by prakharb5** 2023-01-17 02:03 UTC
