### ISSUE TITLE
Can't disable audio flyout

### ISSUE THREAD

**Issue by vdt2210** [ModernFlyouts-Community/ModernFlyouts#1027] opened 2022-06-08 04:27 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.1

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

1. Open app
2. Go to Audio
3. Disable Audio Flyout

### ✔️ Expected Behavior

Disable Audio Flyout and save option

### ❌ Actual Behavior

App not responding, crash and not save

**Comment by arnavbhate** [comment] 2022-06-15 13:41
Duplicate of #888

**Comment by Samuel12321** [comment] 2022-06-19 00:55
Duplicate of #592

**Closed by Samuel12321** 2022-06-19 00:55 UTC
Labels: Bug
