### ISSUE TITLE
Make a widget dont disappear automaticly

### ISSUE THREAD

**Issue by irunislaw** [ModernFlyouts-Community/ModernFlyouts#1000] opened 2022-04-20 17:22 UTC
### Description of the new feature / enhancement

Customization to delete auto disappearing of widget

### Scenario when this would be used?

when i want to have this open for forever

**Comment by Cyberdroid1** [comment] 2022-04-21 03:44
Currently, you can change the timeout in settings to be 99999999 seconds. This way, it won't hide automatically.

**Comment by Samuel12321** [comment] 2022-04-25 02:34
Congratulations on opening our 1000th issue 
Unfortunately i will have to unceremoniously close it as a Duplicate of #368

**Closed by Samuel12321** 2022-04-25 02:34 UTC
Labels: Enhancement
