### ISSUE TITLE
Bug: 关闭“启用音频浮出控件”闪退

### ISSUE THREAD

**Issue by ZSXB2468** [ModernFlyouts-Community/ModernFlyouts#993] opened 2022-04-07 17:52 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows11 22H2

### OS build

build 22593.1 ni_release

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

关闭“启用音频浮出控件”开关就会卡住然后闪退。

### ✔️ Expected Behavior

可以正常关闭“启用音频浮出控件”

### ❌ Actual Behavior

闪退

**Comment by Samuel12321** [comment] 2022-04-07 23:26
Duplicate of #888

**Closed by Samuel12321** 2022-04-07 23:26 UTC
Labels: Bug
