### ISSUE TITLE
Feature Request: Add transparency to the flyouts

### ISSUE THREAD

**Issue by Module32** [ModernFlyouts-Community/ModernFlyouts#654] opened 2021-06-10 00:14 UTC
I really like the ModernFlyouts and their aesthetic, but I think that they can look even better with Windows' transparency features.

I think they would fit in with Windows even better if it was possible to give them a slight tint based on the transparency of the taskbar (this would work really well for light mode).
For example, if your wallpaper is blue and transparency is enabled in your Windows settings, then your taskbar takes on a slight blue tint. If the flyouts could also do this, then I think it would be really nice.

**Comment by Cyberdroid1** [comment] 2021-06-10 05:14
Transparency already exists in Settings (Personalisation).

What you are requesting is tinting based on accent color.
Sounds pretty interesting to me.

@ShankarBUS any thoughts? Planning to do this?

**Comment by ShankarBUS** [comment] 2021-06-11 14:10
Too much work imo. I will see what I can do. Good idea tho.

**Comment by Samuel12321** [comment] 2021-08-03 08:43
Duplicate of #67

**Closed by Samuel12321** 2021-08-03 08:43 UTC
Labels: Enhancement, UI/UX
