### ISSUE TITLE
Crash: Run at Start-Up

### ISSUE THREAD

**Issue by noubz** [ModernFlyouts-Community/ModernFlyouts#489] opened 2021-03-08 09:18 UTC
Since the newest update of Modern Flyouts, everytime I start the computer I get an error (Image). I have already reset the app, reinstalled it and but it does not work on Start-Up. Now i am more or less overwhelmed.

Error: Application could not start correctly. Press "OK" to close the Application.

![Screenshot_2](https://user-images.githubusercontent.com/64863565/110300634-5f73b400-7ff7-11eb-964a-10e7023bb9ce.png)

**Comment by ADeltaX** [comment] 2021-03-08 12:23
Duplicate of #384

**Closed by ADeltaX** 2021-03-08 12:23 UTC
