### ISSUE TITLE
Bug: timeline doesn't work

### ISSUE THREAD

**Issue by XxNatsuENDxX** [ModernFlyouts-Community/ModernFlyouts#666] opened 2021-06-16 01:39 UTC
**Describe the bug:**
 - The timeline bar doesn't work with any software, dont las de time progress of the song.

**To Reproduce:**
- It's visible at simple view.

**Screenshots:**
![image](https://user-images.githubusercontent.com/54340170/122144498-9e4cad80-ce21-11eb-98d4-60e5ef4ec8f6.png)

**OS Version:**
 - Windows 10  Pro Insider Preview - Build 21390

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-06-16 12:30
This is not a bug of our app, instead it is a limitation of the media app. 

Request the app's developer to add GSMTC API support to the app. We have [a document](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md) linked in the readme which addresses this.

Closing this as not an issue.

**Closed by Cyberdroid1** 2021-06-16 12:30 UTC
Labels: Bug
