### ISSUE TITLE
Feature Request: Don't show timeline info when app does not support it

### ISSUE THREAD

**Issue by Poopooracoocoo** [ModernFlyouts-Community/ModernFlyouts#412] opened 2021-01-29 10:54 UTC
**Is your feature request related to a problem? Please describe:**

I often see empty timeline info and it's useless and sad :(

**Describe the solution you'd like:**

Don't show it.

**Describe alternatives you've considered:**

**Additional context:**

p.s. i'm still sad about you stopping development :( will miss it a lot<3

**Comment by Cyberdroid1** [comment] 2021-01-29 13:47
Dupe of #392. Please continue with that issue. It must not have appeared in the search results, since the name isn't exactly great 😄

**Closed** 2021-01-29 13:48 UTC
Labels: Duplicate, Enhancement, UI/UX
