### ISSUE TITLE
Bug: Doesn't show Spotify Thumbnail/Controls etc.

### ISSUE THREAD

**Issue by hristokaragyozov** [ModernFlyouts-Community/ModernFlyouts#665] opened 2021-06-15 20:00 UTC
**Describe the bug**:

When I am using YouTube or any other source for music/moves etc. there's no issues and I see the thumbnail and all the controls, but once I open Spotify App / Spotify Desktop Version (either of these) and try to volume up/down it won't even show anything other than the volume bar, as if Spotify isn't opened at all. 

**OS Version**: Windows 10 Pro (64 bit) 21H1 

**OS Build**: 19043.1052 (current latest)

**ModernFlyouts Version**: 0.9.3.0

**Comment by AnshulJ999** [comment] 2021-06-19 15:36
I second this. Amazing app, but it's not working for Spotify desktop app. The pause/next/previous/stop controls are greyed out, only the volume control, playback seeker, shuffle, and repeat options work. 
I'm on Windows 10 Home 64 bit, and using the latest version of spotify desktop app.

**Comment by ShankarBUS** [comment] 2021-06-19 15:51
It could be one of the two cases:
1. The same old GSMTC bug that we have been facing since Windows 10 2004.
2. I heard somewhere that, Spotify is turning into a full PWA. The existing one has support for the whole set of SMTC APIs. But since the new one is a pure PWA, it might not have the support.

But since you said YouTube and others works well, it could be case 2

So, in short, it is not really our mistake. Spotify has been messing with our app a lot, like logo in thumbnail, slow updating of timeline progress and several other issues.

As for @AnshulJ999,

It is case 1

**Comment by Samuel12321** [comment] 2022-03-27 00:47
Duplicate of #532

**Closed by Samuel12321** 2022-03-27 00:47 UTC
Labels: Bug, Media
