### ISSUE TITLE
Bug: Volume Rocker is stuck on screen after using.

### ISSUE THREAD

**Issue by Megamaster1900** [ModernFlyouts-Community/ModernFlyouts#622] opened 2021-05-16 17:23 UTC
**Describe the bug:**

I realised recently that when I use the volume controls on my computer, either through my keyboard or mouse macro (tried both because it could be my keyboard's fault idk) the flyout appears on my screen but then it just doesn't go away, no matter what I do it's just there until I click the X mark. It happens everytime, doesn't matter what apps I have open, If anything's fullscreen or if i'm in a game, it's always there. (This also happens when I press caps/numlock).

**To Reproduce:**

I don't really know it's just always happening

**Screenshots:**

**OS Version:**
 - Windows 10 Pro Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

Had to cut the video in 2 so they would be less than 10MB

https://user-images.githubusercontent.com/84285150/118406371-b7700c00-b673-11eb-86df-b9227aeeaa7e.mp4

https://user-images.githubusercontent.com/84285150/118406386-c5259180-b673-11eb-9cb9-cf08aa8d383e.mp4

**Comment by juanchohq** [comment] 2021-05-17 20:08
I am also having this issue.

**Comment by Cyberdroid1** [comment] 2021-05-18 03:55
Duplicate of #464.

**Closed by Cyberdroid1** 2021-05-18 03:55 UTC
Labels: Bug
