### ISSUE TITLE
interface Audio

### ISSUE THREAD

**Issue by X2KROT2X** [ModernFlyouts-Community/ModernFlyouts#1052] opened 2022-07-18 09:00 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 20H2

### OS build

last build

### Platform

x64

### Area(s) with issue?

General, Audio Flyout

### Steps to reproduce

when you press shift or spacebar alt + shift, a strip of sound pops up that is annoying

### ✔️ Expected Behavior

nothing happens when you combine shift+ alt or shift or space

### ❌ Actual Behavior

a sound bar pops up a combination of shift + alt or shift or space

**Comment by Cyberdroid1** [comment] 2022-08-26 00:59
What sound bar are you talking about? Can you attach a screenshot?

**Comment by X2KROT2X** [comment] 2022-08-26 16:28
[image: image.png]

пт, 26 авг. 2022 г. в 03:59, Prakhar B ***@***.***>:

**Comment by Cyberdroid1** [comment] 2022-08-27 04:02
@X2KROT2X you will need to use the github website to send an image. Sending image via email does not work.

Reply on the website here : https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1052

**Comment by X2KROT2X** [comment] 2022-08-27 06:44
![unnamed](https://user-images.githubusercontent.com/80601139/187018526-bfde92aa-bc75-4c3b-afd1-c8c375492c90.png)

**Comment by Cyberdroid1** [comment] 2022-08-27 10:20
Duplicate of #584

**Closed by Cyberdroid1** 2022-08-27 10:20 UTC
Labels: Bug
