### ISSUE TITLE
Hovering Mouse for Information Pop-Up but in a Bad Placement

### ISSUE THREAD

**Issue by primus0123** [ModernFlyouts-Community/ModernFlyouts#1009] opened 2022-05-08 21:30 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Home 21H2

### OS build

19044.1682

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1.)Take any actions for previewing the application's interface.(voluming up/down volume of brightness...etc)

2.)When the interface shows up, hover your mouse pointer to any button and dont click, just wait to mini information pop-up window to show up.

3.)You probably see that the information pop-up window is just appear under the interface windows. 

I think this is not critical but visualy disturbed me I this it shoud not work in this way as planned I guess.
This situating works for nearly all of the buttons as I tried even after resetting the application.
![InkedFlyout bug_LI](https://user-images.githubusercontent.com/24403947/167316406-0dfe1340-7f40-4819-83f6-b14dc7866708.jpg)

### ✔️ Expected Behavior

Information pop-up window to be apper over the application's interface or just not totaly apperaring without editing windows settings to disabling the pop-up function
![bug fix foto](https://user-images.githubusercontent.com/24403947/167316516-229ecc5f-7e20-4cde-b095-899718b1ce2f.jpg)
.

### ❌ Actual Behavior

The information pop-up windows appears under the interface and it is hard to identify what is writing and creates unfavorable visual.

### Additional Context

Good luck!

**Comment by Samuel12321** [comment] 2022-05-10 01:57
Hi, thanks for reporting this.
Its a known bug which will be fixed in the next release.
Duplicate of #377

**Closed by Samuel12321** 2022-05-10 01:57 UTC
Labels: Bug
