### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by alient12** [ModernFlyouts-Community/ModernFlyouts#761] opened 2021-08-19 21:38 UTC
Some music players like Spotify do not have this feature, to have a small window media player and pin at the top of every other app.
I appreciated if you add this feature to lock the app and not disappear by time.

**Comment by Cyberdroid1** [comment] 2021-08-20 06:04
Duplicate of #368

**Closed by Cyberdroid1** 2021-08-20 06:04 UTC
Labels: Enhancement
