### ISSUE TITLE
Feature Request: I Would highly recommend u guys to make this app compatible with WebNowPlaying Companion, so that we can see the song progress (for people who use YT music) any ways this app is dope 

### ISSUE THREAD

**Issue by DoomSlayer1095** [ModernFlyouts-Community/ModernFlyouts#712] opened 2021-07-22 10:16 UTC
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-07-22 14:56
Duplicate of #711.

**Closed by Cyberdroid1** 2021-07-22 14:56 UTC
Labels: Enhancement
