### ISSUE TITLE
No autostart at pc startup

### ISSUE THREAD

**Issue by Hrshl7** [ModernFlyouts-Community/ModernFlyouts#1244] opened 2023-11-01 10:20 UTC
### ModernFlyouts Version

0.10.0.0

### Windows version

Windows 11 Family 22H2

### OS build

22621.2428

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Turn on the laptop.

### ✔️ Expected Behavior

Autostart of the application with the flyout of the application appearing when changing volume/brightness.

### ❌ Actual Behavior

No autostart. The W11 flyout appear when changing volume/brightness.
Need to manually open the app for it to start.

### Additional Context

The app is allowed to autostart in the task manager.
Need to open the app twice for it to appear.

**Comment by manstheram** [comment] 2023-12-01 17:27
This is caused by the host part of the app, but I have no idea why it's screwing up.

**Comment by manstheram** [comment] 2023-12-01 17:29
I've already made a workaround myself by forcing the start up task to not launch the host but just launch the main app by editing the build settings, but doing that means you have to compile it afterwards. You could try creating a shortcut to the app and placing that into your Startup folder.

**Comment by AbbieDoobie** [comment] 2023-12-01 18:10
Seems to work for now. Guide for anyone curious:

1. Run (Win+R) "shell:startup"
2. Run "shell:appsfolder"
3. Drag-n-drop ModernFlyouts from the appsfolder to startup. It'll make a shortcut.

**Comment by prakharb5** [comment] 2024-07-22 19:29
Duplicate of #437

**Closed by prakharb5** 2024-07-22 19:29 UTC
Labels: Bug
