### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by bombsnuccer** [ModernFlyouts-Community/ModernFlyouts#649] opened 2021-06-04 21:57 UTC
When switching layouts, a window pops up

1.press 'alt + shift'
2.appears

** OS Version: **

Windows 10 Version: Windows 10 20H2
** ModernFlyouts Version: **

Version: v0.9.3
sorry i am translating via google translator

**Comment by Cyberdroid1** [comment] 2021-06-05 15:35
Duplicate of #584

**Closed by Cyberdroid1** 2021-06-05 15:35 UTC
Labels: Bug
