### ISSUE TITLE
Bug: Showing the audio and brightness box with the default Windows 11 Volume increaser and Brightness increaser

### ISSUE THREAD

**Issue by harsh160101065** [ModernFlyouts-Community/ModernFlyouts#1300] opened 2024-05-07 14:05 UTC
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/80818574/4e438fea-4b41-402a-8271-0b62c2e3bfc5)

The given image shows the issue

**Comment by harsh160101065** [comment] 2024-05-07 15:08
Till then we can use HideVolumeOSD which is an open source and free program that disables the Volume Meto flyout In Windows 8, 8.1, 10  and even disables the Windows 11 Volume Flyout

**Comment by manstheram** [comment] 2024-05-07 16:16
https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4

**Comment by prakharb5** [comment] 2024-07-04 12:38
dupe of #920

**Closed by prakharb5** 2024-07-04 12:38 UTC
