### ISSUE TITLE
NOTICE: Redesigned volume flyout for W11

### ISSUE THREAD

**Issue by Rexogamer** [ModernFlyouts-Community/ModernFlyouts#919] opened 2022-01-12 18:14 UTC
Heya! Thanks for the amazing work on this tool.

As of writing this, in [the latest W11 Insider Dev build](https://blogs.windows.com/windows-insider/2022/01/12/announcing-windows-11-insider-preview-build-22533/) there's a brand new, Fluent flyout:

![image](https://user-images.githubusercontent.com/42586271/149198528-0b68706f-6790-49ef-baed-6d2a47240003.png)

(picture credit: [this](https://blogs.windows.com/wp-content/uploads/prod/sites/44/2022/01/hw-vol-flyout.png) in the announcement article)

I wanted to mention this in case it could influence anything here - while this new flyout does indeed follow Fluent guidelines, it annoyingly lacks a volume number. I suspect this will be fixed in future builds, but yeah. Have a great day!

**Comment by Rexogamer** [comment] 2022-01-12 21:20
Upon further testing, it seems MF doesn't replace this new flyout. I've opened #920 to track this bug.

**Comment by Samuel12321** [comment] 2022-01-12 22:02
Hi, thanks for letting us know. I found out this morning, and while we knew it was coming I didn't expect it so soon.
We are working as fast as we can with 0.11 which we feel will be superior to Microsoft's new flyouts.

**Comment by Samuel12321** [comment] 2022-05-19 09:43
Duplicate of #920

**Closed by Samuel12321** 2022-05-19 09:43 UTC
