### ISSUE TITLE
Display Modern Flyout When Skipping Songs

### ISSUE THREAD

**Issue by Reach420** [ModernFlyouts-Community/ModernFlyouts#1023] opened 2022-05-29 13:48 UTC
### Description of the new feature / enhancement

when we skip a song it will display modern flyout so that we can see what's the next song playing but of course when we purposely skip a song(Example: for me i would swipe with 3 fingers to skip songs) and not when it automatically skip. 

### Scenario when this would be used?

when we want to see what song we skipped to

**Comment by Cyberdroid1** [comment] 2022-08-19 17:07
Duplicate of #78

**Closed by Cyberdroid1** 2022-08-19 17:07 UTC
Labels: Enhancement
