### ISSUE TITLE
run at start-up not working

### ISSUE THREAD

**Issue by N0tAvai1able** [ModernFlyouts-Community/ModernFlyouts#1301] opened 2024-05-07 22:14 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10 22h2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

![Screenshot (000151)](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/99380313/00a07bf6-2c78-4a1e-8f70-f98c57704898)
even after turning this on, app is not starting at start up

### ✔️ Expected Behavior

it should start at log on/startup

### ❌ Actual Behavior

not starting up

**Comment by thedtvn** [comment] 2024-05-16 10:52
same  bug

**Comment by thedtvn** [comment] 2024-05-16 11:24
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/80153297/774ea0bd-3b6a-46a4-92ce-a15e43967191)
bug windows PermissionError: [WinError 5] Access is denied 
likely windows block run sub app

**Comment by wefalltomorrow** [comment] 2024-05-29 13:09
Can confirm unfortunately .

**Comment by prakharb5** [comment] 2024-07-22 19:27
Duplicate of #437

**Closed by prakharb5** 2024-07-22 19:27 UTC
Labels: Bug
