### ISSUE TITLE
Bug: Media Playback Thumbnail and Info Not Shown

### ISSUE THREAD

**Issue by TheDarkKnight2168** [ModernFlyouts-Community/ModernFlyouts#709] opened 2021-07-21 05:29 UTC
Its a bug/glitch which happens if the media is played at first - thats the only media which gets showed as the thumbnail. After that  the next app/media playback gets no more showed on the flyout even if the media is playing

**To Reproduce:**

1. Play any media after first install
2. then the 2nd media thumbnail and info is no more displayed
3. Even after restart - it does not appear anymore
4. For it to reappear I need to restart the app again and again
-->

**Screenshots:**
![image](https://user-images.githubusercontent.com/75940259/126435674-6e712617-98ea-46f1-8364-b62499e0254a.png)

**OS Version:**
 - Windows 10 Version:  Windows 10 21H1 - 32 bit

**ModernFlyouts Version:**
 - Version: v0.9.3.0]

**Comment by Cyberdroid1** [comment] 2021-07-21 06:24
Duplicate of #610.

**Closed by Cyberdroid1** 2021-07-21 06:24 UTC
Labels: Bug
