### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by romajmg** [ModernFlyouts-Community/ModernFlyouts#601] opened 2021-05-02 22:24 UTC
**Describe the bug:**
Volume Panel is opened when switching input language (Alt+Shift)

**To Reproduce:**
Everytime when I switching input language volume panel appears

**OS Version:**
Windows 10 20H2

**ModernFlyouts Version:**
 - Version: v0.9.3

**Comment by Samuel12321** [comment] 2021-05-03 08:54
Duplicate of #584

**Closed by Samuel12321** 2021-05-03 08:54 UTC
Labels: Bug
