### ISSUE TITLE
Bug: Song skipping, media control and startup  

### ISSUE THREAD

**Issue by Prakrit-170807** [ModernFlyouts-Community/ModernFlyouts#325] opened 2020-12-25 18:17 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

Hey i have been using your software for almost two month now and i have been face a lot of difficulties 
1.Some time as i am listening to song and i want to skip the song it works like it does skips the song but it doesn't shows up in the ui it doesn't resumes until i restart the app 
2.This happens often with me that when i am using this the UI doesn't pops up or the flyout and my media keys stop working until i completely restart my computer and it is very tedious task to get it going. This cannot be done for ever and i even have to save the work i have been doing and then restart it.
3.The last thing is that i every time after a restart have to manually restart it because when it start with windows it doesn't start properly and it is very buggy   

these problems were faces by me on both on my desktop and my laptop but i was not able to figure what caused it  

Also on both my PC and my laptop i was rocking the windows latest builds 20H2 

these problems were on the latest version on the app 

thanx !
merry christmas🎄🎄

**Comment by ShankarBUS** [comment] 2020-12-25 18:32
Thanks for taking your time to find this repository and filing this bug report!

What you experience is essentially a bug in the OS and not in ModernFlyouts. Please see #29 for more information.
We are expecting to fix this issue as soon as possible.

> my media keys stop working
FYI, ModernFlyouts won't affect the functioning of the media keys. You misunderstood the functionality of our app.
ModernFlyouts won't affect any part of the system except replacing the native flyout.

**Comment by ShankarBUS** [comment] 2020-12-25 19:06
@Prakrit-170807,

I now have to close this issue as a duplicate of #29. Please keep up-to-date with it. A fix is under construction and will soon be provided with the v0.9 release. Please be patient.

**Closed by ShankarBUS** 2020-12-25 19:06 UTC
Labels: bug
