### ISSUE TITLE
brief pop-up when a new track is played automatically

### ISSUE THREAD

**Issue by Laplace9** [ModernFlyouts-Community/ModernFlyouts#1294] opened 2024-04-17 08:42 UTC
### Description of the new feature / enhancement

wish the app would show pop-up when it moves to next song automatically from playlist 

### Scenario when this would be used?

Basically I'm expecting a feature where a brief popup appears for a few seconds whenever the next song is played automatically, without requiring any manual intervention. This feature would allow us to quickly determine if the current song is to our liking, or if we want to skip it, or if we want to save it for later.

This functionality was previously available in the Groove app, I mean it's a very basic feature; however, it is no longer working after it became "media player". 

### Additional context

An example that closely resembles what I am seeking is when the media player app displays information in a pop-up at the top left corner when we skip tracks. What I am looking for a similar behavior where, when a song ends and automatically moves to the next track in a playlist, a pop-up notification will appear, mirroring the current app's behavior when skipping tracks. I hope I'm making some sense here.

At least give us an option to turn it on/off if it can't be added by default. This will make the app more polished.

**Comment by prakharb5** [comment] 2024-07-22 19:18
Duplicate of #78

**Comment by Samuel12321** [comment] 2024-07-23 04:20
Closed as tracking this on #78
 Not completed

**Closed** 2024-07-23 04:21 UTC
Labels: Enhancement

**Comment by Samuel12321** [comment] 2024-07-23 08:36
@Laplace9 we haven't added this feature yet. As stated above we are tracking this in another ticket, #78 which is still open as we haven't added this feature yet.
