### ISSUE TITLE
Crash: Clicking on "Enable Audio Flyouts" toggle in settings crashes the app

### ISSUE THREAD

**Issue by slowDrag0n** [ModernFlyouts-Community/ModernFlyouts#961] opened 2022-02-24 17:12 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 20H2

### OS build

19042.1526

### Platform

x64

### Steps to reproduce

1.  Double Click Tray Icon to open settings
2. Select audio tab in settings from sidebar
3. Click on toggle switch labeled "Enable Audio Flyouts"

### ✔️ Expected Behavior

Audio Flyouts should be toggled on/off based on selected option

### ❌ Actual Behavior

The app crashed.

**Comment by Cyberdroid1** [comment] 2022-02-24 17:32
Duplicate of #888

**Closed by Cyberdroid1** 2022-02-24 17:32 UTC
Labels: Bug
