### ISSUE TITLE
Bug: Precision Trackpad Support is Weird

### ISSUE THREAD

**Issue by superluig164** [ModernFlyouts-Community/ModernFlyouts#506] opened 2021-03-14 03:39 UTC
When using the touchpad to adjust volume (I have it mapped to 4 fingers up/down) it only works under 2 conditions:

a) the panel was already open
b) the volume being adjusted is over 02.

Otherwise the stock volume panel is shown.

Steps:
Ensure you are using a laptop or touchpad with the Windows Precision Touchpad drivers.
Set up the gestures in Settings to make one for adjusting volume.
Try to adjust the volume, you should see the stock Windows panel.
Hit the volume button once to pop up the ModernFlyouts panel, then quickly use the touchpad, it should work okay until you get below 02, then it will switch back to the stock Windows panel.

Windows 10 20H2 19042.804

ModernFlyouts 0.9.0.0

**Comment by Samuel12321** [comment] 2021-03-14 19:33
duplicate of #4, please see #4 for further updates on this issue

**Closed by Samuel12321** 2021-03-14 19:33 UTC
Labels: Bug
