### ISSUE TITLE
Bug: Multiple sessions of music playing activity displayed despite only one session being active

### ISSUE THREAD

**Issue by rsmyst** [ModernFlyouts-Community/ModernFlyouts#443] opened 2021-02-14 14:42 UTC
**Describe the bug:**
Duplicate sessions of the same music playing session open up every time but only one of them have the controls and music metadata displayed. Also, if you have multiple sources of music open, for example, whatsapp desktop (when playing back audio recordings), voice recorder app (playing back recordings), groove music, youtube, spotify, etc. all these sessions will be displayed alongside the duplicating on every session making the thing unusable. This happens even if only one source is actively playing the content. For example, even if we are only playing spotify, 2 sessions of spotify, 3 sessions of whatsapp, 4 sessions of voice recorder, 2 sessions of youtube will be displayed. none of them are usable though. 
one workaround I found it going into the 3-dot menu and stopping the unnecessary ones. This seems to be working.

1. open a bunch of sources of audio output
2. play audio in each of those one by one.
3. stop playing audio in one application then move on to the next one.
4. Start playing music in a single service (eg: only spotify)
5. use volume control
6. You will find many sessions despite nothing being played.

**Screenshots:**
No screenshot unfortunately since I restarted the app and the issue seems to be gone now... a similar issue is already open I believe but it doesn't cover the multiple sessions part.

**OS Version:**
windows 10 20H2

**ModernFlyouts Version:**
0.9.0.0

**Comment by generalguy41** [comment] 2021-02-14 14:54
I haven't done the steps to reproduce, but it's been happening to me lately as well and I happened have a screenshot of the issue.
![image](https://user-images.githubusercontent.com/8879244/107880027-4a997a00-6eaa-11eb-85d2-56fd595abb60.png)
I've also seen it with multiple others (multiple Firefox/YouTube, multiple video players, etc), all exceeding the 3 session limit as well. A restart does "fix" the issue though.

**Comment by ShankarBUS** [comment] 2021-02-14 14:55
@ADeltaX, could you look into this?

**Comment by rsmyst** [comment] 2021-02-14 15:08
> I haven't done the steps to reproduce, but it's been happening to me lately as well and I happened have a screenshot of the issue.
> ![image](https://user-images.githubusercontent.com/8879244/107880027-4a997a00-6eaa-11eb-85d2-56fd595abb60.png)
> I've also seen it with multiple others (multiple Firefox/YouTube, multiple video players, etc), all exceeding the 3 session limit as well. A restart does "fix" the issue though.

On a side note, how did you get the volume controller to display below the active sessions? looks pretty neat.

**Comment by generalguy41** [comment] 2021-02-14 15:19
> On a side note, how did you get the volume controller to display below the active sessions? looks pretty neat.

@rsmyst Set the stacking direction to Descending
![image](https://user-images.githubusercontent.com/8879244/107880606-ebd5ff80-6ead-11eb-9fbf-12323032c037.png)

**Comment by rsmyst** [comment] 2021-02-14 15:33
Oh thanks a lot @generalguy41

**Comment by Samuel12321** [comment] 2021-03-04 00:59
Duplicate of #381 , this has been fixed in 0.9.2 which will be released in the next few days.

**Closed by Samuel12321** 2021-03-04 00:59 UTC
Labels: Bug, Media
