### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Loremly** [ModernFlyouts-Community/ModernFlyouts#756] opened 2021-08-17 14:29 UTC
**Describe the bug:**
Tooltips for media controls are under the window making it hard to see some of them.
**To Reproduce:**
1. Press any functioning media control on your keyboard.
2. Hover on any of the controls at the bottom of the flyout

**Screenshots:**

![preview](https://i.imgur.com/fQyM2aD.png)

**OS Version:**
 - Windows 11 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Comment by Cyberdroid1** [comment] 2021-08-17 18:20
Duplicate of #377

**Closed by Cyberdroid1** 2021-08-17 18:20 UTC
Labels: Bug
