### ISSUE TITLE
Open the flyouts with a set key compination

### ISSUE THREAD

**Issue by Jooosl** [ModernFlyouts-Community/ModernFlyouts#964] opened 2022-03-02 16:06 UTC
### Description of the new feature / enhancement

I'd like to open the audio float as a "media player" with a global shortcut, to set them to any combination i'd like (I'm also using a macro pad as a way to activate key combinations, for example f12 + ...)

### Scenario when this would be used?

when i want to see the current song, click play next or return without using different shortcuts.

**Comment by Samuel12321** [comment] 2022-03-27 00:03
Duplicate of #468 
coming with 0.11

**Closed by Samuel12321** 2022-03-27 00:03 UTC
Labels: Enhancement
