### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by eisumon** [ModernFlyouts-Community/ModernFlyouts#687] opened 2021-07-04 14:24 UTC
**Describe the bug:**
1. When I'm trying to disable the Audio Flyout option the app is crashed and exist automatically. The change is not applied.
2. When I'm trying to increase or decrease the brightness, the Brightness Flyout is not showing. 

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 11 Version: [  Windows 11 Insider Preview 10.0.22000.51(co_release)]

**ModernFlyouts Version:**
 - Version: [ v0.9.3.0]

**Additional context:**

**Comment by Samuel12321** [comment] 2021-07-04 22:04
duplicate of #592 this will be fixed in the next update

**Closed by Samuel12321** 2021-07-04 22:04 UTC
Labels: Bug
