### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by RMD-A** [ModernFlyouts-Community/ModernFlyouts#1179] opened 2023-03-29 00:51 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 21H2

### OS build

22000.1696

### Platform

x64

### Area(s) with issue?

General, Installer

### Steps to reproduce

installed app from both Microsoft store and GitHub. installs perfectly but doesn't open at all

### ✔️ Expected Behavior

opening the app or a widget on the taskbar

### ❌ Actual Behavior

nothing happens

**Comment by bajwaboi** [comment] 2023-04-06 07:38
> ### ModernFlyouts Version
> 0.9.3
> 
> ### Windows version
> Windows 11 21H2
> 
> ### OS build
> 22000.1696
> 
> ### Platform
> x64
> 
> ### Area(s) with issue?
> General, Installer
> 
> ### Steps to reproduce
> installed app from both Microsoft store and GitHub. installs perfectly but doesn't open at all
> 
> ### ✔️ Expected Behavior
> opening the app or a widget on the taskbar
> 
> ### ❌ Actual Behavior
> nothing happens
> 
> ### Other Software
> _No response_
> 
> ### Additional Context
> _No response_

i am facing the same issue on my laptop, Windows 11.

**Comment by bajwaboi** [comment] 2023-04-06 08:03
@RMD-A https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1164#issuecomment-1412100509

**Comment by Spoon91** [comment] 2023-04-09 05:17
Having the same problem with the latest version of Windows 11 and latest version of Modernflyouts

**Comment by bajwaboi** [comment] 2023-04-15 06:55
@Spoon91 https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1164#issuecomment-1412100509

**Comment by Samuel12321** [comment] 2023-08-04 06:50
Closing as a duplicate of #1164

**Closed** 2023-08-04 06:49 UTC
Labels: Bug
