### ISSUE TITLE
Bug (I think): scrolling and changing music don't work for all apps

### ISSUE THREAD

**Issue by Lukasz-egg** [ModernFlyouts-Community/ModernFlyouts#379] opened 2021-01-23 17:09 UTC
In spotify changing and scrolling music works very good, but when i open youtube in Microsoft Edge (ver.  88.0.705.50), scrolling and changing music don't work (pause/play and info about music features work), Windows 10 20H2 , media flyout ver. 0.9.0 

Update: sometimes on playlists changing works, but it can stop working (refreshing page helps), i think that's problem with youtube.com, but you can check it 😉

**Comment by ShankarBUS** [comment] 2021-01-24 03:15
Wut?

Are you talking about the media playback position slider?

MS Edge doesn't support it.

It is something that we can do nothing about. Dil vid it 😎

**Comment by ShankarBUS** [comment] 2021-01-24 03:17
This is not a bug. This is a wont fix.

Because it is duty of the source media application to support the required features. If they don't support certain feature, we disable the corresponding control in our media session controls. We can not do anything. Sorry.

**Closed** 2021-01-24 05:47 UTC
Labels: Bug, Wontfix
