### ISSUE TITLE
Alt+Shift sometimes brings Audio Flyout

### ISSUE THREAD

**Issue by N0rule** [ModernFlyouts-Community/ModernFlyouts#650] opened 2021-06-08 09:07 UTC
Sometimes after rebooting pc,recognizes alt+shift as audio flyout keybind and brings the flyout
![image](https://user-images.githubusercontent.com/30196774/121156960-d49e9180-c851-11eb-8db3-077829016581.png)

**Comment by ErenAKGUN2007** [comment] 2021-06-08 09:09
Duplicate of #584

**Closed** 2021-06-09 05:38 UTC
Labels: Bug, Duplicate
