### ISSUE TITLE
Bug:Sound HUD jumps out without change sound.

### ISSUE THREAD

**Issue by HydrogenDeuterium** [ModernFlyouts-Community/ModernFlyouts#626] opened 2021-05-21 16:04 UTC
**Describe the bug:**

when I change language(press Win+Space),sound HUD jumps out ,which I expected not to.

**To Reproduce:**
Press Win(not release);
Press Space; 
Release both(or not ,that will cause the short key repeat)

**Screenshots:**
![image](https://user-images.githubusercontent.com/36532302/119166284-057c7980-ba91-11eb-98a7-0a54992d66f8.png)

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

**Comment by ErenAKGUN2007** [comment] 2021-05-21 16:06
Duplicate of #584

**Comment by Cyberdroid1** [comment] 2021-05-22 10:05
Thanks @ErenAKGUN2007 !

Closing as duplicate of #584.

**Closed by Cyberdroid1** 2021-05-22 10:05 UTC
Labels: Bug
