### ISSUE TITLE
Volume Flyout appears when I change keyboard language using Win + Spacebar

### ISSUE THREAD

**Issue by tarasburia** [ModernFlyouts-Community/ModernFlyouts#637] opened 2021-05-28 06:57 UTC
I use three keyboard languages on my PC (English, Russian, and Ukrainian.) Whenever I change the language using the Win + Spacebar shortcut, ModernFlyouts displays the volume flyout.

The problem does not occur with the Shift + Alt shortcut.

**Windows version**: 19043.985
**ModernFlyouts version**: 0.9.3.0

Not sure if that is related, but I am using Logitech MX Keys keyboard with Logitech Options installed.

**Comment by ErenAKGUN2007** [comment] 2021-05-28 06:59
Duplicate of #584

**Closed** 2021-05-28 07:08 UTC

**Comment by Cyberdroid1** [comment] 2021-05-28 17:29
Duplicate of #584.
