### ISSUE TITLE
Currently if you use a windows precision trackpad and change the volume the old windows flyout comes up. It would be great if you could fix this.Bug:

### ISSUE THREAD

**Issue by Jaspreetiscool1** [ModernFlyouts-Community/ModernFlyouts#515] opened 2021-03-19 00:14 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-03-19 02:52
Duplicate of #4. Please check that issue.

**Closed** 2021-03-19 02:52 UTC
Labels: Bug, Duplicate
