### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by V0xyy** [ModernFlyouts-Community/ModernFlyouts#945] opened 2022-02-08 13:19 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 21H2

### OS build

19044.1466

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Start by opening Spotify->type any song-> play it-> open any other app-> try to return to the previous track

### ✔️ Expected Behavior

to return or skip to the other track

### ❌ Actual Behavior

cant return, skip or pause the track

**Comment by Samuel12321** [comment] 2022-03-27 00:30
Duplicate of #532

**Closed by Samuel12321** 2022-03-27 00:30 UTC
Labels: Bug
