### ISSUE TITLE
Button tooltips show behind Flyout 

### ISSUE THREAD

**Issue by WouterVanGoey** [ModernFlyouts-Community/ModernFlyouts#1099] opened 2022-09-20 09:46 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 21H2

### OS build

22000.856

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Hovering over flyout buttons shows the mouse tooltip behind the flyout, making text illegible.

<img width="316" alt="NVIDIA_Share_1WOzFuDgw4" src="https://user-images.githubusercontent.com/6655152/191225009-35741c53-1a3d-4c9d-95f2-ef0673b70a6f.png">

### ✔️ Expected Behavior

Tooltips show in front of the flyout.

### ❌ Actual Behavior

Tooltips show behind the flyout.

### Additional Context

Happens with all tooltips, not just on hovering over media playback buttons.

**Comment by Samuel12321** [comment] 2022-10-02 02:39
Duplicate of #377

**Closed by Samuel12321** 2022-10-02 02:39 UTC
Labels: Bug
