### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by aarmn** [ModernFlyouts-Community/ModernFlyouts#703] opened 2021-07-15 20:22 UTC
**Describe the bug:**
all of the alt texts of sound flyout (at least it's the one I tested) fall behind the flyout itself

**To Reproduce:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/29726901/125852052-7cbe1f90-65e4-476b-a733-5da87a1f28db.png)

**OS Version:**
 - Windows 11 Version:  21H2:22000.65

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

**Comment by ErenAKGUN2007** [comment] 2021-07-16 06:04
Duplicate of #377

**Closed** 2021-07-16 07:42 UTC
Labels: Bug
