### ISSUE TITLE
Flyout stays on screen after waking PC up from sleep

### ISSUE THREAD

**Issue by dylannguyennn** [ModernFlyouts-Community/ModernFlyouts#1314] opened 2024-06-28 17:49 UTC
### ModernFlyouts Version

0.9.8513.0

### Windows version

Windows 10 10.0.19045

### OS build

19045

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Putting the computer to sleep and then waking it up and using the audio flyout causes it to stay stuck on the screen. I'm not sure if length of time that the computer is asleep for has anything to do with it, but my computer is typically asleep for about 8 hours.

### ✔️ Expected Behavior

After using the audio flyout, the flyout should disappear/fade out after the preset amount of time.

### ❌ Actual Behavior

The audio flyout stayed on the screen. It's unable to be closed using the X button, since it immediately reppears. The only way to close it is by exiting the program through the system tray or by exiting the program through Task Manager, although both of these further causes odd system-wide bugs.

**Comment by manstheram** [comment] 2024-06-28 17:51
It may be possible to force the flyout to close by clicking just outside the edge of it.

**Comment by prakharb5** [comment] 2024-07-05 09:40
Duplicate of #464

**Closed by prakharb5** 2024-07-05 09:40 UTC
Labels: Bug
