### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by CHSXuan** [ModernFlyouts-Community/ModernFlyouts#985] opened 2022-03-28 14:31 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2 Preivew

### OS build

22581.100

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Close Audio Flyout button

### ❌ Actual Behavior

Closing Audio Flyout after Windows 11 22H2 crashes the program

**Comment by Cyberdroid1** [comment] 2022-03-28 16:58
Duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/592

**Closed by Cyberdroid1** 2022-03-28 16:58 UTC
Labels: Bug
