### ISSUE TITLE
Feature Request: Automatically Open on Track Advance

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#401] opened 2021-01-26 23:04 UTC
**Describe the solution you'd like:**
When a new song comes on, I like to know what it is. I think it would be neat if the flyout could automatically open when the track advances.

**Additional context:**
App Version 0.9.0.0

**Comment by Cyberdroid1** [comment] 2021-01-27 04:42
I would consider this as a dupe of #78. Please check out that issue and share your opinion there.

**Closed** 2021-01-27 04:42 UTC
Labels: Duplicate, Enhancement, UI/UX
