### ISSUE TITLE
Music flyout not updating with the music that is currently playing from Spotify

### ISSUE THREAD

**Issue by Hewzac** [ModernFlyouts-Community/ModernFlyouts#1152] opened 2022-12-18 22:58 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/88815038/208323565-abfcc252-ad2c-4cf4-8727-6e56c737eea9.png)

### ✔️ Expected Behavior

The music from the flyout matches with the music from what I use as Spotify.

### ❌ Actual Behavior

The music from the flyout did not update to the current music playing from what I use as Spotify.

### Other Software

Spotify (Couldn't find version number)

**Comment by dlamh19** [comment] 2022-12-25 01:25
Happens on Windows 10 too

**Comment by ayZagen** [comment] 2024-07-22 13:31
still valid. running windows 11 version 23h2

**Comment by prakharb5** [comment] 2024-07-22 19:17
Duplicate of #684

**Closed by prakharb5** 2024-07-22 19:17 UTC
Labels: Bug
