### ISSUE TITLE
Bug: ModernFlyouts panel pops up after using language layout switching hotkeys

### ISSUE THREAD

**Issue by VladWinner** [ModernFlyouts-Community/ModernFlyouts#645] opened 2021-06-02 15:16 UTC
**Describe the bug:**
Since version 0.9.3.0, I have a volume bar pop up if I press these keyboard shortcuts: Win+Space or Alt+Shift
The problem occurs after upgrading to Windows 10 21H2.

**GIF:**
![Desktop 2021 06 02 - 18 07 02 05-1](https://user-images.githubusercontent.com/13555921/120506257-6def2300-c3ce-11eb-986d-7aad6be6fb61.gif)

**OS Version:**
Windows 10 21H2 19044.1023

**ModernFlyouts Version:**
0.9.3.0

**Comment by Samuel12321** [comment] 2021-06-02 23:25
Duplicate of #584

**Closed by Samuel12321** 2021-06-02 23:25 UTC
Labels: Bug
