### ISSUE TITLE
Can't see spotify GUI

### ISSUE THREAD

**Issue by Empxthic** [ModernFlyouts-Community/ModernFlyouts#754] opened 2021-08-16 20:28 UTC
When i open modern flyouts I can't see the spotify GUI or the volume I do once in a while but its rare I've also used capslock but it only shows that it turned on and off but I dont actually see the song 
![dawg](https://user-images.githubusercontent.com/89044534/129625474-24859654-8e1a-4bf0-a45a-cb6fcc7eb49a.PNG)

**Comment by Extertrout423** [comment] 2021-08-18 20:13
I get this too, I just downloaded it so I have no idea how to use it or why it doing this

**Comment by Flobii** [comment] 2021-08-18 23:48
Does it  show up when you change your volume level?

Because it replaces the default volume knob thing, so it'll show up when you change your volume and won't be present constantly.

**Comment by Cyberdroid1** [comment] 2021-08-19 04:24
@Empxthic @Extertrout423 can you see if pressing the play/pause button or the volume buttons pop up the media info, as @Flobii correctly says?

**Comment by Extertrout423** [comment] 2021-08-19 17:52
@Cyberdroid1 It didnt work, it still just shows the volume but not the song.

**Comment by Cyberdroid1** [comment] 2021-08-19 20:13
Ok thanks

Duplicate of #610

**Closed** 2021-08-19 20:13 UTC
