### ISSUE TITLE
The  layout is not closing automaticly

### ISSUE THREAD

**Issue by Knekki3** [ModernFlyouts-Community/ModernFlyouts#1291] opened 2024-03-29 11:51 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 23H2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

![Screenshot 2024-03-29 045051](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/132212828/781838e6-037e-4ced-81eb-ab9b64900fdd)

### ✔️ Expected Behavior

it closing on its own

### ❌ Actual Behavior

It aint clossing on its own

**Comment by prakharb5** [comment] 2024-07-05 09:39
Duplicate of #464

**Closed by prakharb5** 2024-07-05 09:39 UTC
Labels: Bug
