### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by hrcxr** [ModernFlyouts-Community/ModernFlyouts#869] opened 2021-11-07 01:45 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows Version:  Windows 10 Pro

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

Pressing Windows + M changes language for my PC, and it also opens up the ModernFlyout and i am wondering how do i disable this as there is no settings for this..

**Comment by arnavbhate** [comment] 2021-11-07 11:24
Duplicate of #584

**Closed** 2021-11-07 12:00 UTC
Labels: Bug
