### ISSUE TITLE
Does not block the default windows volume 

### ISSUE THREAD

**Issue by Wambyat** [ModernFlyouts-Community/ModernFlyouts#1118] opened 2022-10-07 02:40 UTC
### ModernFlyouts Version

"0.9.3.0"

### Windows version

"Windows 11 22H2"

### OS build

"22621.521"

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Install the latest version of windows 11 and turn on modern flyouts. Both the mordern flyouts volume indicator and the new default windows one will come up.
![image](https://user-images.githubusercontent.com/77496170/194456589-5d516e32-20db-4c76-ba90-751db4fa9ef5.png)

### ✔️ Expected Behavior

The default windows volume indicator should be blocked.

### ❌ Actual Behavior

Both volume indicators are showing up.

**Comment by webtimo-de** [comment] 2022-10-07 12:02
I've also observed this problem. However, to all of you reading here, please bear with the developers as these flyouts come from Windows 11 22H2 Update. And are therefore new.

**Comment by Samuel12321** [comment] 2022-10-15 22:28
Duplicate of #920

**Closed by Samuel12321** 2022-10-15 22:28 UTC
Labels: Bug
