### ISSUE TITLE
Bug: Sometimes changing the language by pressing Shift+Alt shows the volume level

### ISSUE THREAD

**Issue by MaxG1k** [ModernFlyouts-Community/ModernFlyouts#735] opened 2021-08-04 18:52 UTC
Describe the bug:

Sometimes changing the language by pressing Shift+Alt shows the volume level

To Reproduce:

Change the language on the computer by pressing Shift+Alt
Then the volume slider will appear
Screenshots:

OS Version:

Windows 10 Version: 19041.1110
ModernFlyouts Version:

Version: 0.9.3.0
Additional context:

I apologize if this topic has already been, to be honest, at the time of publication I did not see another one

**Comment by ShankarBUS** [comment] 2021-08-04 19:07
We haved fixed it in v0.10. We are currently having some issues in publishing the release. You should wait for a few days.

**Comment by MaxG1k** [comment] 2021-08-04 19:08
> f

Well, in any case, this is great news! Thank you for the already great app!

**Comment by Cyberdroid1** [comment] 2021-08-05 06:51
Duplicate of #584

**Closed by Cyberdroid1** 2021-08-05 06:51 UTC
Labels: Bug
