### ISSUE TITLE
App crashes when trying to turn off audio flyout

### ISSUE THREAD

**Issue by LudanShrestha** [ModernFlyouts-Community/ModernFlyouts#594] opened 2021-04-29 04:32 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

When I try to turn off the audio flyout the app crashes and also stops to work. You will have to start the app again to run.

**Comment by ADeltaX** [comment] 2021-04-30 01:03
I'm dumb, that's why it crashes.
(duplicate of: #592)

**Closed by ADeltaX** 2021-04-30 01:03 UTC
Labels: Bug

**Comment by LudanShrestha** [comment] 2021-04-30 02:33
> I'm dumb, that's why it crashes.
> (duplicate of: #592)

@ADeltaX Is this really how you respond to a bug report?

**Comment by ShankarBUS** [comment] 2021-04-30 03:19
@LudanShrestha, Y E S.

We are not professionals, you shouldn't expect professionality from us.

We built this app for fun and are still doing it for fun.

**Comment by LudanShrestha** [comment] 2021-04-30 03:33
@ShankarBUS Didn't really want to offend you. The app overall is amazing tho.

**Comment by ShankarBUS** [comment] 2021-04-30 03:39
@LudanShrestha,

No no mate, I am not really offended 😄.

We never have been professionals, we are just college students. We have been building this app for fun. That's why we are being playful.

We will change eventually.

**Comment by LudanShrestha** [comment] 2021-04-30 05:21
@ShankarBUS Lol 🤣🤣Keep making these amazing projects. 😍Cheers mate ✌✌
