### ISSUE TITLE
Bug: Flyout is on top of text tooltips

### ISSUE THREAD

**Issue by nolemretaWxd** [ModernFlyouts-Community/ModernFlyouts#586] opened 2021-04-25 10:01 UTC
**Describe the bug:**
Flyout is on top of text tooltips

**To Reproduce:**
1. Hover on any button on a flyout
2. Tooltip should be on top of the flyout but it isn't

**Screenshots:**
![image](https://user-images.githubusercontent.com/31414969/115989274-e4258c00-a5bd-11eb-808f-a161abaf92a2.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

**Comment by Samuel12321** [comment] 2021-04-25 10:03
Duplicate of #377

**Closed by Samuel12321** 2021-04-25 10:03 UTC
Labels: Bug
