### ISSUE TITLE
Media control

### ISSUE THREAD

**Issue by WilliamAnimate** [ModernFlyouts-Community/ModernFlyouts#573] opened 2021-04-19 00:21 UTC
overall, PERFECT app, but pausing/rewind/forward does not work

**Comment by Cyberdroid1** [comment] 2021-04-19 05:31
Please give us more info-
- what app version?
- which windows build?
- which media app are you using?
- screenshots or screen recording

**Comment by Samuel12321** [comment] 2021-04-19 10:25
Duplicate of #532

**Closed by Samuel12321** 2021-04-19 10:25 UTC
Labels: Needs Author feedback
