### ISSUE TITLE
Feature Request: AutoHotKey support (Brightness Flyout)

### ISSUE THREAD

**Issue by Movisivi** [ModernFlyouts-Community/ModernFlyouts#222] opened 2020-11-16 04:15 UTC
**Describe the bug:**

I use Autohotkey to use pg-up and pg-down for brightness control because the built in ones don't work. The volume flyout is replaced fine but the brightness is not. 

**Screenshots:**

**OS Version:**
 - Windows 10 2004 19041.264: 

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**

**Comment by ShankarBUS** [comment] 2020-11-16 04:16
Could you share me your ahk script?

I have to test on mine first and evaluate the possibilities to make it work.

**Comment by Samuel12321** [comment] 2020-11-16 04:18
So essentially you are asking for support for custom trigger keys or assigned key shortcuts

**Comment by ShankarBUS** [comment] 2020-11-16 04:46
Not really.

Autohotkey intercepts the registered hotkey (Pg Up, Down in their case) for a specified function and runs the script (this what I need) of the function (i.e. to change brightness and trigger the flyout).

So Autohotkey has a method to trigger the built-in brightness flyout which we don't support.

We should support every method that the built-in flyout supports.

**Comment by Movisivi** [comment] 2020-12-04 04:12
> 
> 
> Could you share me your ahk script?
> 
> I have to test on mine first and evaluate the possibilities to make it work.

Sorry for the delay in response. Github didn't notify me via its desktop notifications and I don't check this email. Here's the ahk script https://pastebin.com/XMrabgMz

**Comment by Movisivi** [comment] 2021-01-05 02:59
Bump. Happy new year! How's progress going on this, any updates?

**Comment by Samuel12321** [comment] 2021-01-05 05:10
Hi @Movisivi , there hasn't been any progress on this yet. There have been a few more pressing issues to deal with. Thanks for your patience.
I will tentatively add this to the 0.10.5 release.

**Comment by ShankarBUS** [comment] 2021-01-10 16:42
Well, wait a minute, the AHK script to control the brightness is illegal. They shouldn't change brightness like that!

What they do is:
- Use Power management APIs to control the brightness which is kinda interesting. But WMI APIs would do just fine I hope. We could actually use the method to solve #301 or #86. Lets see if that works.
- And send a ShellHook message of value 0x37 manually to the native flyout in-order to show it.

I'll see if the existing shell hook works fine with this or whether we can hook the window message.

I'll start my work soon.

**Comment by ShankarBUS** [comment] 2021-01-10 16:50
Hmm they do use shell hook and we already handle `0x37` (= 55). Interesting.

**Comment by ShankarBUS** [comment] 2021-01-10 17:25
Hey @Movisivi,

Can you help me set up AutoHotKey with the script you posted?
How should I hook it up to test?

**Comment by Movisivi** [comment] 2021-01-10 17:30
I simply installed autohotkey, followed this video https://www.youtube.com/watch?v=k7e9MrP-U_g and pasted the code into it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ShankarBUS** [comment] 2021-01-10 17:30
Thanks!

**Comment by ShankarBUS** [comment] 2021-01-10 18:02
So, the problem is this script sends the window messages directly to the native flyout instead of sending it to the system.

@ADeltaX, could we hook the WndProc of the native flyout's hWnd?

@Movisivi, unfortunately this is hard to fix. Would #56 solve your problem?

**Comment by Movisivi** [comment] 2021-01-10 19:33
Sorry I don't understand

**Comment by GameBoyYeet** [comment] 2021-02-01 03:38
Maybe install the function key drivers for the corresponding computer, go to support, and download drivers

**Comment by Samuel12321** [comment] 2021-03-03 02:47
@Movisivi Use Keyboard Manager in Microsoft's PowerToys app instead of auto hotkeys this will work with ModernFlyouts.

Unfortunately we don't have time to add support for these more unusual situations art the moment.

**Comment by Cyberdroid1** [comment] 2021-03-03 03:39
@Samuel12321 
Apparently, Keyboard Manager does not make remapping keys to control brightness possible since it does not have that option.

**Comment by Samuel12321** [comment] 2021-03-03 03:41
Ok will reopen

**Comment by Movisivi** [comment] 2021-06-22 20:30
So what's the current situation?

**Comment by ShankarBUS** [comment] 2021-06-23 23:49
We will try to provide custom hotkey support instead of supporting AutoHotKey.

**Comment by Samuel12321** [comment] 2021-10-11 22:30
closing in favor of #468

**Closed by Samuel12321** 2021-10-11 22:30 UTC
Labels: Bug, Good First Issue
