### ISSUE TITLE
Feature Request: Add optional volume sliders like the ones in the Volume Mixer utility

### ISSUE THREAD

**Issue by INeedTogepi** [ModernFlyouts-Community/ModernFlyouts#811] opened 2021-09-19 20:58 UTC
**Is your feature request related to a problem? Please describe:**
I always find it irritating to have to open the Volume Mixer utility by right-clicking on the volume icon on my taskbar just to change a specific program's volume. It was only today that I found a way to change it using AutoHotkey and nircmd, but when I change the focused window's volume, the volume overlay doesn't display.

**Describe the solution you'd like:**
 I would like to request that the individual volume sliders for separate apps/programs found in the Volume Mixer utility be replicated in the audio flyout.

**Describe alternatives you've considered:**
I could put up with not being able to see what the focused window's volume on screen when I change it.

**Additional context:**
Volume Mixer:
![image](https://user-images.githubusercontent.com/1144106/133942775-4f506995-bd67-43d9-9059-3e78ae52080d.png)

**Comment by Cyberdroid1** [comment] 2021-09-20 06:32
Duplicate of #164 
Please check pinned issues and search for other issues before opening a new one :)

**Closed by Cyberdroid1** 2021-09-20 06:32 UTC
Labels: Enhancement
