### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by ProviceUnify** [ModernFlyouts-Community/ModernFlyouts#602] opened 2021-05-03 09:54 UTC
**Describe the bug:**

At changing language (Win + Space) layout showing up but that's not should be.

**To Reproduce:**

1. Press Win + Space
2. Getting the strange behavior - layout showing up

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 20H2 

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

Possible way to temporarily escape that issue: using media key "play/pause" on keyboard to pause and play track is disable handling Win + Space combination until next Windows start.

**Comment by Samuel12321** [comment] 2021-05-03 10:30
Duplicate of #584

**Closed by Samuel12321** 2021-05-03 10:30 UTC
Labels: Bug
