### ISSUE TITLE
Bug: Media controls don't appear for spotify

### ISSUE THREAD

**Issue by rsmyst** [ModernFlyouts-Community/ModernFlyouts#640] opened 2021-05-30 05:04 UTC
**Describe the bug:**
As title says. When using spotify windows 10 app, I am not able to control it through the media controls on modernflyouts. The controls are just greyed out. 
Also noticed that it randomly works sometimes but most of the time it doesn't.

**To Reproduce:**
1. Open spotify and play some music
2. Use modernflyouts.

**Screenshots:**
![image](https://user-images.githubusercontent.com/30620767/120092684-94d2fe00-c11d-11eb-8ce9-f10d1f833498.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3

**Comment by gfififid** [comment] 2021-06-02 09:42
Same bug. Buttons work, if spotify was open before modernflyouts was launch.

**Comment by AndriiHarashchak** [comment] 2021-06-02 17:22
I have this bug too. Music window and buttons work only when ModernFlyouts was launched after the Spotify app.

**Comment by Cyberdroid1** [comment] 2021-06-03 04:42
Duplicate of #532

**Closed by Cyberdroid1** 2021-06-03 04:42 UTC
Labels: Bug
