### ISSUE TITLE
Being able to like songs on spotify

### ISSUE THREAD

**Issue by notseoc** [ModernFlyouts-Community/ModernFlyouts#936] opened 2022-02-01 06:16 UTC
### Description of the new feature / enhancement

Just being able to like a spotify song without tabbing to the actual app

### Scenario when this would be used?

Gaming, talking with someone on vc while spotify is minimized, etc

**Comment by arnavbhate** [comment] 2022-03-03 08:48
Duplicate of #823

**Closed** 2022-03-03 09:21 UTC
Labels: Enhancement
