### ISSUE TITLE
Settings menu layout page not translated into Chinese

### ISSUE THREAD

**Issue by TU0YDH** [ModernFlyouts-Community/ModernFlyouts#503] opened 2021-03-13 07:50 UTC
The layout has not been translated into Chinese,its language is English!

**Comment by Samuel12321** [comment] 2021-03-13 07:54
@TU0YDH Please fill out the issue template correctly or we are not able to help you.
You haven't provided enough information for us to work out the problem 
What version of ModernFlyouts are you using, os version screenshots etc...

**Comment by imgradeone** [comment] 2021-03-13 14:37
I could found this issue as well, which is even weird that we have already translated it into Chinese.
**Version:** 0.9.1
**OS:** Windows 10 20H2
@Samuel12321 
![屏幕截图(41)](https://user-images.githubusercontent.com/30969327/111033505-95c48f80-844c-11eb-8fad-ca1f0f23e7f0.png)

**Comment by Myuki** [comment] 2021-03-14 03:20
I have met the same problem, and I remember the old version has zh translation.

It may relate to #250 in v0.9.1. Chinese translation just disappear from the language list.

**Comment by Samuel12321** [comment] 2021-05-12 23:15
Duplicate of #605

**Closed by Samuel12321** 2021-05-12 23:15 UTC
Labels: Bug, Duplicate, Translation
