### ISSUE TITLE
Bug: Flyout keeps changing monitors (when multiple monitors are used)

### ISSUE THREAD

**Issue by writeblankspace** [ModernFlyouts-Community/ModernFlyouts#938] opened 2022-02-04 08:23 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

21H2

### OS build

22000.434

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Project to several screens
2. Select "layout" and choose the second monitor
3. At some random point (eg after the computer comes from sleep) the flyout will end up being on monitor 1 instead of monitor 2

### ✔️ Expected Behavior

The flyout will be on monitor 2

### ❌ Actual Behavior

The flyout goes to monitor 1 after sleeping

**Comment by langka774** [comment] 2022-02-10 10:13
Got the same issue, Flyout alternate the display number

**Comment by Dust019** [comment] 2022-02-21 19:16
I have a laptop and the same thing happens to me. Normally I have the Flyout on my laptop monitor, but everytime I unplug and plug my second monitor in again, it appears on the second monitor.

**Comment by Samuel12321** [comment] 2022-03-27 00:14
Duplicate of #736

**Closed by Samuel12321** 2022-03-27 00:14 UTC
Labels: Bug
