### ISSUE TITLE
Feature Request: Add the option to keep Lock Key Notification showing on the screen till deselected.

### ISSUE THREAD

**Issue by DeruiZhao** [ModernFlyouts-Community/ModernFlyouts#706] opened 2021-07-19 01:33 UTC
There is no breathing light on my laptop's CapsLock key. When I press the CapsLock button, I want the CapsLock key is always dispalyed on the screen and disappeared when I press the button again.

**Comment by JohnLGalt** [comment] 2021-07-19 14:01
I wouldn't mind this as a user selectable option.  But not as default.

**Comment by Cyberdroid1** [comment] 2021-07-19 14:17
So you want the flyout to work as a replacement for the indicator light on the Caps Lock key and keeps displaying "Caps Lock ON"?

**Comment by DeruiZhao** [comment] 2021-07-20 01:02
> So you want the flyout to work as a replacement for the indicator light on the Caps Lock key and keeps displaying "Caps Lock ON"?
> 
> 所以你希望弹出作为一个工作的指示灯上的大写锁定关键，并继续显示“大写锁定”？

Closely, I think it's good to give the "Caps lock" a switch button, which can keep "Caps lock ON" always showing on the screen.

**Comment by Samuel12321** [comment] 2021-12-26 04:52
Duplicate of #852

**Closed by Samuel12321** 2021-12-26 04:52 UTC
Labels: Enhancement
