### ISSUE TITLE
Clicking on the Language button on the taskbar or using the shortcut triggers the audio flyout

### ISSUE THREAD

**Issue by ElitePheonix2009** [ModernFlyouts-Community/ModernFlyouts#1126] opened 2022-10-20 05:12 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro 21H2

### OS build

19044.2130

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

1) Click on the language button on the taskbar or use the shortcut (win + space).

![image](https://user-images.githubusercontent.com/114980232/196861311-6c019ca4-b4e7-4bc1-b08f-a410515dc3fd.png)

2) See that the audio flyout pops up.

![image](https://user-images.githubusercontent.com/114980232/196862186-16a250fd-2676-4c1c-a6ef-9efd109a4f3d.png)

### ✔️ Expected Behavior

Do not trigger the audio flyout when clicking on the language tab on the taskbar or using the shortcut (win + space).

### ❌ Actual Behavior

The audio flyout pops up when clicking on the language tab on the taskbar or using the shortcut (win + space).

![image](https://user-images.githubusercontent.com/114980232/196862204-1559394a-20d8-49e9-a691-9d4768807964.png)

**Comment by prakharb5** [comment] 2023-01-14 10:00
Duplicate of #584

**Closed by prakharb5** 2023-01-14 10:00 UTC
Labels: Bug
