### ISSUE TITLE
When i switch the input method the volume bar may fly out

### ISSUE THREAD

**Issue by Summer-sn0w** [ModernFlyouts-Community/ModernFlyouts#612] opened 2021-05-08 06:34 UTC
LIKE TITLE
i am not sure weather it a bug.and it seems no need for repair.

**Comment by ErenAKGUN2007** [comment] 2021-05-08 07:12
Duplicate of #584

**Comment by ErenAKGUN2007** [comment] 2021-05-08 07:14
Duplicate of #584

**Closed** 2021-05-08 08:01 UTC
