### ISSUE TITLE
Doesn't work on windows 22H2.

### ISSUE THREAD

**Issue by drjkpalli** [ModernFlyouts-Community/ModernFlyouts#1119] opened 2022-10-09 04:54 UTC
Looks like the 22H2 update broke the app as it no longer works after the update. tried restarting several times but nothing.

**Comment by Wambyat** [comment] 2022-10-10 03:15
Check this [bug report](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1118)

**Comment by Samuel12321** [comment] 2022-10-15 22:27
Duplicate of #920

**Closed by Samuel12321** 2022-10-15 22:27 UTC
