### ISSUE TITLE
Bug:The music progress bar of the volume panel will not work when playing a song

### ISSUE THREAD

**Issue by MC-Nirvana** [ModernFlyouts-Community/ModernFlyouts#795] opened 2021-08-31 17:37 UTC
**Describe the bug:**

The music progress bar of the volume panel will not work when playing a song
**To Reproduce:**

1. Open Groove Music
2. Play any song
3. Call up the volume panel, find that the music progress bar does not work (display 0:00)
**Screenshots:**

https://i.loli.net/2021/09/01/cDR2yAEUOWPdI3e.png
**OS Version:**
 - Windows 10 Version: 
Windows11 22000.168
**ModernFlyouts Version:**
 - Version: 
v0.9.3.0
**Additional context:**

none

**Comment by Cyberdroid1** [comment] 2021-09-02 14:47
Duplicate of #542

**Closed by Cyberdroid1** 2021-09-02 14:47 UTC
Labels: Bug
