### ISSUE TITLE
Bug: When changing the language, a window appears with ModernFlyouts

### ISSUE THREAD

**Issue by TheFollenBest** [ModernFlyouts-Community/ModernFlyouts#600] opened 2021-05-01 04:36 UTC
When changing the language, a window appears with
ModernFlyouts

Example:
![Снимок экрана (3)](https://user-images.githubusercontent.com/67145215/116771056-89cf7400-aa72-11eb-8065-05fe3be371ba.png)

OS Version:
 - Windows 10 Version 20H2

ModernFlyouts Version:
 - Version:

**Comment by TheTolexDok** [comment] 2021-05-02 06:06
I have the same problem

**Comment by TheTolexDok** [comment] 2021-05-02 06:08
I also want to add that it also opens no matter how you change the language (win+space or shift+alt)

**Comment by Cyberdroid1** [comment] 2021-05-02 08:41
Duplicate of #584.

**Closed** 2021-05-02 08:41 UTC
Labels: Bug, Duplicate
