### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Devpineapple** [ModernFlyouts-Community/ModernFlyouts#328] opened 2020-12-29 20:28 UTC
When pressing the volume down or up buttons on an external headphone (Wired or Bluetooth), the flyout doesn't appear.
**To Reproduce:**

1. Press volume up or down on your headphones (if supported)
2. See error

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.5 MS-Store

**Additional context:**

This might be a bug or feature missing on the app/program. But if this is a feature missing from the app, please add it because i use my beats solo3 a lot and I normally use the in-headphone buttons rather than the built in buttons on my laptop.

**Comment by Samuel12321** [comment] 2020-12-29 21:18
Thanks for reporting this.
closing as a duplicate of #4 
see #4 for updates on this issue.

**Closed by Samuel12321** 2020-12-29 21:18 UTC
Labels: Duplicate
