### ISSUE TITLE
enable audio flyout BUG

### ISSUE THREAD

**Issue by scrgy** [ModernFlyouts-Community/ModernFlyouts#1098] opened 2022-09-20 02:49 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10 21H2

### OS build

19044.2006

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/76255863/191156113-1385f3ca-c6bc-4977-a7e5-614a34f66c6e.png)
This switch causes the software to exit

### ✔️ Expected Behavior

Turn off this switch

### ❌ Actual Behavior

Automatic software exit

### Other Software

nothing

### Additional Context

nothing

**Comment by Samuel12321** [comment] 2022-10-02 02:26
Hi,
Thanks for reporting this. We are aware of the problem and plan to fix this in the next update 0.11.

Closing as duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/888

**Closed by Samuel12321** 2022-10-02 02:26 UTC
Labels: Bug
