### ISSUE TITLE
On Windows 11, the volume change is incorrectly displayed

### ISSUE THREAD

**Issue by STaYsONzxc** [ModernFlyouts-Community/ModernFlyouts#1284] opened 2024-03-13 16:43 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 23h2

### OS build

22631.3296

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Add Volume on Windows 11

### ✔️ Expected Behavior

Correctly add volume without the standard Windows 11 window appearing

### ❌ Actual Behavior

2 windows appear, the MF window and the Windows window
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/80705216/db730ab3-befe-454b-abe6-6e4c36e2f51f)

**Comment by harsh160101065** [comment] 2024-05-07 14:07
Same issue here running on WIndows 11 Insider Preview Beta Build
22635.3570 Version 23H2

**Comment by prakharb5** [comment] 2024-07-04 12:38
Duplicate of #920

**Closed by prakharb5** 2024-07-04 12:38 UTC
Labels: Bug
