### ISSUE TITLE
Bug: Dispaly selection setting rested when connecting and disconnecting form display

### ISSUE THREAD

**Issue by arielAmselBGU** [ModernFlyouts-Community/ModernFlyouts#911] opened 2022-01-01 10:11 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Select in the setting the second display.
Disconnect from second display.
Change the volume.
Reconnect second display.
Change the volume -> now it should appear on the first display

### ✔️ Expected Behavior

After reconnecting to the second display it should show on the second display.

### ❌ Actual Behavior

After reconnecting It appears on the first display instead of the second although I changed it in the settings to be the first display.

**Comment by Samuel12321** [comment] 2022-01-01 10:16
Duplicate of #736

**Closed by Samuel12321** 2022-01-01 10:16 UTC
Labels: Bug
