### ISSUE TITLE
Feature Request: Add the option to fully theme the flyout with the accent color

### ISSUE THREAD

**Issue by Nikkicode** [ModernFlyouts-Community/ModernFlyouts#723] opened 2021-08-01 05:48 UTC
In Windows 10 and 11, there is an option to theme the whole taskbar/Start menu according to your accent color, besides the standard accent color behavior, making, for example, the whole taskbar blue, or green. To make the flyouts more consistent with Windows, it would be great if there was an option for that!

![image](https://user-images.githubusercontent.com/88263506/127760628-b22b631d-10c8-4d3e-bef8-f4f0b3ab1fb6.png)
The Start menu in Windows 11, themed around the purple accent color

**Additional context:**
The flyout already follows the accent coloring in Windows, as shown here using the same purple from the Start, but it only has the basic accent color behavior, with no option to color the whole flyout in the accent color

![image](https://user-images.githubusercontent.com/88263506/127760521-3c7bf804-a9e0-4f35-8065-ea09b6d28221.png)

Thanks for the amazing app!

**Comment by Cyberdroid1** [comment] 2021-08-01 13:32
Closing as duplicate of #67

**Closed by Cyberdroid1** 2021-08-01 13:32 UTC
Labels: Enhancement
