### ISSUE TITLE
ModernFlyouts crash when disable volume only.

### ISSUE THREAD

**Issue by HRPF** [ModernFlyouts-Community/ModernFlyouts#1136] opened 2022-11-12 06:55 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 Pro Insider Preview 22H2

### OS build

25236.1010

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/62463449/201461531-0e92aed3-38b0-43a6-b926-36c357ad3707.png)
Simple click the "启用音频浮出控件" switch button.

### ✔️ Expected Behavior

The program runs normally.

### ❌ Actual Behavior

The whole app crashed/stopped.

**Comment by zhenjie1999** [comment] 2022-12-19 03:07
windows 11 stable version also have same problem

**Comment by prakharb5** [comment] 2023-01-14 10:03
Duplicate of #888

**Closed by prakharb5** 2023-01-14 10:03 UTC
Labels: Bug
