### ISSUE TITLE
App doesn't run at startup; Laggy & Unresponsive UI

### ISSUE THREAD

**Issue by ZhhTeo** [ModernFlyouts-Community/ModernFlyouts#1299] opened 2024-05-06 07:54 UTC
### ModernFlyouts Version

0.10.0

### Windows version

Windows 11 Home Single Language 23H2

### OS build

22631.3527

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout

### Steps to reproduce

Flyouts doesn't run at Startup
1. Enable 'Run at startup' from Modern Flyout settings
2. Enable Startup on Windows Task Manager
3. Restart the computer
4. Modern Flyouts don't run on startup

Laggy & Unresponsive UI
1. Open Spotify and Play Song
2. Spotify Flyouts has a 5-10 seconds delayed response on UI when there's action on Spotify i.e. Play/Pause; Previous/Next Song; Media Session Timeline.

### ✔️ Expected Behavior

- Flyouts run at Windows startup
- Responsive UI with accurate timing on Spotify Flyouts

### ❌ Actual Behavior

- Flyouts did not run at Windows startup
- Unresponsive UI with inaccurate timing on Spotify Flyouts

### Other Software

Spotify

### Additional Context

Please also upload the latest version of Flyouts to MS Store asap, thank you.

**Comment by sirdoombox** [comment] 2024-06-13 11:20
I'm in the same position on the latest beta. This poor performance and especially unresponsive Spotify flyout behaviour is present on both the latest 10.0.0 Beta and the version available on the MS Store.

Win11 Pro 23H2 - 22631.3737

**Comment by ZhhTeo** [comment] 2024-06-13 13:06
Get the v0.9.0 from Releases, I have tested every single release, and that's the one you're looking for. Thank me later :)

**Comment by sirdoombox** [comment] 2024-06-18 16:35
0.9 seems to exhibit the exact same behaviour on my machine. I'm happy to accept the poor performance though with a lack of any real alternatives.

**Comment by prakharb5** [comment] 2024-07-23 07:33
You can follow this for now: https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/437#issuecomment-792143025
Duplicate of #437

**Closed by prakharb5** 2024-07-23 07:33 UTC
Labels: Bug
