### ISSUE TITLE
Bug: Tooltip gets hidden behind Flyout

### ISSUE THREAD

**Issue by arnavbhate** [ModernFlyouts-Community/ModernFlyouts#696] opened 2021-07-11 13:53 UTC
**Describe the bug:**

The tooltip that appears when hovering on text is getting hidden behind the flyout. For example the options in the TopBar or the title and artist in the media flyout.

**To Reproduce:**
Steps to reproduce the behaviour:
1. Set TopBar Visibility to visible.
2. Make any flyout appear.
3. Hover on any of the options on the TopBar.
4. See error.

**Screenshots:**

![Screenshot (313)](https://user-images.githubusercontent.com/86760472/125197932-559bdf00-e27d-11eb-8ee6-d539bdb3a136.png)

**OS Version:**
 - Windows 10 Version: Windows 10 21H1 19043.1083

**ModernFlyouts Version:**
 - Version: v0.9.3

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-07-12 06:21
Duplicate of #377

**Closed by Cyberdroid1** 2021-07-12 06:21 UTC
Labels: Bug
