### ISSUE TITLE
Feature Request: Popup media flyout when media is controlled from another source

### ISSUE THREAD

**Issue by superluig164** [ModernFlyouts-Community/ModernFlyouts#809] opened 2021-09-17 04:55 UTC
For example, if the song is changed automatically, or play/paused from some other method besides the media buttons.  Maybe make it an option because more options are always better.

I would primarily find this useful to show when the song changes on my media player.

**Comment by BasicallyWiz** [comment] 2021-09-17 06:40
I think this lacks specifics. Are you suggesting that the flyout automatically shows when some media status changes? The suggestion isn't exactly very clear here.

**Comment by superluig164** [comment] 2021-09-17 06:51
That's exactly what I was suggesting.  Examples:

Your music player advances to the next song (the status changes because the song changed.)
You change the song from the media player (as opposed to using media keys.)
You start playing music from the media player (as opposed to using media keys.)
etc.

**Comment by Samuel12321** [comment] 2021-09-19 08:56
Duplicate of #78

**Closed by Samuel12321** 2021-09-19 08:56 UTC
Labels: Enhancement
