### ISSUE TITLE
错误：

### ISSUE THREAD

**Issue by TwilightSFA** [ModernFlyouts-Community/ModernFlyouts#678] opened 2021-06-24 16:48 UTC
**Describe the bug:**

The first is that the program will exit abnormally when the audio flyout control is closed, and all functions will be invalid. In case of win+space, the audio float control will be called but the volume will not be increased or decreased. These problems have not been resolved after I reinstalled.

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 
 - Windows 10 20H2 

**ModernFlyouts Version:**
 - Version: 
 - v0.9.3.0

**Additional context:**

When using win+space, the audio flyout control will be called but the volume will not increase or decrease. The problem occurred when I adjusted the visibility of the top bar to "collapsed", adjusted the background opacity of the flyout control to "95%", and closed it in the system tray. It appears after the icon is displayed, but after repeatedly resetting all settings to default values for testing, I did not accurately test which operation caused it, and this is a probabilistic event. Sometimes I reset all settings to default This problem does not occur after adjusting the value or the above three places, but sometimes it still occurs. And as I said at the beginning, after uninstalling and reinstalling the application and immediately using win+space, the problem may still occur.

**Comment by ErenAKGUN2007** [comment] 2021-06-24 16:58
Duplicate of #584 and #592

**Comment by Cyberdroid1** [comment] 2021-06-25 05:12
Closing this as duplicate of #584 and #592

Thanks @ErenAKGUN2007!

**Closed by Cyberdroid1** 2021-06-25 05:12 UTC
Labels: Bug
