### ISSUE TITLE
Bug: Default menu shows when I change the volume using a trackpad gesture (precision drivers)

### ISSUE THREAD

**Issue by plt-francesco** [ModernFlyouts-Community/ModernFlyouts#394] opened 2021-01-25 22:40 UTC
The title pretty much describes itself.
**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 
Windows 10 20H2
**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-01-26 06:12
Duplicate of #4. Please check out that issue.

**Closed** 2021-01-26 16:23 UTC
Labels: Bug, Duplicate
