### ISSUE TITLE
'Syntax Error' On Colored Tray Icon Switch Label

### ISSUE THREAD

**Issue by BMT79** [ModernFlyouts-Community/ModernFlyouts#308] opened 2020-12-16 11:02 UTC
Label on colored tray icon switch appears with a syntax error in off position

**Comment by Cyberdroid1** [comment] 2020-12-16 11:13
Can you please post an image for the same?

**Comment by Samuel12321** [comment] 2020-12-21 04:21
closing as a duplicate of #178

**Closed by Samuel12321** 2020-12-21 04:21 UTC
