### ISSUE TITLE
Bug: Bro_x64 error 0xc0000005 on Windows 10 v2004

### ISSUE THREAD

**Issue by haddagaek92** [ModernFlyouts-Community/ModernFlyouts#483] opened 2021-03-03 23:07 UTC
**Describe the bug:**
The program doesn't run at all when I launch it. It was installed via Microsoft Store

**To Reproduce:**
1. Start menu
2. Search for ModernFlyouts (Preview)
3. Click to run

**Screenshots:**
![image](https://user-images.githubusercontent.com/22382156/109882733-a3269080-7c7a-11eb-850a-3ef6370db04c.png)

**OS Version:**
 - Windows 10 Version: 2004

**ModernFlyouts Version:**
 - Version: (preview)

**Comment by Samuel12321** [comment] 2021-03-04 00:32
This is a duplicate of #384 , please check before making a new issue that there isn't another identical issue.

See #384 for more information on this issue, - its caused by your anti virus. What Antivirus are you using?

**Closed by Samuel12321** 2021-03-04 00:32 UTC
Labels: Bug

**Comment by ADeltaX** [comment] 2021-03-05 09:51
Can you tell me what Antivirus are you using? I need to repro locally and try to see if I can workaround this **garbage** AV behavior. Thank you.
