### ISSUE TITLE
Feature Request : Full Battery Notification.

### ISSUE THREAD

**Issue by PrinceMayur007** [ModernFlyouts-Community/ModernFlyouts#528] opened 2021-03-28 03:16 UTC
Just like we get notification by windows default when charging gets low. Windows doesn't provide full battery charged notification. I know, there are many codes and apps, but most of time, they get error and faulty, or been removed from background services. Please find some solution on this. 
It will be definitely most appreciated feature in modern flyouts. 
Thank you!

**Comment by ShankarBUS** [comment] 2021-04-05 13:11
I will surely consider this for v1.0 😄

**Comment by ShankarBUS** [comment] 2021-04-08 10:08
Dupe of #385

**Closed by ShankarBUS** 2021-04-08 10:08 UTC
Labels: Enhancement

**Comment by PrinceMayur007** [comment] 2021-04-13 11:24
Its not duoe of #385 but some addition to it. Windows has its own feature to remind us battery low but not for battery is fully charged. And other apps have bugs or not provide exact what that is need (either it will not work in background or fail to startup at firat place)

**Comment by Cyberdroid1** [comment] 2021-04-13 12:29
#385 includes request for battery percentage warnings. Low battery, is a case of having the battery at a lower "percentage". 

Hence this issue is considered as a dupe :)
