### ISSUE TITLE
Disabling audio flyout crashes application

### ISSUE THREAD

**Issue by Zo-Bro-23** [ModernFlyouts-Community/ModernFlyouts#1167] opened 2023-02-19 08:15 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Win 11 22H2

### OS build

Dev Build 22621.1265

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Go to Settings. Click "Audio". Toggle "Enable Audio Flyout". App hangs for a second and crashes. Can reproduce consistently.

### ✔️ Expected Behavior

Audio flyout should toggle and disable.

### ❌ Actual Behavior

App crashes.

**Comment by prakharb5** [comment] 2023-02-20 18:12
Duplicate of #888

**Closed by prakharb5** 2023-02-20 18:12 UTC
Labels: Bug
