### ISSUE TITLE
Feature Request: Add Acrylic Blur Effect

### ISSUE THREAD

**Issue by Ben-BenAa** [ModernFlyouts-Community/ModernFlyouts#349] opened 2021-01-10 08:32 UTC
Acrylic backgrounds look very nice with Microsoft's new fluid design, and I though ModernFlyouts would look even better with acrylic background combined with the current background opacity setting.

**Comment by ShankarBUS** [comment] 2021-01-10 08:39
![](https://i.imgflip.com/4t9iuo.jpg)

**Comment by Samuel12321** [comment] 2021-01-10 08:45
Hi @Ben-BenAa , 
We are working on this see #66.
Closing this as a Duplicate of #66

**Closed by Samuel12321** 2021-01-10 08:45 UTC
