### ISSUE TITLE
Feature Request: Use accent color as a base color of the all flyouts

### ISSUE THREAD

**Issue by XxNatsuENDxX** [ModernFlyouts-Community/ModernFlyouts#667] opened 2021-06-16 01:45 UTC
** SORRY FOR MY LEVEL OF ENGLISH, I ONLY SPEAK SPANISH, BUT I TRY TO SPEAK IT **

**Describe the solution you'd like:**
- Is simple, only when you use the accent color, the flyouts also use this accent color, for more uniformity with the system.

**Comment by Cyberdroid1** [comment] 2021-06-16 12:27
Duplicate of #654

**Closed by Cyberdroid1** 2021-06-16 12:27 UTC
Labels: Enhancement
