### ISSUE TITLE
Bug: Application Craches when  Audio Flyouts is turned off.

### ISSUE THREAD

**Issue by HRM29** [ModernFlyouts-Community/ModernFlyouts#924] opened 2022-01-15 09:00 UTC
### ModernFlyouts Version

"0.9.3"

### Windows version

"Windows 11 21H2"

### OS build

"22000.434"

### Platform

x64

### Area(s) with issue?

Audio Flyout

### ✔️ Expected Behavior

It should not crash and simply get turned off.

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/57740829/149616135-2f96363c-7d33-4762-a065-0fd6a265773a.png)

**Comment by Cyberdroid1** [comment] 2022-01-15 15:45
Duplicate of #592

**Closed by Cyberdroid1** 2022-01-15 15:45 UTC
Labels: Bug
