### ISSUE TITLE
Bug: Modern flyouts launches but then crashes

### ISSUE THREAD

**Issue by Ast3r0ids** [ModernFlyouts-Community/ModernFlyouts#659] opened 2021-06-12 11:45 UTC
**Describe the bug:**
I launched the ModernFlyouts (Preview) app, then I look in system tray to make sure it's working, when I hover over it while media is playing the app crashes. I have also not seen it working at all yet.

**To Reproduce:**

**Screenshots:**

**OS Version:**
Windows 10 version 21H1

**ModernFlyouts Version:**
Version 0.9.3

**Comment by Cyberdroid1** [comment] 2021-06-12 14:35
Please have a look at Reliability monitor in Windows for any crash reports, and please share them here.

**Comment by Ast3r0ids** [comment] 2021-06-26 07:24
Sorry for the late reply,
I have opened the reliability monitor but I have no crash reports. Is there
anything else I can do?
Thanks.

**Comment by Cyberdroid1** [comment] 2021-08-14 16:30
Open event viewer

Then go here
![image](https://user-images.githubusercontent.com/51435948/129452970-34012363-1e25-4c11-872e-0f1c99e650e0.png)

Then look for any red stop icons in the list

Click on it, then share the screenshot of the bottom box with the details.

**Comment by baokhang147** [comment] 2021-08-30 17:13
![image](https://user-images.githubusercontent.com/89720668/131377953-ef3174be-0c1b-4f94-bf64-e36cbecc194b.png)

**Comment by Cyberdroid1** [comment] 2022-03-28 17:00
Duplicate of #642

**Closed by Cyberdroid1** 2022-03-28 17:00 UTC
Labels: Bug, Needs More Info
