### ISSUE TITLE
Brightness 0-70 not 0-100

### ISSUE THREAD

**Issue by maeuszt16** [ModernFlyouts-Community/ModernFlyouts#547] opened 2021-04-07 11:29 UTC
**Describe the bug:**
When I'm changing brightness using FN and F6 buttons i can see scale like 7, 14, 21, 28, 35, 42, 49, 56, 63, 70 and that's all. I can't  set to 100

**To Reproduce:**
1. Hold Fn button
2. Press F6 (Brightness up)
3. See error

**Screenshots:**
![image](https://user-images.githubusercontent.com/75527703/113859272-fffaf680-97a4-11eb-8341-fc7176cccc87.png)

**OS Version:**
 
![image](https://user-images.githubusercontent.com/75527703/113859395-228d0f80-97a5-11eb-87fe-2ee6d3eb5de8.png)

**ModernFlyouts Version:**
 
![image](https://user-images.githubusercontent.com/75527703/113859457-35074900-97a5-11eb-89cf-ab78b86de34d.png)

**Additional context:**
I'm using Lenovo Legion Y530 Laptop and windows 10

**Comment by Samuel12321** [comment] 2021-04-08 06:35
Duplicate of #86

**Closed by Samuel12321** 2021-04-08 06:35 UTC
Labels: Bug
