### ISSUE TITLE
Feature Request: Hide media playback seekbar

### ISSUE THREAD

**Issue by krlvm** [ModernFlyouts-Community/ModernFlyouts#628] opened 2021-05-22 17:56 UTC
**Is your feature request related to a problem? Please describe:**

I'd like to hide the media playback seekbar because the most apps I use don't support it.

**Describe the solution you'd like:**

A toggle switch in audio module settings.

**Describe alternatives you've considered:**

Not showing it when the target app don't support it, but this will cause a problem with constantly changing heights when switching between media sources.

**Additional context:**

I'm taking about this:
![image](https://user-images.githubusercontent.com/51774833/119236460-3b2c6b80-bb40-11eb-9240-dc4aae76840e.png)

**Comment by Cyberdroid1** [comment] 2021-05-22 18:04
Duplicate of #392

**Closed by Cyberdroid1** 2021-05-22 18:04 UTC
Labels: Enhancement
