### ISSUE TITLE
Doesn't works anymore on yandex for me

### ISSUE THREAD

**Issue by Jeluxe** [ModernFlyouts-Community/ModernFlyouts#682] opened 2021-06-26 16:26 UTC
it doesnt works anymore on yandex for me

**Comment by Cyberdroid1** [comment] 2021-06-26 18:12
What doesn't work? 
Please give us more details so that we can understand what's going on.

**Comment by Jeluxe** [comment] 2021-06-27 17:01
the media thumbnail of yandex browser does not show up, 
i did try with other browser and it worked, just not with yandex anymore,
though it did works at first and all of a sudden it stopped

**Comment by Cyberdroid1** [comment] 2021-06-28 04:40
Do the default windows flyouts show the media thumbnail?

**Comment by Jeluxe** [comment] 2021-06-28 07:54
I think you are right it doesn't work on neither of them.
what can i do about it?

**Comment by Cyberdroid1** [comment] 2021-07-21 06:06
Then it seems like a problem on yandex's side.

Since the problem is not on Modernflyouts' side, I will be closing this issue then.

**Closed by Cyberdroid1** 2021-07-21 06:06 UTC
