### ISSUE TITLE
Feature Request: use a swipe down gesture to bring out the volume flyout 

### ISSUE THREAD

**Issue by Saihaan06** [ModernFlyouts-Community/ModernFlyouts#616] opened 2021-05-10 02:01 UTC
**Is your feature request related to a problem? Please describe:**

the problem is that you can not use the volume flyout in tablet modes for windows tablets which have volume only on the keyboard, so no volume key next to the power button like the surface pro.
**Describe the solution you'd like:**

create a swipe down gesture to bring the flyout in to be able to use touch to change the volume.

**Comment by Samuel12321** [comment] 2021-05-11 06:19
Duplicate of #497

**Closed by Samuel12321** 2021-05-11 06:19 UTC
Labels: Enhancement, UI/UX

**Comment by Cyberdroid1** [comment] 2021-05-11 11:20
Why did he open the same issue again? 😂
