### ISSUE TITLE
Glitches flyout

### ISSUE THREAD

**Issue by rami-shalhoub** [ModernFlyouts-Community/ModernFlyouts#1313] opened 2024-06-23 19:21 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 23H2

### OS build

22631.3737

### Platform

x86

### Area(s) with issue?

Audio Tray Flyout

### Steps to reproduce

when i choose the default flyout as the modern flyout 
![Screenshot 2024-06-23 211230](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/125956297/f1fdeeeb-f519-4d6d-947e-526b23916db5)
 

### ✔️ Expected Behavior

to appear the modern flyout only

### ❌ Actual Behavior

the original windows and the modern appear together

**Comment by prakharb5** [comment] 2024-07-22 19:23
Update to the latest beta available on github.
Duplicate of #920

**Closed by prakharb5** 2024-07-22 19:23 UTC
Labels: Bug
