### ISSUE TITLE
Bug: Media flyout not appearing automatically

### ISSUE THREAD

**Issue by felipeqq2** [ModernFlyouts-Community/ModernFlyouts#502] opened 2021-03-13 00:26 UTC
**Describe the bug:**
When I play some music at Spotify, the Flyout doesn't automatically changes to show the music and the controls. Actually, it'll just show this info when I open the settings and I deactivate and reactivate "Activate audio flyout". When I stop listening to music, the media controls will continue to appear, but with no info. I have to, again, restart the audio flyout at settings. It's like the flyout only detects wheter to activate or not the media flyout when it starts.

**To Reproduce:**
1. Start Spotify (downloaded at the Microsoft Store)
2. Try to decrease the volume, so you can see the Flyout
3. No media will be shown
4. Toggle 2x the key "activate audio flyout" (rough translation from Portuguese)
5. The media will appear
6. Close the Spotify app
7. The media window will continue there, but with no info

**Screenshots:**
Before reactivating:
![before reactivate](https://user-images.githubusercontent.com/71830138/111011515-752b0580-8378-11eb-9b52-76bc81d3b3e4.png)
After reactivating and stopping the music:
![image](https://user-images.githubusercontent.com/71830138/111011676-ecf93000-8378-11eb-8158-64e0d1b5c2e9.png)

**OS Version:**
 - Windows 10 Version: W10 HOME v20H2

**ModernFlyouts Version:**
 - Version: v0.9.1

**Comment by Samuel12321** [comment] 2021-03-13 08:11
@felipeqq2 does this still occur with 0.9.1 ?

**Comment by felipeqq2** [comment] 2021-03-13 13:50
> @felipeqq2 does this still occur with 0.9.1 ?

Yes, it does

**Comment by felipeqq2** [comment] 2021-03-14 14:23
This is happening with everything, not only Spotify. Youtube has the same problem, for instance

**Comment by fabio-henriques** [comment] 2021-03-14 15:57
This happening to me too

**Comment by ADeltaX** [comment] 2021-03-14 21:17
What is your OS version (for example 19043.xxx)?

**Comment by felipeqq2** [comment] 2021-03-14 22:09
> What is your OS version (for example 19043.xxx)?

19042.867

**Comment by TheFlash200406** [comment] 2021-04-05 15:09
Me too

**Comment by TheFlash200406** [comment] 2021-04-05 15:19
Did you solve it ??

**Comment by felipeqq2** [comment] 2021-04-05 15:22
> Did you solve it ??

Me? nope

@ADeltaX

**Comment by fishears** [comment] 2021-04-07 14:05
Same thing happening to me too. ModernFlyouts version 0.9.1.0, Windows 10 Home 20H2 Build 19042.906
If I toggle the audio flyout as suggested in the issue then the media information appears but it stays visible even after I close the media player - the information goes blank but the box stays.

**Comment by SebaldJ** [comment] 2021-04-14 18:14
I unfortunately have exactly the same problem, Windows 21H1, Build 10.0.19043.928, v0.9.1.0 😔

**Comment by LukoFoks** [comment] 2021-06-11 15:40
Absolutely agree. Installed today and the flyout is not reloading. I would have to restart the app all the time. Hope this will be fixed soon.

**Comment by felipeqq2** [comment] 2021-06-15 12:31
It's now working properly for me at v0.9.3

**Comment by Cyberdroid1** [comment] 2021-06-15 15:31
@fishears @SebaldJ @TheFlash200406 
can you all also confirm if it is working for you too now?

**Comment by TheFlash200406** [comment] 2021-06-15 15:33
Yes, Now for me, It is working correctly

**Comment by fishears** [comment] 2021-06-15 16:03
Yes. I can confirm this seems to be fixed but not by a version change of ModernFlyouts - I've been on the latest build for some time - I think it must be a Windows update that has made it work. Great news however it happened. The only thing I can't do though is control playback when Spotify is playing. The forward, back and pause buttons are there but don't work...

**Comment by felipeqq2** [comment] 2021-06-15 16:23
> The only thing I can't do though is control playback when Spotify is playing. The forward, back and pause buttons are there but don't work...

For me, it works normally.

**Closed** 2021-08-23 16:21 UTC
Labels: Bug, Media
