### ISSUE TITLE
Feature Request: AutoHotKey support (Audio Flyout)

### ISSUE THREAD

**Issue by Minnona** [ModernFlyouts-Community/ModernFlyouts#229] opened 2020-11-18 06:25 UTC
Hey, I recently got myself a new keyboard and I made a few shortcuts for media settings using AutoHotKey. Using media controls via AHK shows default W10 flyouts.

**Comment by Samuel12321** [comment] 2020-11-18 06:28
Hi, thanks for reporting this. This is a duplicate of #222. 
Please see #222 for follow-up on this issue.

**Comment by ShankarBUS** [comment] 2021-01-10 17:21
@elenmerbau, could you please share the AHK script?

**Comment by elenmerbau** [comment] 2021-01-12 18:35
@ShankarBUS sorry for late reply.
`; AutoHotkey Media Keys
^!Space::Send       {Media_Play_Pause}
^!Left::Send        {Media_Prev}
^!Right::Send       {Media_Next}
^!NumpadMult::Send  {Volume_Mute}
^!Up::Send   {Volume_Up}
^!Down::Send   {Volume_Down}`

**Comment by ShankarBUS** [comment] 2021-01-12 18:49
Thanks! I'll look into it.

In the mean time could you try Microsoft PowerToys?
It has a module called Keyboard Manager which could solve this problem for you.

**Comment by elenmerbau** [comment] 2021-01-12 19:37
I tried powertoys, but it's got its own problems. First volumeup keybind shows default W10 popup, after that ModernFlyouts popup kicks in. Can reproduce it as soon as popup disappears, tried to reboot as well.

**Comment by Cyberdroid1** [comment] 2021-01-12 21:09
> I tried powertoys, but it's got its own problems. First volumeup keybind shows default W10 popup, after that ModernFlyouts popup kicks in. Can reproduce it as soon as popup disappears, tried to reboot as well.

Facing same issue 🙁.

**Comment by Samuel12321** [comment] 2022-01-08 09:13
Duplicate of #468 will be fixed with 0.11

**Closed by Samuel12321** 2022-01-08 09:13 UTC
Labels: Enhancement
