### ISSUE TITLE
Bug: The tab representing the media file being played remains there as long as the file is not being played.

### ISSUE THREAD

**Issue by oveja10o01** [ModernFlyouts-Community/ModernFlyouts#909] opened 2021-12-29 11:57 UTC
**Describe the bug:**
 The tab representing the media file being played remains there as long as the file is not being played.

**To Reproduce:**

<--
--> 1. Go to any multimedia file
--> 2. Click on one of the volume keys
--> 3. See the tab that represents
--> 4. Close the multimedia file 
--> 5. See the error
--> The tab stills on the screen.

**Screenshots:**
 
![image](https://user-images.githubusercontent.com/96797211/147659582-03e9ab06-bf09-4eaa-89b3-6e025d392e6b.png)

**OS Version:**
 - Windows Version:  Windows 10 Home 
**ModernFlyouts Version:**
 - Version:  0.9.3.0 

**Additional context:**
 Apart from reporting the bug, I would like to take this opportunity to congratulate you for the very detailed work you did to improve the Windows volume tab. Thank you and I hope this little problem will be solved.

**Comment by arnavbhate** [comment] 2021-12-30 14:16
Duplicate of #710

**Comment by oveja10o01** [comment] 2022-01-08 10:05
Sorry @arnavbhate, I don't understand. What I should have to do now?

**Comment by Samuel12321** [comment] 2022-01-08 10:07
Duplicate of #710 will be fixed in a future update

**Closed by Samuel12321** 2022-01-08 10:07 UTC
Labels: Bug

**Comment by oveja10o01** [comment] 2022-01-08 10:09
Oh, then, thanks @Samuel12321!
