### ISSUE TITLE
Bug: Audio Flyout appears when using shortcuts to switch input methods

### ISSUE THREAD

**Issue by choking-chips** [ModernFlyouts-Community/ModernFlyouts#899] opened 2021-12-21 14:51 UTC
**Describe the bug:**

Press `Alt` + `Shift` or `Windows` + `Space`, and then Audio Flyout appears.

**To Reproduce:**

1. Boot Windows normally with ModernFlyouts starting up automatically
2. Just press `Alt` + `Shift` or `Windows` + `Space`
3. See error

**Screenshots:**

Recorded a gif to show how this happens. To make it easier for me to record, Flyout is placed in the top right corner of the screen.

![3](https://user-images.githubusercontent.com/52846426/146947428-2730496d-da27-4454-a930-556c01139f9e.gif)

**OS Version:**
 - Windows Version:  Windows 10 20H2 (build 19042.1415)

**ModernFlyouts Version:**
 - Version: 0.9.3.0 from Microsoft Store

**Additional context:**

- The bug disappears after I change the brightness by shortcut
- I've tried my best to express this bug in English, but it has been of some difficulty. Anyway I still would like to say, ModernFlyouts is really a nice application :)

**Comment by Cyberdroid1** [comment] 2021-12-22 04:22
Thanks for the report! We have implemented a fix which should come in a future release (or you can try the v0.10 beta if you would like to)

Duplicate of #584

**Closed** 2021-12-22 04:22 UTC
Labels: Bug
