### ISSUE TITLE
Latest version can't run properly in win11.

### ISSUE THREAD

**Issue by LiuYiLin-CA** [ModernFlyouts-Community/ModernFlyouts#1094] opened 2022-09-19 05:36 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 21H2

### OS build

22000.978

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

After installing the new version of ModernFlyouts in Microsoft Store or Github releases, and launch the software from the Start menu, it seems can't start properly. I've tried 0.9.3 (Latest) and 0.9.97 (0.10.0-beta.1 pre-release), and both are unable to start. However, I found that someone said 0.9.0 may start properly ,and it does. 

### ❌ Actual Behavior

 0.9.3 (Latest) and 0.9.97 (0.10.0-beta.1 pre-release) both are unable to start. 

### Additional Context

I run ModernFlyouts in laptop(Thinkbook 16 G4+ IAP Lenovo).

**Comment by hdadhich01** [comment] 2022-09-25 00:42
Experiencing the same issue with Windows 11 Pro 21H2 22000.978. This is discussed further in #1078.

**Comment by Samuel12321** [comment] 2022-10-02 02:46
Duplicate of #1078

**Closed by Samuel12321** 2022-10-02 02:46 UTC
Labels: Bug
