### ISSUE TITLE
Feature Request: Support Windows 10 Wheel

### ISSUE THREAD

**Issue by thewan056** [ModernFlyouts-Community/ModernFlyouts#577] opened 2021-04-21 07:18 UTC
**Is your feature request related to a problem? Please describe:**
When using the Wheel feature for Windows 10, the default Windows 10 flyout is used for volume adjustment.

**Describe the solution you'd like:**
Is it possible for ModernFlyouts to replace this flyout too?

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-04-21 08:43
What is the wheel feature in windows? Can you share some more info on that?

Meanwhile, do try the new beta release in the release section of the repo.

**Comment by thewan056** [comment] 2021-04-21 08:59
I'm referring to the functionality originally introduced by the Surface Dial. There are a few manufacturers now coming out with alternatives which work with this feature. I recently bought a keyboard that supports it. This is my screenshot of the setting below:

![Screenshot 2021-04-21 165219](https://user-images.githubusercontent.com/24851051/115525756-f5bb1b00-a2c1-11eb-95f2-ff65772ab07c.jpg)

When I use this Wheel to set my volume, it uses the default volume flyout.  I would like to use Modern Flyouts for consistency if possible.

[Review on the Surface Dial](https://www.windowscentral.com/surface-dial-review) for those not familiar with it.

**Comment by Cyberdroid1** [comment] 2021-04-21 12:02
Install this beta and let us know if you still get the bug

https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.9.X-beta.1

**Comment by thewan056** [comment] 2021-04-21 12:52
The beta works perfectly. Thanks.

**Comment by Cyberdroid1** [comment] 2021-04-21 16:23
Ok thanks! Closing this issue then as a duplicate of #4.

**Closed by Cyberdroid1** 2021-04-21 16:23 UTC
Labels: Enhancement
