### ISSUE TITLE
Bug: default Windows flyout when changing volume by touchpad

### ISSUE THREAD

**Issue by De-Os** [ModernFlyouts-Community/ModernFlyouts#326] opened 2020-12-28 09:27 UTC
**Describe the bug:**
Default flyout appears when changing volume by touchpad gestures.
Also, if use volume keys first and then use gestures, then it works good

**To Reproduce:**
1. Enable "Change audio and volume" in touchpad gestures
![Screenshot (7)](https://user-images.githubusercontent.com/37545373/103204150-b8dcaa00-4907-11eb-807d-a6bdda004915.png)
2. Try to use it

**Screencapture:**
https://user-images.githubusercontent.com/37545373/103204188-ce51d400-4907-11eb-8082-38b1227bbe70.mp4

**OS Version:**
 - Windows 10 20H2 (build 19042.685)

**ModernFlyouts Version:**
 - 0.8.5.0

**Comment by Cyberdroid1** [comment] 2020-12-28 12:05
Duplicate of #4. Please check that issue.

**Closed** 2020-12-28 12:05 UTC
Labels: Bug, Duplicate
