### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Marcoky** [ModernFlyouts-Community/ModernFlyouts#999] opened 2022-04-19 14:28 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Audio Tray Flyout, System tray

### Steps to reproduce

cuando se inicia el ordenador
(when the computer starts)

### ✔️ Expected Behavior

que salga el control flotante de musica
(bring out the music flyout)

### ❌ Actual Behavior

no sale el control flotante cuando le doy a parar musica
(The floating control does not come out when I give it to stop music)

### Other Software

Chome,Spotify

### Additional Context

me gustaria ponerlo como esta en windows 
(I would like to put it as it is in windows)

**Comment by Samuel12321** [comment] 2022-04-25 02:57
Duplicate of #610

**Closed by Samuel12321** 2022-04-25 02:57 UTC
Labels: Bug
