### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by meowmeowd** [ModernFlyouts-Community/ModernFlyouts#987] opened 2022-03-29 21:00 UTC
### ModernFlyouts Version

"0.9.3.0

### Windows version

"Windows 11 22H2

### OS build

"22581.1"

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

![image](https://user-images.githubusercontent.com/86579067/160706073-5be88541-e532-43b1-854a-a48b1c9f1582.png)

### ✔️ Expected Behavior

Expecting the modern flyout to show instead of the Windows one.

### ❌ Actual Behavior

Both the modern flyout and Windows flyout showed up at the same time

**Comment by Cyberdroid1** [comment] 2022-03-30 03:33
Duplicate of #920

**Closed by Cyberdroid1** 2022-03-30 03:33 UTC
Labels: Bug
