### ISSUE TITLE
Bug: Audio Flyout appearance after switching keyboard layout

### ISSUE THREAD

**Issue by flackseven** [ModernFlyouts-Community/ModernFlyouts#884] opened 2021-11-29 10:39 UTC
**Describe the bug:**
When you change the keyboard layout, the Audio Flyout appears.  The bug may disappear over time, but after restarting Windows repeats again.

1. Click on any text input.
2. Change keyboard layout (Alt+Shift or Win+Space)
3. See Audio Flyout

**Screenshots:**

![flyout bug](https://user-images.githubusercontent.com/78412508/143852458-e36942a9-e133-4e1e-9c80-43266fae4ccb.gif)

**OS Version:**
 - Windows Version: Windows 10 21H2 OS Build 19044.1387

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

**Comment by Chint355** [comment] 2021-11-30 05:53
I think this issue duplicated #584

**Comment by Cyberdroid1** [comment] 2021-11-30 11:13
Duplicate of #584

**Closed** 2021-11-30 11:14 UTC
Labels: Bug, Duplicate
