### ISSUE TITLE
Timeline info suggestion

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#114] opened 2020-10-17 04:05 UTC
> The Time Line info bar should always show in panel, instead of click button to see the progress!

Store review, perhaps this could be a toggle setting

**Comment by ShankarBUS** [comment] 2020-10-17 04:25
Nice suggestion.

But the layout would be different from what it is now.

We may expect some issues.

I'll think of an efficient way to do this

**Comment by Cyberdroid1** [comment] 2020-12-23 08:43
Isn't this counted as duplicate of #97?

**Comment by WinstonSepruko** [comment] 2020-12-23 08:44
Not necessarily, but they can definitely be bundled together.

**Comment by ShankarBUS** [comment] 2020-12-23 08:47
They're mutually exclusive.

That one's for asking support.

This one's for UX.

**Comment by Cyberdroid1** [comment] 2020-12-23 10:12
Ah I see.

**Comment by ShankarBUS** [comment] 2021-01-11 15:06
Done

**Closed** 2021-01-18 21:05 UTC
Labels: Enhancement, MS Store Feedback
