### ISSUE TITLE
app not disabling default flyouts

### ISSUE THREAD

**Issue by glitch128** [ModernFlyouts-Community/ModernFlyouts#1110] opened 2022-09-30 01:26 UTC
### ModernFlyouts Version

"0.9.3.0"

### Windows version

"Windows 11 22H2"

### OS build

"22622.601"

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

increase/decrease volume, pause/play using media keys increase/decrease brightness, anything that would trigger both windows default and modern flyouts

### ✔️ Expected Behavior

it would hide the default flyout

### ❌ Actual Behavior

both flyouts appeared

**Comment by SoNotMC** [comment] 2022-10-01 09:38
Yup all due to the new update :(

**Comment by Firsh** [comment] 2022-10-02 02:03
Is there a setting in Windows to disable it by any chance?

**Comment by Samuel12321** [comment] 2022-10-02 02:20
Hi, 
Thanks for reporting this. We are aware of the problem and plan to fix this in the next update 0.11.
@Firsh unfortunately windows doesn't have any settings to disable it or alter it.
Closing as duplicate of #920

**Closed by Samuel12321** 2022-10-02 02:20 UTC
Labels: Bug
