### ISSUE TITLE
How to set default display monitor?

### ISSUE THREAD

**Issue by coheneli98** [ModernFlyouts-Community/ModernFlyouts#441] opened 2021-02-14 12:08 UTC
Hi, how are you? I use Modern Flyouts on my laptop which I often connect to my monitor. Whenever I use my monitor, I like Modern Flyouts to be displayed on my monitor and not on my laptop screen, but whenever I disconnect my laptop to my monitor it goes back to being displayed on my laptop, so whenever I plug it into my monitor I need to set it to be displayed on my monitor, not my laptop, so each time I use my monitor I need to change the settings. Is there any way around this? Is there a way to set it to always be displayed on another screen when connected to one?

**Comment by Cyberdroid1** [comment] 2021-02-18 05:55
Closing as duplicate of issue #423. Please add your opinion in that issue :)

**Closed** 2021-02-18 05:56 UTC
Labels: Duplicate, Enhancement
