### ISSUE TITLE
Bug: Modern Flyout does not close automatically

### ISSUE THREAD

**Issue by mtratchet16** [ModernFlyouts-Community/ModernFlyouts#576] opened 2021-04-19 15:30 UTC
**Describe the bug:**
The flyout does not automatically close. I made sure that the settings have it automatically close after a certain amount of time (I set it to 2,000 ms), but it still stays up--whether I switch windows, click outside of the flyout, or wait the 2 seconds. To get it to go away, I have to physically close it.

**To Reproduce:**
1. Adjust volume.

**Screenshots:**
N/A

**OS Version:**
 - Windows 10 Version: Windows 10 Pro 21H1

**ModernFlyouts Version:**
 - Version: v0.9.1.0

**Additional context:**
I searched for the same issue before posting. While I found other people with the issue, I didn't see any answers to the question.

**Comment by Cyberdroid1** [comment] 2021-04-21 08:53
Duplicate of #563

**Closed by Cyberdroid1** 2021-04-21 08:53 UTC
Labels: Bug
