### ISSUE TITLE
ModernFlyout isn't hiding/disabling system volume and display popup bar

### ISSUE THREAD

**Issue by Vai007** [ModernFlyouts-Community/ModernFlyouts#1304] opened 2024-05-17 18:03 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 23H2

### Steps to reproduce

When trying to change volume or brightness using laptop's keyboard shortcut somehow system volume bar is also showing along with modernFlout.
![Screenshot (1)](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/71776225/4192a0de-b8d8-41f0-9a0c-5820cfa11be3)

### ❌ Actual Behavior

System's volume bar should be hiden/disabled.

**Comment by BrianG61UK** [comment] 2024-06-13 22:41
Same bug present on Windows 11 23H2 laptop with ModernFlyouts 0.9.3.0.

**Comment by kurtbahartr** [comment] 2024-06-19 17:03
I can confirm on Windows 11 21HJ2 with ModernFlyouts v0.10.0-beta.4 - Don't ask me why I use that specific Windows 11 feature update. :D

![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/168406273/3eceeb32-d9b8-4481-8e3f-9f0ba5b91c64)
> PrntScr mapping didn't change as I didn't restart my system after enabling the setting that remaps it to Snipping Tool, which resulted in both of my displays being captured. My bad!

**Comment by manstheram** [comment] 2024-06-19 20:05
However, the other people are using 0.9.3 @kurtbahartr 
Your issue is a little bit more confusing as it should've been fixed in that version. Could you tell me the exact Windows build you are on using winver?

**Comment by kurtbahartr** [comment] 2024-06-19 20:48
> However, the other people are using 0.9.3 @kurtbahartr Your issue is a little bit more confusing as it should've been fixed in that version. Could you tell me the exact Windows build you are on using winver?

@manstheram,

Sure thing. The build number is `22000.3019`, the last build released for 21H2 before EoS. I also tried version 0.9.3 which didn't even launch let alone helping debugging it.

**Comment by kurtbahartr** [comment] 2024-06-19 22:40
I just tested it out on Windows 10 22H2 build `19045.4529` too and it seems to be working just fine so I assume this has to do with the way system flyouts are now handled on later builds of Windows 11.

![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/168406273/dd45eb26-8ec0-49ab-87e8-eacec05c6cbd)

**Comment by manstheram** [comment] 2024-06-20 17:08
I set it to swap the method used for changing the volume bar after 22000 (Windows 11 changed it), so maybe the fact you are directly on 22000 is what's causing the issue. I am also able to replicate this on a virtual machine at 22000.318 so I will try to figure out why it's not working. Even the check I used works too so it's a bit confusing.

**Comment by kurtbahartr** [comment] 2024-06-20 17:26
> I set it to swap the method used for changing the volume bar after 22000 (Windows 11 changed it), so maybe the fact you are directly on 22000 is what's causing the issue. I am also able to replicate this on a virtual machine at 22000.318 so I will try to figure out why it's not working. Even the check I used works too so it's a bit confusing.
> 
> @kurtbahartr Ah, I realised the issue, Windows 11 still uses the same volume bar from Win10 until exactly that version, I messed up the version I was checking. It changed in 22H2, not 21H2..

@manstheram,

Yep, just as I assumed. 22H2 brings lots of visual revamps throughout Windows 11 along with lots of bugs and glitches. One of them, however, is quite irritating to the point I ended up opting for 21H2 even though 24H2 is around the corner already. I don't mind having the old volume bar as long as ModernFlyouts is a thing. :)

**Comment by manstheram** [comment] 2024-06-20 18:07
@kurtbahartr I released a build that should fix that error on my fork [ModernFlyouts Fork](https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4). You can see if that fixes it.

**Comment by kurtbahartr** [comment] 2024-06-20 18:21
@manstheram,

Alrighty. I just sent the tab with the link you provided to the impacted machine over Chrome. I'll check it out when my brother is done with his gaming session. 😅

P.S I know I could've just sent the files over SMB to use less bandwidth as I'm typing this on the laptop with Windows 10 22H2 but I can't connect to the Windows 11 laptop over local network for some reason - I do see it in Network category in Explorer but trying to connect to it returns a "Can't connect to DESKTOP-1234567" with the detail being "Network path could not be found".

**Comment by kurtbahartr** [comment] 2024-06-21 13:22
@manstheram,

It works just fine when the target laptop is logged into the system with my own user account. I'll dig deeper into it at a later time. I'll be focusing on helping troubleshoot and check for the bug I face here on ModernFlyouts as soon as I can - My brother seems to want to keep that laptop of mine to himself all day long, or potentially even longer, just because it's a gaming laptop and he can game with his friends on it. 🙄

**Comment by kurtbahartr** [comment] 2024-06-21 14:29
@manstheram,

Update: I just tested it out and things work just as expected!

![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/168406273/199a5a64-92b0-44b3-8109-7337812de0a7)

**Comment by Samuel12321** [comment] 2024-11-17 02:47
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Closed by Samuel12321** 2024-11-17 02:47 UTC
Labels: Bug
