### ISSUE TITLE
Bug: Not showing modern flyout if not used for some minutes

### ISSUE THREAD

**Issue by tjhecker** [ModernFlyouts-Community/ModernFlyouts#770] opened 2021-08-24 05:44 UTC
![Screenshot (159)](https://user-images.githubusercontent.com/89440583/130560953-d33f0318-79e1-4ae4-9335-b6108d5fd98d.png)

Describe the bug:*It doesn't showing modern flyout if it is used after some time(10-15 minutes)*

Screenshots:*given*

OS Version:*Windows 10 20H1*

Modern Flyouts Version:*0.9.3*

_I am new at GitHub so if there is any mistakes please ignore it_

**Comment by Cyberdroid1** [comment] 2021-08-24 11:37
Is only the media flyout not displaying, or are all the flyouts gone? Try pressing the caps-lock/num-lock key.

**Comment by tjhecker** [comment] 2021-09-16 04:25
1

**Comment by tjhecker** [comment] 2021-09-16 04:30
only the media flyout not displaying and if I press caps-lock/num-lock key it is displaying and if i press caps-lock then it is showing media flyout then it is working.

**Comment by Cyberdroid1** [comment] 2021-09-20 19:37
Closing as duplicate of #710

**Closed by Cyberdroid1** 2021-09-20 19:37 UTC
Labels: Bug
