### ISSUE TITLE
Bug:Flyout doesnt auto-hide

### ISSUE THREAD

**Issue by da-r-k** [ModernFlyouts-Community/ModernFlyouts#889] opened 2021-12-10 04:41 UTC
I tried changing the flyout timeout to 100ms... Still it is visible always and takes up a lot of space on my screen

**Comment by lxdklp** [comment] 2021-12-24 15:37
遇到相同的问题

**Comment by Samuel12321** [comment] 2021-12-26 04:57
Duplicate of #464

**Closed by Samuel12321** 2021-12-26 04:57 UTC
Labels: Bug
