### ISSUE TITLE
HDMI (as Main Display) Bug

### ISSUE THREAD

**Issue by Cabus1982** [ModernFlyouts-Community/ModernFlyouts#1287] opened 2024-03-18 06:09 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro 22H2

### OS build

19045.4170

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Media Flyout, Lock keys Flyout

### Steps to reproduce

Disconnecting and reconnecting my main display (HDMI) causes the program to become stuck on the secondary display (Notebook).

### ✔️ Expected Behavior

I want the program to keep track of the settings and display them on the main display.

### ❌ Actual Behavior

Does not appear again in the HDMI after connecting it.

### Additional Context

Restarting the program is the only way to “fix it” 🙄

**Comment by prakharb5** [comment] 2024-07-22 19:20
Duplicate of #663 and #736

**Closed by prakharb5** 2024-07-22 19:20 UTC
Labels: Bug
