### ISSUE TITLE
Bug: Flyouts can't recognize Spotify when switching from Chrome audio to Spotify

### ISSUE THREAD

**Issue by Daydream404** [ModernFlyouts-Community/ModernFlyouts#898] opened 2021-12-19 11:28 UTC
**Describe the bug:**
When I listen to music on Youtube in Google Chrome I can easily skip/pause etc. music. But when I exit Chrome and switch to spotify music I can't skip/stop music because It is trying to stop chrome music.

**To Reproduce:**
Play music on Chrome
Exit Chrome
Open Spotify
Try to pause music.

**Screenshots:**

Normal working flyout in Chrome: 
![image](https://user-images.githubusercontent.com/46535297/146673200-0a09ec7a-193b-4143-b8f4-8b7915d39df6.png)

Now I closed Chrome and turned on Spotify app(normal Win App not from Microsoft store):
![image](https://user-images.githubusercontent.com/46535297/146673231-96c6177d-d47e-4b5d-b746-1cd89355b3fc.png)
And you can see that it doesn't recognize that Spotify is opened

**OS Version:**
 - Windows Version: Win 10 Home 21H1

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Comment by arnavbhate** [comment] 2021-12-23 13:16
Duplicate of #710

**Closed** 2021-12-23 13:20 UTC
Labels: Bug
