### ISSUE TITLE
Bug: When I change the input method, the ui box will pop up

### ISSUE THREAD

**Issue by iosyyy** [ModernFlyouts-Community/ModernFlyouts#918] opened 2022-01-09 02:17 UTC
### ModernFlyouts Version

0.10

### Windows version

Windows 11 Insider Preview 

### OS build

22526.1000

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Using win + space to switch the input method will cause this phenomenon to occur

### ❌ Actual Behavior

Display ui in inappropriate places

**Comment by Samuel12321** [comment] 2022-01-09 02:18
duplicate of another issue, this is a known bug and will be fixed in the 0.11 release

**Closed by Samuel12321** 2022-01-09 02:18 UTC
Labels: Bug
