### ISSUE TITLE
Bug: Layout repeatly goes to a wrong screen

### ISSUE THREAD

**Issue by Blizzardfall** [ModernFlyouts-Community/ModernFlyouts#958] opened 2022-02-23 13:22 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### OS build

220000.527

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1, Have two screens or more
2. The screens turn off when afk due to power setting
3. Use the PC again

### ✔️ Expected Behavior

The layout should be appear on the screen that I've set before.

### ❌ Actual Behavior

The layout appears on a wrong screen, having to change it again in the settings.
In my case, The layout resets to screen 2 when I've set it to screen 1 (main screen)
![image](https://user-images.githubusercontent.com/19769002/155326834-34757d31-eabf-4a67-8b25-9dd610df8c34.png)

### Additional Context

Both monitors are connected via DP port, using Nvidia GPU.

**Comment by Samuel12321** [comment] 2022-03-27 00:14
Duplicate of #736

**Closed by Samuel12321** 2022-03-27 00:14 UTC
Labels: Bug
