### ISSUE TITLE
Feature Request: Volume not using keyboard keys

### ISSUE THREAD

**Issue by mtratchet16** [ModernFlyouts-Community/ModernFlyouts#575] opened 2021-04-19 15:20 UTC
**Is your feature request related to a problem? Please describe:**
When I adjust the volume via my Bluetooth Device (Surface Headphones), it uses the default volume flyout. It does the same thing when adjusting via multi-touch gestures (Three fingers up/down is how mine is customized).

**Describe the solution you'd like:**
Making the modern flyout compatible with adjustments systemwide to ensure consistency.

**Describe alternatives you've considered:**
N/A

**Additional context:**
If I adjust the volume once the modern flyout is up using my headphones or touchpad, it will continue using the modern flyout. If I use my headphones/touchpad to adjust when the modern flyout is not already up, it uses the system's default.

**Comment by Cyberdroid1** [comment] 2021-04-19 18:36
Dupe of #4.

**Closed** 2021-04-19 18:36 UTC
Labels: Duplicate, Enhancement
