### ISSUE TITLE
Bug: Stuck on a Song

### ISSUE THREAD

**Issue by HypedDomi** [ModernFlyouts-Community/ModernFlyouts#880] opened 2021-11-23 09:41 UTC
**Describe the bug:**
Sometimes ModernFlyouts it stuck on an Song. The Play/Pause button is triggered, but does not pause/start the song and in the flyout is a song that was played a few minutes ago. Otherwise the flyout works normally. Appears and goes away after the set time.

**OS Version:**
 - Windows Version: Windows 11, 21H2

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**
So far I have only noticed this while playing VALORANT, but don't think that it is VALORANT. I use the Spotify app from the Spotify site, but also had the same problems with the store version

**Comment by Cyberdroid1** [comment] 2021-11-23 11:15
Duplicate of #492

**Closed by Cyberdroid1** 2021-11-23 11:15 UTC
Labels: Bug
