### ISSUE TITLE
Bug: Using volume buttons on a Bluetooth speaker uses default Windows 10 flyout as opposed to Modernflyouts.

### ISSUE THREAD

**Issue by Vodcat** [ModernFlyouts-Community/ModernFlyouts#304] opened 2020-12-14 18:44 UTC
**Describe the bug:**
Using the volume up and volume down buttons on a bluetooth speaker shows default volume panel.

**To Reproduce:**
1. Connect a speaker via bluetooth.
2. Press volume up or volume down on the speaker.

**Screenshots:**
![Screenshot 2020-12-14 193949](https://user-images.githubusercontent.com/76006707/102121675-a319b000-3e44-11eb-9c42-825435a47daa.png)
![Screenshot 2020-12-14 194144](https://user-images.githubusercontent.com/76006707/102121688-a7de6400-3e44-11eb-94fe-647654b93209.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.4.0

**Additional context:**

**Comment by Samuel12321** [comment] 2020-12-14 20:42
Hi thanks for reporting this issue.
We are aware of this see #4.
Closing as a Duplicate of #4

**Closed by Samuel12321** 2020-12-14 20:42 UTC
Labels: bug
