### ISSUE TITLE
Feature Request: Please have the app remember window positions on a per screen layout basis. If I have a second monitor attached I want it there, if not I want it on the primary screen. It should remember window position on a per layout basis.

### ISSUE THREAD

**Issue by Ry5ter** [ModernFlyouts-Community/ModernFlyouts#512] opened 2021-03-18 00:00 UTC
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Samuel12321** [comment] 2021-03-18 00:24
Duplicate of #423

**Closed** 2021-03-18 00:24 UTC
Labels: Duplicate
