### ISSUE TITLE
Feature Request: Pop-up when a new song starts playing as an option that can be toggeled on and off 

### ISSUE THREAD

**Issue by FocalFactor** [ModernFlyouts-Community/ModernFlyouts#1056] opened 2022-07-24 00:15 UTC
### Description of the new feature / enhancement

When a song ends and a new one begins the overlay will flash for a certain amount of time (user-specified like the fade-out) to have a visual indication of what song is playing. Ideally this would have a toggle so that you can turn it on and off whenever you want. (First time using github apologies if this is not in the right place or formatted incorrectly!)

### Scenario when this would be used?

Passively / always on as the user works on their computer

**Comment by Cyberdroid1** [comment] 2022-08-19 17:06
Duplicate of #78

**Closed by Cyberdroid1** 2022-08-19 17:06 UTC
Labels: Enhancement
