### ISSUE TITLE
Feature Request: Flyout for Trackpad Activation

### ISSUE THREAD

**Issue by nott74** [ModernFlyouts-Community/ModernFlyouts#527] opened 2021-03-27 21:58 UTC
So I use a laptop, and it does have a program that manages the flyouts for num lock, caps lock, trackpad, etc. 

Since I now exclusively use you app for all flyouts, I was wondering of you could add the one that is missing for me, the Trackpad Flyout. It doesn't need to be nothing fancy, just similar to the other flyouts.

Thank you for your attention! Hope you can do it!

**Comment by Samuel12321** [comment] 2021-03-27 22:07
I didn't know such a flyout existed. Is it for a laptop where you can disable the trackpad?
What model laptop is it?

**Comment by nott74** [comment] 2021-03-29 08:34
Yea it's for a laptop. I use an Acer Aspire 7 (A715-72g).

**Comment by Cyberdroid1** [comment] 2021-04-04 04:30
Dupe of #268

**Closed** 2021-04-04 04:30 UTC
Labels: Duplicate, Enhancement, Wontfix

**Comment by Samuel12321** [comment] 2021-04-04 08:17
@Cyberdroid1 , the reason i didn't close this one (although you are right it is a duplicate); is because the report said another app made by the oem could display this suggesting that the enabled/ disabled state must be passed on to the os somehow?
