### ISSUE TITLE
Enabling Modern Flyout does not disable the default ones

### ISSUE THREAD

**Issue by seanmamasde** [ModernFlyouts-Community/ModernFlyouts#1037] opened 2022-06-19 04:05 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Home

### OS build

22621.160 

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

ModernFlyouts set to enabled under General -> Default Flyout section does not disable default Windows flyouts.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/85484530/174465179-505114d0-718a-49ca-bc7b-d33581e6b10b.png">

### ✔️ Expected Behavior

There should be ModernFlyouts only, not both.

### ❌ Actual Behavior

Both are showing up simultaneously.

### Other Software

can reproduce even with: 
1. no apps opened 
2. selective startup (a line on "load system services" (only Microsoft services are not disabled) option and unticking the box "load startup items")

### Additional Context

1. Tried uninstalling it and reinstalling it again, does not help.
2. [Similar issue raised previously](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/36). It's under Windows 10 so it's been a while since it's fixed (perhaps)? Maybe the way Windows 11 do volume and brightness pop-ups are different? I am not sure but I will just raise another issue.

**Comment by Jai-JAP** [comment] 2022-06-19 06:15
I am getting the same issue on a fresh win 11 install

**Comment by Cyberdroid1** [comment] 2022-06-20 01:37
Duplicate of #920

**Closed by Cyberdroid1** 2022-06-20 01:37 UTC
Labels: Bug

**Comment by vladivanchik** [comment] 2024-08-26 12:53
> ### ModernFlyouts Version
> 0.9.3.0
> 
> ### Windows version
> Windows 11 Home
> 
> ### OS build
> 22621.160
> 
> ### Platform
> x64
> 
> ### Area(s) with issue?
> General
> 
> ### Steps to reproduce
> ModernFlyouts set to enabled under General -> Default Flyout section does not disable default Windows flyouts.
> 
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/85484530/174465179-505114d0-718a-49ca-bc7b-d33581e6b10b.png">
> 
> ### ✔️ Expected Behavior
> There should be ModernFlyouts only, not both.
> 
> ### ❌ Actual Behavior
> Both are showing up simultaneously.
> 
> ### Other Software
> can reproduce even with:
> 
> 1. no apps opened
> 2. selective startup (a line on "load system services" (only Microsoft services are not disabled) option and unticking the box "load startup items")
> 
> ### Additional Context
> 1. Tried uninstalling it and reinstalling it again, does not help.
> 2. [Similar issue raised previously](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/36). It's under Windows 10 so it's been a while since it's fixed (perhaps)? Maybe the way Windows 11 do volume and brightness pop-ups are different? I am not sure but I will just raise another issue.

Have the same issues since I updatet to windows 11
