### ISSUE TITLE
Bug: The description of some button is behind the flyout

### ISSUE THREAD

**Issue by Chint355** [ModernFlyouts-Community/ModernFlyouts#874] opened 2021-11-17 02:35 UTC
**Describe the bug:**
The description of some button is behind the flyout, pls look at the screenshot.

**Screenshots:**
Like the "pause" word, its behind the flyout
![Untitled](https://user-images.githubusercontent.com/94503306/142105556-769da27b-62ea-40bc-870a-a8e5c34fc7d1.png)

**OS Version:**
 - Windows Version:  Window 10 20H2

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Comment by Cyberdroid1** [comment] 2021-11-17 05:42
Duplicate of #377

**Closed by Cyberdroid1** 2021-11-17 05:43 UTC
Labels: Bug
