### ISSUE TITLE
Bug: Windows default flyout shows when changing volume while holding down mouse buttons.

### ISSUE THREAD

**Issue by timothymhuang** [ModernFlyouts-Community/ModernFlyouts#546] opened 2021-04-06 22:52 UTC
**Describe the bug:**
When you change the volume while holding down the mouse left-click, right-click, middle-click, and the forward and backward buttons, the Windows default flyout will show instead of the ModernFlyouts.

**To Reproduce:**
1. Hold down left-click, right-click, middle-click, forwards, or backward on your mouse.
2. Change the volume with the volume buttons.
3. Notice that the Windows default flyout shows instead of the ModernFlyout.

**Screenshots:**

**OS Version:**
 - Windows 10 Version: Windows 10 Pro 20H2

**ModernFlyouts Version:**
 - Version: 0.9.1.0

**Additional context:**
This bug has also happened to me with other keys, but I wasn't able to reproduce with other keys consistently.

**Comment by ShankarBUS** [comment] 2021-04-08 06:19
Yep! Just realized this. Will be fixed altogether with #4.

**Comment by ShankarBUS** [comment] 2021-04-08 10:06
Dupe of #470

**Closed by ShankarBUS** 2021-04-08 10:06 UTC
Labels: Bug
