### ISSUE TITLE
It can't hide the native modern controller in 22h2.I hope it will be fixed soon.

### ISSUE THREAD

**Issue by ZhangDigital** [ModernFlyouts-Community/ModernFlyouts#1115] opened 2022-10-05 00:43 UTC
### ModernFlyouts Version

0.10.0.0

### Windows version

Windows 11 22H2

### OS build

25211.1010

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout, Camera Flyout, Mic Flyout, Welcome / ModernFlyouts OOBE, System tray

### Steps to reproduce

In windows 11 22h 2, you can reproduce once modern flyers is enabled.

### ✔️ Expected Behavior

Native Modern style controllers can be hidden in Windows 11 22 H 2, I hope the next version can hide the native modern controller in 22h2

### ❌ Actual Behavior

Used to be very good, now updated to win 11 22h 2 after win built into a modern style, at this time can not hide win native volume controller, brightness is the same.

**Comment by Cyberdroid1** [comment] 2022-10-05 08:54
Duplicate of #920

**Closed by Cyberdroid1** 2022-10-05 08:54 UTC
Labels: Bug
