### ISSUE TITLE
Flyout shuts down after a while

### ISSUE THREAD

**Issue by dreadbalaur** [ModernFlyouts-Community/ModernFlyouts#1297] opened 2024-04-30 02:28 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 10 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Launch the flyout and leave it there in the system tray.

### ✔️ Expected Behavior

Flyout keeps running even when laptop runs multiple days without shutting down. 

### ❌ Actual Behavior

Flyout shuts down after a while without notice

### Additional Context

Potential causes? I do a lot of RAM/CPU intensive tasks on my laptop, could Flyout crash when the RAM/CPU is overloaded? Is there a way to set task scheduler to start Flyout again whenever it is shut down?

**Comment by LanxiaoWang** [comment] 2024-06-17 13:28
I also have this situation. It seems to have appeared since I started using an external monitor.

**Comment by dreadbalaur** [comment] 2024-06-23 22:10
Thanks for corroborating. I am also using an external monitor

**Comment by manstheram** [comment] 2024-06-25 14:34
Have you tried the beta?

**Comment by dreadbalaur** [comment] 2024-06-25 14:51
No, I'm running the stable version.

**Comment by manstheram** [comment] 2024-06-25 14:56
Try running this build https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4

**Comment by dreadbalaur** [comment] 2024-06-30 17:49
It happened again after 5 days. This is probably me talking out of my ass but could it be that it is considered low priority, so Windows kills it first if the computer's resource is being taken up by heavy programs?

**Comment by manstheram** [comment] 2024-07-01 06:32
No, you could be right, but it's hard to figure out. However, I think it's just .NET being really unstable and crashing a lot.

**Comment by prakharb5** [comment] 2024-07-23 07:30
Duplicate of #642

**Closed by prakharb5** 2024-07-23 07:30 UTC
Labels: Bug
