### ISSUE TITLE
Bug: Stops running / disappears from tray

### ISSUE THREAD

**Issue by anishre** [ModernFlyouts-Community/ModernFlyouts#862] opened 2021-10-29 23:04 UTC
**Describe the bug:**
Noticed that after a while when I use volume or brightness keys fly-outs preview doesn't show up. I check tray icon and see the app isn't running.

**To Reproduce:**
1. Leave app running
2. Either wait about 12 hours or let PC go to sleep ( which is when i usually noticed it)

**OS Version:**
Edition : Windows 10 Pro
Version : 21H1
OS build : 19043.1320
Experience Windows Feature Experience Pack 120.2212.3920.0

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Comment by Cyberdroid1** [comment] 2021-10-30 06:58
Duplicate of #642

**Closed by Cyberdroid1** 2021-10-30 06:58 UTC
Labels: Bug
