### ISSUE TITLE
Brightness 🔆 Control

### ISSUE THREAD

**Issue by dheerajvirgo** [ModernFlyouts-Community/ModernFlyouts#647] opened 2021-06-04 04:40 UTC
**Is your feature request related to a problem? Please describe:**
Not having brightness controls when using desktops where we use external monitor

**Describe the solution you'd like:**
I know this might be available on devices that have attached displays and I'm guessing the code works replacing the brightness control default but there are apps like Win10_BrightnessSlider.exe and some skins in rainmeter that work independently controlling the brightness of external monitors. So it is possible to write some code to include this

**Describe alternatives you've considered:**
using Win10_BrightnessSlider.exe

**Additional context:**

**Comment by ShankarBUS** [comment] 2021-06-04 12:11
Hehe, wait for da nxt releaz 😎😎😎

**Comment by ShankarBUS** [comment] 2021-06-04 12:11
This issue is a duplicate btw

**Comment by Cyberdroid1** [comment] 2021-06-04 12:12
#222 ?

**Comment by ShankarBUS** [comment] 2021-06-04 12:16
Nah, more back bro

**Comment by ShankarBUS** [comment] 2021-06-04 12:17
Dupe of #102

**Closed** 2021-06-05 15:33 UTC
Labels: Enhancement
