### ISSUE TITLE
Bug: Buggy Flyout after closing Spotify

### ISSUE THREAD

**Issue by cix99** [ModernFlyouts-Community/ModernFlyouts#564] opened 2021-04-13 14:23 UTC
**Describe the bug:**
Buggy Flyout after closing Spotify

**To Reproduce:**
1. Open Spotify and play a song
2. Minimize Spotify while playing
3. Press Volume up/Volume down/Play/Pause on the keyboard while Spotify is minimized, all works fine and the flyout shows all the infos about the song playing.
4. Close Spotify and press Play on the keyboard, it shows the flyout as on the screenshot below (with no info)
5. When reopening Spotify, even though a new song is playing, the flyout shows no more info.

**Screenshots:**
![Flyout-broken](https://user-images.githubusercontent.com/17433641/114568232-3f798500-9c74-11eb-9e47-d1b082eb36a6.jpg)

**OS Version:**
Edition Windows 10 Pro
Version 20H2
OS build 19042.906

**ModernFlyouts Version:**
0.9.1.0

**Comment by Samuel12321** [comment] 2022-03-27 00:37
Duplicate of ##532

**Closed by Samuel12321** 2022-03-27 00:37 UTC
Labels: Bug, Media
