### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by aayushyap89** [ModernFlyouts-Community/ModernFlyouts#623] opened 2021-05-19 01:05 UTC
Hello, I don't know if this is a bug or not yet added but it doesn't automatically disappear off my screen and I have to do that myself from the top bar. Even though there is a setting for the flyout timeout but that doesn't seem to work.

**Comment by Cyberdroid1** [comment] 2021-05-19 04:30
Duplicate of #464.

And please use the correct issue template when opening a new issue 😄

**Closed by Cyberdroid1** 2021-05-19 04:30 UTC
Labels: Enhancement
