### ISSUE TITLE
Bug: Brightness Strangely Broken

### ISSUE THREAD

**Issue by LiamAmsdorf** [ModernFlyouts-Community/ModernFlyouts#871] opened 2021-11-12 08:30 UTC
The Bug is that when I try increase/decrease the brightness with these modern flyouts it like breaks and acts strangely jumping up and down and it maxes at 70.

Steps to reproduce the behaviour:
All you need to do is increase the brightness of your screen on windows when there is access to a Fn Key and a brightness 

**Screenshots:**
![image](https://user-images.githubusercontent.com/77044546/141435237-af6d2639-809b-4028-873c-fd90a4fd49e4.png)
![image](https://user-images.githubusercontent.com/77044546/141435462-b29779f1-7ac1-4bbc-9eba-6a50e55248d4.png)

Windows 10 21H1
ModernFlyouts v0.9.3

**Comment by Cyberdroid1** [comment] 2021-11-12 11:27
Duplicate of #86

**Closed by Cyberdroid1** 2021-11-12 11:27 UTC
Labels: Bug
