### ISSUE TITLE
Bug: Flyout Appears when Changing Keyboard Language

### ISSUE THREAD

**Issue by m4l0n** [ModernFlyouts-Community/ModernFlyouts#700] opened 2021-07-14 01:25 UTC
**Describe the bug:**
When changing the keyboard language, the flyout pops out. Been happening every time I restart my laptop. Had to restart Modern Flyouts so it doesn't pop out when changing keyboard language.

**To Reproduce:**
1. Alt + Shift to change language / Change language from taskbar

**Screenshots:**
![image](https://user-images.githubusercontent.com/67460463/125545696-4bc2cb45-9d6e-4191-b649-c47c564e5eb1.png)

**OS Version:**
 - Windows 10 Version: Windows 10 21H1

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

**Comment by Samuel12321** [comment] 2021-07-14 05:02
Duplicate of #584

Please check before opening up a new issue.

**Closed** 2021-07-14 05:02 UTC
Labels: Bug, Duplicate
