### ISSUE TITLE
Bug: Broken start menu icons

### ISSUE THREAD

**Issue by Dominiquini** [ModernFlyouts-Community/ModernFlyouts#927] opened 2022-01-21 08:40 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro 21H2

### OS build

19044.1469

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

- Install app from Windows Store
- Search for 'ModernFlyouts' on the start menu
- Look at the second panel

### ✔️ Expected Behavior

Only working entries should appear in the start menu!

### ❌ Actual Behavior

After installed the app from Windows Store, some start menu entries under ModernFlyouts was created but is not working:
- Settings
- Restore legacy flyout
- Exit

### Other Software

Windows Store

### Additional Context

![DrnIa0H7t2](https://user-images.githubusercontent.com/1180808/150494550-85d95bb8-c882-4e6a-80fc-095214b8e85c.png)

**Comment by walkxcode** [comment] 2022-01-25 02:19
As far as I know, these have always been the icons.

**Comment by Dominiquini** [comment] 2022-01-25 02:55
But only the 'Open' option is working. All the other options is broken!

![firefox_3YOi3l9g8B](https://user-images.githubusercontent.com/1180808/150902468-476e66ea-bbca-487b-9c3e-50b25c98a165.png)

Thanks

**Comment by Samuel12321** [comment] 2022-01-25 03:27
you are correct it has been broken for a while, will be fixed with 0.11

**Comment by Samuel12321** [comment] 2022-03-27 01:38
Duplicate of #646

**Closed by Samuel12321** 2022-03-27 01:38 UTC
Labels: Bug
