### ISSUE TITLE
Z-index of onhover buttons tool tip on Media not proper

### ISSUE THREAD

**Issue by pohihihisocks** [ModernFlyouts-Community/ModernFlyouts#968] opened 2022-03-06 11:19 UTC
So when you listen to any media on the browser lets say youtube and change the audio, the Media playing will pop up and those extra buttons such as Pause, Play, Next etc will display, when hovering on them, there will be a tooltip saying what that button is for, the tooltip shows behind the media, thats pretty much about it.

**Comment by Cyberdroid1** [comment] 2022-03-06 15:49
It is a known issue noted in the v0.9 release :)

Duplicate of another issue.

**Closed by Cyberdroid1** 2022-03-06 15:49 UTC
