### ISSUE TITLE
Bug: The flyout appear on switching keyboard layout

### ISSUE THREAD

**Issue by remichan97** [ModernFlyouts-Community/ModernFlyouts#972] opened 2022-03-10 13:39 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H2

### OS build

19044.1586

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

On a system with multiple keyboard layout installed, use the keyboard layout switching key combination (Default is Windows key + Space) to change the keyboard.

### ✔️ Expected Behavior

The Flyout should not show up upon switch keyboard layout

### ❌ Actual Behavior

The flyout appears alongside with the keyboard layout selector on the right side of the screen as shown below

![Screenshot (1)](https://user-images.githubusercontent.com/77116130/157673212-0e3b65e8-546d-4822-b058-78f01731deb2.png)

**Comment by arnavbhate** [comment] 2022-03-17 09:36
Duplicate of #584

**Closed** 2022-03-17 16:16 UTC
Labels: Bug
