### ISSUE TITLE
After disuse overnight, Flyouts appear in the correct corner but incorrect display than what's configured in Settings

### ISSUE THREAD

**Issue by Paetrig** [ModernFlyouts-Community/ModernFlyouts#1018] opened 2022-05-20 13:12 UTC
### ModernFlyouts Version

Flyout pin moves to non-primary display intermittently

### Windows version

Windows 11 21H2

### OS build

22000.675

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Setup:
3-display setup (left portrait, center landscape, right portrait)

Replication steps:
1. In Flyout Settings, configure as follows:
      - Display - Center monitor
      - Placement mode - Auto
      - Horizontal alignment - Right
      - Vertical alignment - Bottom
3. Lock the machine (do not shutdown).
4. Leave the machine alone to replicate a period of disuse (e.g., workstation is not used outside of work hours).
5. Return to the workstation and use the media keys or adjust the volume.
6. Flyout appears in the correct corner (Bottom-Right) but the incorrect display (Left).
7. Verify Settings has retained correct alignment but incorrect display is now set as Primary.

### ✔️ Expected Behavior

Flyouts is meant to appear as configured in the Settings of the app, but it is not the case after logging back in after a period of disuse (e.g., remaining locked overnight)

### ❌ Actual Behavior

Flyout appears in the correct alignment but on the incorrect display

### Other Software

Appears to be an issue regardless of app; I have replicated this with the following programs:
- Zoom
- Teams
- Slack
- Cider
- YouTube (web version)

### Additional Context

Please feel free to reach out for additional information as needed.

**Comment by creeve4** [comment] 2022-05-20 20:55
Also experiencing this after undocking and redocking my laptop with multiple monitors.

**Comment by YSCohen** [comment] 2022-05-31 13:39
Also experiencing this after shutting down and booting my laptop; all the settings get reset to defaults

**Comment by Cyberdroid1** [comment] 2022-08-26 01:05
Duplicate of #604

**Closed by Cyberdroid1** 2022-08-26 01:05 UTC
Labels: Bug
