### ISSUE TITLE
Windows 11 22H2 Flyout Bug

### ISSUE THREAD

**Issue by Bysic** [ModernFlyouts-Community/ModernFlyouts#1107] opened 2022-09-26 14:32 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 22H2

### OS build

22621.521

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

The App's volume flyout shows up with the default windows flyout instead of hiding it

### ✔️ Expected Behavior

Only the App's Flyout should be shown

### ❌ Actual Behavior

The App's volume Flyout shows up with the default Windows Flyout

![Screenshot (1)](https://user-images.githubusercontent.com/62754606/192303356-a21c4c19-3a89-4575-ab58-cb0191ebe29e.png)

**Comment by BPilot253** [comment] 2022-09-28 11:51
I can say I'm also experiencing this.

**Comment by chak39** [comment] 2022-09-29 07:16
I just got this app from the Microsoft store and can confirm I have the same issue

**Comment by Samuel12321** [comment] 2022-10-02 02:21
Hi,
Thanks for reporting this. We are aware of the problem and plan to fix this in the next update 0.11.

Closing as duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/920

**Closed by Samuel12321** 2022-10-02 02:21 UTC
Labels: Bug
