### ISSUE TITLE
Bug: When a media is playing, animation it's lagged.

### ISSUE THREAD

**Issue by MauricioGlez** [ModernFlyouts-Community/ModernFlyouts#625] opened 2021-05-21 15:11 UTC
**Describe the bug:**
When a media is playing, the fadeout animation becomes kind of laggy and not smooth as if there were no media.

**To Reproduce:**

Play any media
Change volume.

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**
If related, i'm using an AMD APU A12 with a Radeon R7 graphics card.

**Comment by Cyberdroid1** [comment] 2021-05-22 14:47
Duplicate of #487

**Closed by Cyberdroid1** 2021-05-22 14:47 UTC
Labels: Bug
