### ISSUE TITLE
Store Images

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#58] opened 2020-09-25 03:50 UTC
We need better images for MS Store:

The images need to have the labels in the image and preferably show windows original vs Modern flyouts.

There can only be 10 screenshots with the following requirements:
- 1366 x 768 pixels or larger recommended
- Supports 4K images (3840 x 2160)
- Max upload 10 files
- Landscape or portrait
- Accepted file types: .png
- Less than 50 MB

Additionally there are other features the store allows which i haven't used yet but we can decide to make:

**Banner for store page (which they call superhero art):**
Requirements:
16:9 Super hero art appears at the top of your Store listing (or after any trailers finish playing) for customers on Windows 10, version 1607 or later (which includes Xbox). Learn more
Must not include the product's title
Required if you want one of your trailers to appear at the top of the Store listing
Accepted file types: .png
Less than 50 MB

**A Trailer:**
Requirements:
Trailers are only shown to customers on Windows 10, version 1607 or later (including Xbox)
Max upload 15 trailers
Each trailer must include one video, a title and a thumbnail
Video file types: .mp4 (recommended), .mov
Thumbnail files must be .png files, 1920 x1080 pixels
Title character limit: 255
Do not include IARC age rating info
[Learn more about trailer requirements](https://docs.microsoft.com/en-us/windows/uwp/publish/app-screenshots-and-images#trailers)

**Comment by ShankarBUS** [comment] 2020-09-25 04:14
Thanks for the information! I will do the image editing and make some good user friendly & attractive trailers and screenshots.

Should we upload the video directly to store or are they required to be uploaded to some media hosting sites (such as YouTube)?

**Comment by Samuel12321** [comment] 2020-09-25 04:21
All direct to store

**Comment by Cyberdroid1** [comment] 2020-09-27 11:03
https://github.com/ShankarBUS/ModernFlyouts/issues/55#issuecomment-699619222

@Samuel12321, What do you say?

**Comment by ShankarBUS** [comment] 2020-09-27 11:07
We got too many documentation (Wiki, images, README, release notes) work for v0.6. There is not much feature wise. But at least this attract some users 😂

**Comment by Cyberdroid1** [comment] 2020-09-27 14:30
Can we add this to v1 milestone/project?

**Comment by Cyberdroid1** [comment] 2020-09-27 17:20
In the ReadMe images, we have a section of media flyout images. Can we please change the image to show another file playing as that file (please don't get offended) looks a bit unprofessional. Can we replace it with some other file like used in here - https://github.com/ShankarBUS/ModernFlyouts/issues/6#issuecomment-665917276

It would be great to keep the files generic.

**Comment by ShankarBUS** [comment] 2020-09-27 17:26
I'm offended, JK

I know they look silly and unprofessional.
But I had to put what I had at that time. I don't have that much media on my system. All of them are old and outdated. Can you provide some good sample media? I don't have the time to pick them 😅.

I'll focus on fixing the issues, can you help me with the media selection and what sample images to put?

**Comment by Cyberdroid1** [comment] 2020-09-27 17:35
What do you say about Kalimba by Mr Scruff? 

I will send the mp3 on Telegram as GitHub doesnt support mp3 files.

**Comment by ShankarBUS** [comment] 2020-09-27 17:37
I also need a video file to showcase the timeline properties support we provide. Can you pack the audio (*.MP3) and a video file (*.MP4 preferably) as a *.zip file on GitHub?

**Comment by Cyberdroid1** [comment] 2020-09-27 17:38
Hmm, video file. Ok, will see to it.

**Comment by Cyberdroid1** [comment] 2020-09-27 18:06
[Files.zip](https://github.com/ShankarBUS/ModernFlyouts/files/5288790/Files.zip)

Here you go. Tell if it works as intended.

**Comment by ShankarBUS** [comment] 2020-09-27 18:58
Thanks @Cyberdroid1, I will use these medias to make the screenshots for the next release 👍.

**Comment by Samuel12321** [comment] 2020-09-27 19:58
> [#55 (comment)](https://github.com/ShankarBUS/ModernFlyouts/issues/55#issuecomment-699619222)
> 
> @Samuel12321, What do you say?

Brilliant. Perhaps a caption above stating light and dark theme is needed but otherwise great.

**Comment by Cyberdroid1** [comment] 2020-09-28 02:44
We can add captions with the same font being used in the flyout. Light color font for Dark theme, and dark color font for Light theme.

**Comment by Samuel12321** [comment] 2020-09-28 02:46
great

**Comment by Cyberdroid1** [comment] 2020-10-06 08:19
[Pictures.zip](https://github.com/ShankarBUS/ModernFlyouts/files/5332287/Pictures.zip)

I have merged the light and dark pictures. Just add captions and it is ready to go.

**Comment by ShankarBUS** [comment] 2020-10-06 08:22
Cool pal! 😁

**Comment by ShankarBUS** [comment] 2020-10-06 08:25
Hey @Samuel12321, Can you update the README to include these?

We have to redo these images for v0.8 though

**Comment by Cyberdroid1** [comment] 2020-10-06 08:33
Redo? Will there be a design of the flyouts?

**Comment by ShankarBUS** [comment] 2020-10-06 08:39
Could be? I prefer taking new screenshots for every releases.

For v0.8 we need to update the store images (1366x768 res images) and trailers. While doing so  we should also update the images on README

The current images on README will be moved into respective Wiki pages

**Comment by Cyberdroid1** [comment] 2020-10-25 17:39
![image](https://user-images.githubusercontent.com/51435948/97114521-0164c500-1717-11eb-8194-db57cca796e9.png)

Doesn't look exactly appealing, 😅

![image](https://user-images.githubusercontent.com/51435948/97114540-180b1c00-1717-11eb-8eea-7ec04d5b56b6.png)
This looks better, but can we use Segoe UI for the text, please?

**Comment by Cyberdroid1** [comment] 2020-10-25 17:50
Some changes in features, as there is a LOT OF TEXT currently. We need to keep it small and simple.

![image](https://user-images.githubusercontent.com/51435948/97114782-93b99880-1718-11eb-8cc6-1841254f3057.png)

**Comment by Samuel12321** [comment] 2020-10-25 20:30
> Some changes in features text, as there is a LOT OF TEXT currently. We need to keep it short and simple.
> 
> ![image](https://user-images.githubusercontent.com/51435948/97114782-93b99880-1718-11eb-8cc6-1841254f3057.png)
> 
> We don't have to tell the user each and every thing. There should be some excitement in the person's mind too, I hope you get my point.

Agreed, have updated this

**Comment by Samuel12321** [comment] 2020-10-25 20:34
> ☝☝☝ Doesn't look exactly appealing, 😅

i know

I agree with all your other suggestions. I don't currently have time to do a lot of work with the images. However if anyone has improved images i am very happy to use them instead.

**Comment by ShankarBUS** [comment] 2020-10-25 23:57
@Samuel12321,

Don't worry I'm planning to add Wiki before v0.8 release. I'll update the screenshots and README together with it 😄

Take care pal 👊

**Comment by Cyberdroid1** [comment] 2020-10-26 07:01
![image](https://user-images.githubusercontent.com/51435948/97142540-cef2b080-1786-11eb-88e7-dfbb17405060.png)

Tried this. What do you say?

**Comment by ShankarBUS** [comment] 2020-10-26 07:02
What font did you use?

Looks neat but too thin. Could you try semi-light?

**Comment by Samuel12321** [comment] 2020-10-26 07:04
i agree, it think its too thin. 
I also think the light / dark text should be above, or at least fully below the flyout.

**Comment by Cyberdroid1** [comment] 2020-10-26 07:04
I used SEGOE UI LIGHT

**Comment by Cyberdroid1** [comment] 2020-10-26 07:06
![image](https://user-images.githubusercontent.com/51435948/97143008-dc5c6a80-1787-11eb-8b17-19f903318e58.png)

This is SEGOE UI SEMILIGHT

**Comment by Cyberdroid1** [comment] 2020-10-26 07:07
Keeping the text of Light/Dark above the flyout wont be suitable, since there is already text of TOPBAR ON.

**Comment by Samuel12321** [comment] 2020-10-26 07:09
Below is fine, before it was sort of half way
i still think it's still slightly too thin.
Personally i also think the Dark text should be used under dark and light under light.

**Comment by ShankarBUS** [comment] 2020-10-26 07:09
It's still too thin. What about `Segoe UI Regular`?

Oh oh oh!!!, what about making it similar to the text in the airplane mode flyout?

**Comment by Cyberdroid1** [comment] 2020-10-26 07:10
More contrast = more readabilty, thats why exchange in color.

**Comment by Cyberdroid1** [comment] 2020-10-26 07:10
> It's still too thin. What about `Segoe UI Regular`?
> 
> Oh oh oh!!!, what about making it similar to the text in the airplane mode flyout?

Not the same font, not at all!

**Comment by ShankarBUS** [comment] 2020-10-26 07:11
@Cyberdroid1,

> Not the same font, not at all!

wut?

**Comment by Cyberdroid1** [comment] 2020-10-26 07:12
Not the same font as that of the Airplane text!

BTW, did this

![image](https://user-images.githubusercontent.com/51435948/97143460-bedbd080-1788-11eb-9aa5-707b1eb255a3.png)

**Comment by Cyberdroid1** [comment] 2020-10-26 07:13
> And what image editor did you use?

Glad you asked, it is MS-Paint. 🤣🤣🤣

**Comment by Cyberdroid1** [comment] 2020-10-26 07:14
![image](https://user-images.githubusercontent.com/51435948/97143606-02363f00-1789-11eb-95b5-e5ca337eb59c.png)

Looks boring in regular, TBH

**Comment by ShankarBUS** [comment] 2020-10-26 07:15
@Cyberdroid1,

> Not the same font as that of the Airplane text!

You don't want it to look like the text style in airplane mode flyout?

> MS Paint

Bruuuuuuuhhhhhhhhhh!!!!!!

**Comment by ShankarBUS** [comment] 2020-10-26 07:16
`Segoe UI SemiBold` 16px how bout dat?

**Comment by Cyberdroid1** [comment] 2020-10-26 07:17
> Bruuuuuuuhhhhhhhhhh!!!!!!

I have a good experience with that, 😂
 
> You don't want it to look like the text style in airplane mode flyout?

Um, no actually. Variety of style, fresh.

**Comment by Cyberdroid1** [comment] 2020-10-26 07:18
> `Segoe UI SemiBold` 16px how bout dat?

Let me try.

**Comment by Cyberdroid1** [comment] 2020-10-26 07:19
![image](https://user-images.githubusercontent.com/51435948/97143935-9a342880-1789-11eb-9bbf-ab2117919a8c.png)

Oooof, this fat

**Comment by ShankarBUS** [comment] 2020-10-26 07:20
Oh shit! Fallback!

**Comment by Samuel12321** [comment] 2020-10-26 07:21
i think it is almost right, just slightly too fat

**Comment by Cyberdroid1** [comment] 2020-10-26 07:21
> BTW, did this
> 
> ![image](https://user-images.githubusercontent.com/51435948/97143460-bedbd080-1788-11eb-9aa5-707b1eb255a3.png)

What do you say about this?

**Comment by Samuel12321** [comment] 2020-10-26 07:23
i prefer the segoe

**Comment by Cyberdroid1** [comment] 2020-10-26 07:24
> i prefer the segoe

FYI, this IS Segoe, XD. I understand what you mean. 

![image](https://user-images.githubusercontent.com/51435948/97144394-5d1c6600-178a-11eb-996f-251abe4ddc39.png)

Anyone of these?

**Comment by Samuel12321** [comment] 2020-10-26 07:31
what about segoe ui symbol

**Comment by Cyberdroid1** [comment] 2020-10-26 07:38
![image](https://user-images.githubusercontent.com/51435948/97145483-4b3bc280-178c-11eb-8a79-7284633e8fe0.png)

Umm, doesnt look much different to me.

**Comment by Samuel12321** [comment] 2020-10-27 00:50
i think it's fine

**Comment by Samuel12321** [comment] 2020-10-27 00:50
i'll add this one to the store

**Comment by Cyberdroid1** [comment] 2020-10-29 07:07
![image](https://user-images.githubusercontent.com/51435948/97536637-79670f80-19e3-11eb-8473-2c19ae3937e6.png)

and

![image](https://user-images.githubusercontent.com/51435948/97536657-8257e100-19e3-11eb-9225-299d4a8acbe3.png)

Why is it present twice in store?

**Comment by Cyberdroid1** [comment] 2021-01-25 05:14
Now there is greater need to update the store images. Can I create?

**Closed** 2021-05-28 04:06 UTC
Labels: Documentation, Enhancement
