### ISSUE TITLE
Feature Request: change volume of non default device.

### ISSUE THREAD

**Issue by musteline** [ModernFlyouts-Community/ModernFlyouts#786] opened 2021-08-28 01:26 UTC
I wish i could choose a different device other than default to change the volume, like my headphone instead of default speaker, i cant in normal windows anyway but it would be nice. 
Mainly a problem when using voicemeeter banana with a virtual input.

**Comment by Cyberdroid1** [comment] 2021-08-28 05:24
Duplicate of #336.

**Closed by Cyberdroid1** 2021-08-28 05:24 UTC
Labels: Enhancement
