### ISSUE TITLE
Bug: Tray icon sometimes appears, even if it's set to hidden in the settings

### ISSUE THREAD

**Issue by Elaborendum** [ModernFlyouts-Community/ModernFlyouts#977] opened 2022-03-20 23:12 UTC
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H2

### Platform

x64

### Area(s) with issue?

System tray

### Steps to reproduce

1. Run the app at start up, have the option to show the tray icon turned off
2. Wait for the app to load, occasionally the tray icon (or an empty space where it should be) appears

Since it doesn't always happen, so I'm not entirely sure how reliable these instructions are

### ❌ Actual Behavior

Sometimes, despite having the option to show the tray icon turned off, the tray icon will appear (or an empty space representing the icon image).

Going to the settings and toggling the option off and on again fixes the issue for that moment.

**Comment by NJUsunset** [comment] 2022-04-15 03:58
same problem on windows 11 21H2

**Comment by wefalltomorrow** [comment] 2024-10-28 09:51
Likely the same issue as #281

**Comment by prakharb5** [comment] 2024-11-26 22:18
Duplicate of #281

**Closed by prakharb5** 2024-11-26 22:18 UTC
Labels: Bug
