### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by enusan** [ModernFlyouts-Community/ModernFlyouts#922] opened 2022-01-14 09:22 UTC
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 Dev

### OS build

22533.1001

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

- Install and enable ModernFlyouts before update to latest Insider Dev build
- Update to Insider Dev 22533.1001 build
- Press any volume or brightness key multiple time

### ✔️ Expected Behavior

flyout is popped up and volume or brightness is changed 

### ❌ Actual Behavior

When press key multiple time, Windows Shell(explorer.exe) is crashed. If it only pressed one time, flyout is displayed normally.

### Additional Context

When disable Audio flyouts in ModernFlyouts settings, both app and Shell is crash too.

**Comment by Bertiberlino** [comment] 2022-01-14 15:35
i have the same issue

**Comment by sannier3** [comment] 2022-01-14 17:03
I also have the same problem, but my problem was closed because I used other software with it but this problem was not caused by other software. It can work with my other software (RoundedTB & Start11) but when my Windows has been updated the explorer will restart when I press the volume button

**Comment by Cyberdroid1** [comment] 2022-01-16 10:51
@enusan @Bertiberlino 
![image](https://user-images.githubusercontent.com/51435948/149656922-73c1e38e-20ee-4488-8478-46fe4ae5ff67.png)
https://blogs.windows.com/windows-insider/2022/01/12/announcing-windows-11-insider-preview-build-22533/

The explorer crash is a known issue in the latest Dev build, which is what you are running.

**Comment by Samuel12321** [comment] 2022-01-20 08:30
https://aka.ms/AAfguio
Fixed in latest build

**Closed by Samuel12321** 2022-01-20 08:30 UTC
Labels: Bug
