### ISSUE TITLE
Feature Request: When the volume is changed via a windows precision trackpad the new flyout doesn't appear, only the old one. The issue is also present if the volume is changed trough a bluetooth device.

### ISSUE THREAD

**Issue by Sajtospoga01** [ModernFlyouts-Community/ModernFlyouts#539] opened 2021-04-04 12:37 UTC
**Describe alternatives you've considered:**
I don't know how the original program works but maybe using events for the volume change could eliminate the issue.

**Comment by Cyberdroid1** [comment] 2021-04-04 13:17
Dupe of #4

**Closed** 2021-04-04 23:04 UTC
Labels: Bug, Duplicate

**Comment by Samuel12321** [comment] 2021-04-04 23:06
@Sajtospoga01 If you have any ideas of how to fix this problem they would be greatly appreciated, would you mind discussing it on #4
