### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Hiperfast25** [ModernFlyouts-Community/ModernFlyouts#820] opened 2021-09-27 15:24 UTC
**Describe the bug:**
My flyout doesn't appear when I'm listening to music and it just appears when I turn Capslock on or off. Whenever I try to turn off the audio Flyout the app stops working.

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version:  Windows 10 19042.1237

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

**Comment by Cyberdroid1** [comment] 2021-09-27 16:58
Duplicate of #710 
<h2> Please search your issue before opening a new issue.

**Closed by Cyberdroid1** 2021-09-27 16:58 UTC
Labels: Bug

**Comment by Hiperfast25** [comment] 2021-09-28 13:23
Hi. I haven't been able to fix the flyout. The flyouts don't appear for me, only the caps and lock numbers and whenever I try to turn off the audio flyout it crashes.
