### ISSUE TITLE
Bug: App crashes when switching off the audio flyout module

### ISSUE THREAD

**Issue by jimchen5209** [ModernFlyouts-Community/ModernFlyouts#788] opened 2021-08-29 01:23 UTC
**Describe the bug:**

App crashes when I am trying to switch off this option because of device volume mentioned in #778
![image](https://user-images.githubusercontent.com/10269287/131234764-bc73ee99-aa0a-4641-a1bf-6ebe6368cdcc.png)

**To Reproduce:**

1. Go to **Audio** under **Flyout modules** 
2. Click on the switch under **Enable Audio Flyout**
3. App crashed

**OS Version:**
 - Windows 10 Version:   21H1 build 19043.1200

**ModernFlyouts Version:**
 - Version:  0.9.3.0

**Additional context:**

Two events created in event log

Event 1023: .NET Runtime
```
Application: ModernFlyoutsHost.exe
CoreCLR Version: 6.0.21.21303
.NET Version: 6.0.0-preview.4.21213.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC6C06AE12 (00007FFC6C000000) with exit code c0000005.
```

Event 1000: Application Error 
```
Faulting application name: ModernFlyoutsHost.exe, version: 10.0.17763.1, time stamp: 0x4f2d499e
Faulting module name: coreclr.dll, version: 6.0.21.21303, time stamp: 0x607597ef
Exception code: 0xc0000005
Fault offset: 0x000000000006ae12
Faulting process id: 0x5c5c
Faulting application start time: 0x01d79c7117043e05
Faulting application path: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg\ModernFlyoutsHost.exe
Faulting module path: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg\coreclr.dll
Report Id: a8695f02-24dd-4c7b-a325-e6f45056665a
Faulting package full name: 32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg
Faulting package-relative application ID: App
```

[20210829-modernflyout-eventlogs.zip](https://github.com/ModernFlyouts-Community/ModernFlyouts/files/7071740/20210829-modernflyout-eventlogs.zip)

**Comment by Cyberdroid1** [comment] 2021-08-29 09:12
Thanks, a fix has been found and will be released with next update.
Duplicate of #592

**Closed by Cyberdroid1** 2021-08-29 09:12 UTC
Labels: Bug
