### ISSUE TITLE
Feature Request: Option to disable backgroud media image 

### ISSUE THREAD

**Issue by fheck** [ModernFlyouts-Community/ModernFlyouts#314] opened 2020-12-17 09:55 UTC
**Is your feature request related to a problem? Please describe:**

No, it's only a style choice.

**Describe the solution you'd like:**

I would like to disable the background image in the media control part of the audio flyout, that is displayed over the whole section additionally to the thumbnail image. Best option IMHO would be trough a toggle in the settings.

**Describe alternatives you've considered:**

Not applicable.

**Additional context:**

The reason I would like this to have disabled, is the background image clutters the view, especially when transparency is enable. If a "loud" image is displayed, the information (text, controls) in the flyout itself is harder to discern.

**Comment by Cyberdroid1** [comment] 2020-12-17 10:56
Duplicate of #224. Check out that issue.

**Closed** 2020-12-17 10:56 UTC
Labels: enhancement

**Comment by fheck** [comment] 2020-12-17 10:59
Oh, sorry, I did search for duplicates before posting, but I didn't see that one. That seems to be what I suggested as well.

**Comment by Samuel12321** [comment] 2020-12-17 11:00
all good
