### ISSUE TITLE
Three finger gesture support

### ISSUE THREAD

**Issue by sal4180910** [ModernFlyouts-Community/ModernFlyouts#82] opened 2020-10-03 13:08 UTC
Really like the app, just would like one addition. Using the normal function keys, it works perfectly. But when I use a three finger swipe (up to increase volume, down to decrease, left for previous, and right for next), the old UI comes in. Since I almost always use the three finger swipe, I don't really get to experience the app. Can you please add a switch so that three finger swipes enable the flyout?

**Comment by ShankarBUS** [comment] 2020-10-03 13:25
This is a duplicate or a part of #4

See https://github.com/ShankarBUS/ModernFlyouts/issues/4#issuecomment-665840978

Unfortunately, Windows completely makes it impossible to hook the trackpad swipes and gestures. I can't answer whether it's possible or not.

@ADeltaX FYI (sorry for disturbing you 😅)

**Comment by Cyberdroid1** [comment] 2020-12-20 10:19
Closing it as a duplicate of #4

**Closed by Cyberdroid1** 2020-12-20 10:19 UTC
Labels: High Priority, bug, enhancement, good first issue
